package gw.specContrib.classes.method_Scoring.block_Types

class Errant_BlocksMS_BlockInterfaceObject {

  class JJ{}
  class KK{}
  class LL{}
  interface I{
    function hello()
  }

  function foo1(b : block()) : JJ{
    return null
  }
  function foo1(i : I) : KK{
    return null
  }
  function foo1(o : Object) : LL{
    return null
  }

  function caller() {
    var a111 : JJ = foo1(\ -> {})
    var b111 : KK = foo1(\ -> {})      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.BLOCKS_METHODSCORING.BLOCKSINTERFACESTRUCTURESASPARAMS.BLOCKSMS_BLOCKINTERFACEOBJECT.JJ', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.BLOCKS_METHODSCORING.BLOCKSINTERFACESTRUCTURESASPARAMS.BLOCKSMS_BLOCKINTERFACEOBJECT.KK'
    var c111 : LL = foo1(\ -> {})      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.BLOCKS_METHODSCORING.BLOCKSINTERFACESTRUCTURESASPARAMS.BLOCKSMS_BLOCKINTERFACEOBJECT.JJ', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.BLOCKS_METHODSCORING.BLOCKSINTERFACESTRUCTURESASPARAMS.BLOCKSMS_BLOCKINTERFACEOBJECT.LL'
  }
}