package gw.specContrib.classes.method_Scoring.block_Types

class Errant_BlocksMS_InterfaceInterfaceDiffParam {

  class JJ{}
  class KK{}
  interface I{
    function hello(i : int)
  }
  interface S {
    function hello(s : String)
  }

  function foo1(i : I) : JJ{
    return null
  }
  function foo1(s : S) : KK{
    return null
  }

  function caller() {
    var a111 : JJ = foo1(\ s : int -> {})
    var a112 : JJ = foo1(\ s : String -> {})      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.BLOCKS_METHODSCORING.BLOCKSINTERFACESTRUCTURESASPARAMS.ERRANT_BLOCKSMS_INTERFACEINTERFACEDIFFPARAM.KK', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.BLOCKS_METHODSCORING.BLOCKSINTERFACESTRUCTURESASPARAMS.ERRANT_BLOCKSMS_INTERFACEINTERFACEDIFFPARAM.JJ'

    var b111 : KK = foo1(\ i : int -> {})      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.BLOCKS_METHODSCORING.BLOCKSINTERFACESTRUCTURESASPARAMS.ERRANT_BLOCKSMS_INTERFACEINTERFACEDIFFPARAM.JJ', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.BLOCKS_METHODSCORING.BLOCKSINTERFACESTRUCTURESASPARAMS.ERRANT_BLOCKSMS_INTERFACEINTERFACEDIFFPARAM.KK'
    var b112 : KK = foo1(\ s : String -> {})
  }
}