package gw.specContrib.classes.property_Declarations.javaClassGosuSubClass;

public class Errant_JavaSuper_FunctionVsFunction_4 {

  String getNormalProperty()  { return null; }
  void setNormalProperty(String s){}

  //Should not show error as the function generated by property will be getsmallCaseProperty3() with small 's'
  String getsmallCaseProperty1()  { return null; }
  void setsmallCaseProperty1(String s){}

  String getsmallCaseProperty2() { return null; }
  void setsmallCaseProperty2(String s){}

  //Should not show error as the function generated by property will be getSmallCaseProperty3() with Capital 'S'
  String getSmallCaseProperty3() { return null; }
  void setSmallCaseProperty3(String s){}


  String getOnlyGetter1() { return null; }
  String getOnlyGetter2() { return null; }

  void setOnlySetter1(String s) { }
  void setOnlySetter2(String s) { }
}
