package gw.specContrib.featureLiterals.gosuMembersBinding

class Errant_BindGosuMethods {
  //methods
  //IDE-1375
  var internalFunction111 = GosuFL#gosuInternalFun(String,  int)
  var internalFunction112 = GosuFL#gosuInternalFun("mystring", 44)
  var internalFunction113 = GosuFL#gosuInternalFun()
  var internalFunction114 = GosuFL#gosuInternalFun(GosuFL)      //## issuekeys: CANNOT RESOLVE METHOD 'GOSUINTERNALFUN(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL)'
  var internalFunction115 = GosuFL#gosuInternalFun(GosuFL, String, int)      //## issuekeys: CANNOT RESOLVE METHOD 'GOSUINTERNALFUN(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)'
  var internalFunction116 = GosuFL#gosuInternalFun(GosuFL, "mystring", 42)      //## issuekeys: 'GOSUINTERNALFUN(JAVA.LANG.STRING, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL' CANNOT BE APPLIED TO '(GW.LANG.__PSI__.METATYPE<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL>, JAVA.LANG.STRING, INT)'
  var internalFunction117 = GosuFL#gosuInternalFun(int, String)      //## issuekeys: CANNOT RESOLVE METHOD 'GOSUINTERNALFUN(INT, JAVA.LANG.STRING)'
  var internalFunction118 = GosuFL#gosuInternalFun(42, "mystring")      //## issuekeys: 'GOSUINTERNALFUN(JAVA.LANG.STRING, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL' CANNOT BE APPLIED TO '(INT, JAVA.LANG.STRING)'
  var internalFunction119 = GosuFL#gosuInternalFun      //## issuekeys: CANNOT RESOLVE SYMBOL 'GOSUINTERNALFUN'

  var privateFunction111 = GosuFL#gosuPrivateFun(String, int)
  var privateFunction112 = GosuFL#gosuPrivateFun("mystring", 44)
  var privateFunction113 = GosuFL#gosuPrivateFun()
  var privateFunction114 = GosuFL#gosuPrivateFun(GosuFL)      //## issuekeys: CANNOT RESOLVE METHOD 'GOSUPRIVATEFUN(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL)'
  var privateFunction115 = GosuFL#gosuPrivateFun(GosuFL, String, int)      //## issuekeys: CANNOT RESOLVE METHOD 'GOSUPRIVATEFUN(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)'
  var privateFunction116 = GosuFL#gosuPrivateFun(GosuFL, "mystring", 42)      //## issuekeys: 'GOSUPRIVATEFUN(JAVA.LANG.STRING, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL' CANNOT BE APPLIED TO '(GW.LANG.__PSI__.METATYPE<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL>, JAVA.LANG.STRING, INT)'
  var privateFunction117 = GosuFL#gosuPrivateFun(int, String)      //## issuekeys: CANNOT RESOLVE METHOD 'GOSUPRIVATEFUN(INT, JAVA.LANG.STRING)'
  var privateFunction118 = GosuFL#gosuPrivateFun(42, "mystring")      //## issuekeys: 'GOSUPRIVATEFUN(JAVA.LANG.STRING, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL' CANNOT BE APPLIED TO '(INT, JAVA.LANG.STRING)'
  var privateFunction119 = GosuFL#gosuPrivateFun      //## issuekeys: CANNOT RESOLVE SYMBOL 'GOSUPRIVATEFUN'

  var protectedFunction111 = GosuFL#gosuProtectedFun(String, int)
  var protectedFunction112 = GosuFL#gosuProtectedFun("mystring", 44)
  var protectedFunction113 = GosuFL#gosuProtectedFun()
  var protectedFunction114 = GosuFL#gosuProtectedFun(GosuFL)      //## issuekeys: CANNOT RESOLVE METHOD 'GOSUPROTECTEDFUN(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL)'
  var protectedFunction115 = GosuFL#gosuProtectedFun(GosuFL, String, int)      //## issuekeys: CANNOT RESOLVE METHOD 'GOSUPROTECTEDFUN(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)'
  var protectedFunction116 = GosuFL#gosuProtectedFun(GosuFL, "mystring", 42)      //## issuekeys: 'GOSUPROTECTEDFUN(JAVA.LANG.STRING, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL' CANNOT BE APPLIED TO '(GW.LANG.__PSI__.METATYPE<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL>, JAVA.LANG.STRING, INT)'
  var protectedFunction117 = GosuFL#gosuProtectedFun(int, String)      //## issuekeys: CANNOT RESOLVE METHOD 'GOSUPROTECTEDFUN(INT, JAVA.LANG.STRING)'
  var protectedFunction118 = GosuFL#gosuProtectedFun(42, "mystring")      //## issuekeys: 'GOSUPROTECTEDFUN(JAVA.LANG.STRING, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL' CANNOT BE APPLIED TO '(INT, JAVA.LANG.STRING)'
  var protectedFunction119 = GosuFL#gosuProtectedFun      //## issuekeys: CANNOT RESOLVE SYMBOL 'GOSUPROTECTEDFUN'


  var publicFunction111 = GosuFL#gosuPublicFun(String, int)
  var publicFunction112 = GosuFL#gosuPublicFun("mystring", 44)
  var publicFunction113 = GosuFL#gosuPublicFun()
  var publicFunction114 = GosuFL#gosuPublicFun(GosuFL)      //## issuekeys: CANNOT RESOLVE METHOD 'GOSUPUBLICFUN(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL)'
  var publicFunction115 = GosuFL#gosuPublicFun(GosuFL, String, int)      //## issuekeys: CANNOT RESOLVE METHOD 'GOSUPUBLICFUN(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)'
  var publicFunction116 = GosuFL#gosuPublicFun(GosuFL, "mystring", 42)      //## issuekeys: 'GOSUPUBLICFUN(JAVA.LANG.STRING, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL' CANNOT BE APPLIED TO '(GW.LANG.__PSI__.METATYPE<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL>, JAVA.LANG.STRING, INT)'
  var publicFunction117 = GosuFL#gosuPublicFun(int, String)      //## issuekeys: CANNOT RESOLVE METHOD 'GOSUPUBLICFUN(INT, JAVA.LANG.STRING)'
  var publicFunction118 = GosuFL#gosuPublicFun(42, "mystring")      //## issuekeys: 'GOSUPUBLICFUN(JAVA.LANG.STRING, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL' CANNOT BE APPLIED TO '(INT, JAVA.LANG.STRING)'
  var publicFunction119 = GosuFL#gosuPublicFun      //## issuekeys: CANNOT RESOLVE SYMBOL 'GOSUPUBLICFUN'


  function invokeGosuFunctions() {
    var gInstance : GosuFL

    //Invoking : GosuFL#gosuInternalFun(String, int)
    internalFunction111.invoke(gInstance, "Ed", 42)
    internalFunction111.invoke(gInstance)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL)'
    internalFunction111.invoke(GosuFL, String, int)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.LANG.__PSI__.METATYPE<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL>, GW.LANG.__PSI__.METATYPE<JAVA.LANG.STRING>, GW.LANG.__PSI__.METATYPE<INT>)'
    internalFunction111.invoke(GosuFL, "Ed", 42)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.LANG.__PSI__.METATYPE<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL>, JAVA.LANG.STRING, INT)'
    internalFunction111.invoke(gInstance, String, int)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, GW.LANG.__PSI__.METATYPE<JAVA.LANG.STRING>, GW.LANG.__PSI__.METATYPE<INT>)'
    internalFunction111.invoke("Ed", 42)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(JAVA.LANG.STRING, INT)'
    internalFunction111.invoke(String, int)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.LANG.__PSI__.METATYPE<JAVA.LANG.STRING>, GW.LANG.__PSI__.METATYPE<INT>)'
    internalFunction111.invoke(gInstance, "Ed")      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING)'
    internalFunction111.invoke(gInstance, 42)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, INT)'
    //Invoking : GosuFL#gosuInternalFun("mystring", 44)
    internalFunction112.invoke(gInstance, "Ed", 42)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)'
    internalFunction112.invoke(gInstance)
    //Invoking : GosuFL#gosuInternalFun()
    internalFunction113.invoke(gInstance, "Ed", 42)
    internalFunction113.invoke(gInstance)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL)'


    //Invoking : GosuFL#gosuPrivateFun(String, int)
    privateFunction111.invoke(gInstance, "Ed", 42)
    privateFunction111.invoke(gInstance)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL)'
    privateFunction111.invoke(GosuFL, String, int)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.LANG.__PSI__.METATYPE<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL>, GW.LANG.__PSI__.METATYPE<JAVA.LANG.STRING>, GW.LANG.__PSI__.METATYPE<INT>)'
    privateFunction111.invoke(GosuFL, "Ed", 42)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.LANG.__PSI__.METATYPE<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL>, JAVA.LANG.STRING, INT)'
    privateFunction111.invoke(gInstance, String, int)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, GW.LANG.__PSI__.METATYPE<JAVA.LANG.STRING>, GW.LANG.__PSI__.METATYPE<INT>)'
    privateFunction111.invoke("Ed", 42)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(JAVA.LANG.STRING, INT)'
    privateFunction111.invoke(String, int)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.LANG.__PSI__.METATYPE<JAVA.LANG.STRING>, GW.LANG.__PSI__.METATYPE<INT>)'
    privateFunction111.invoke(gInstance, "Ed")      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING)'
    privateFunction111.invoke(gInstance, 42)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, INT)'
    //Invoking : GosuFL#gosuPrivateFun("mystring", 44)
    privateFunction112.invoke(gInstance, "Ed", 42)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)'
    privateFunction112.invoke(gInstance)
    //Invoking : GosuFL#gosuPrivateFun()
    privateFunction113.invoke(gInstance, "Ed", 42)
    privateFunction113.invoke(gInstance)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL)'

    //Invoking : GosuFL#gosuProtectedFun(String, int)
    protectedFunction111.invoke(gInstance, "Ed", 42)
    protectedFunction111.invoke(gInstance)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL)'
    protectedFunction111.invoke(GosuFL, String, int)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.LANG.__PSI__.METATYPE<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL>, GW.LANG.__PSI__.METATYPE<JAVA.LANG.STRING>, GW.LANG.__PSI__.METATYPE<INT>)'
    protectedFunction111.invoke(GosuFL, "Ed", 42)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.LANG.__PSI__.METATYPE<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL>, JAVA.LANG.STRING, INT)'
    protectedFunction111.invoke(gInstance, String, int)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, GW.LANG.__PSI__.METATYPE<JAVA.LANG.STRING>, GW.LANG.__PSI__.METATYPE<INT>)'
    protectedFunction111.invoke("Ed", 42)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(JAVA.LANG.STRING, INT)'
    protectedFunction111.invoke(String, int)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.LANG.__PSI__.METATYPE<JAVA.LANG.STRING>, GW.LANG.__PSI__.METATYPE<INT>)'
    protectedFunction111.invoke(gInstance, "Ed")      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING)'
    protectedFunction111.invoke(gInstance, 42)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, INT)'
    //Invoking : GosuFL#gosuProtectedFun("mystring", 44)
    protectedFunction112.invoke(gInstance, "Ed", 42)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)'
    protectedFunction112.invoke(gInstance)
    //Invoking : GosuFL#gosuProtectedFun()
    protectedFunction113.invoke(gInstance, "Ed", 42)
    protectedFunction113.invoke(gInstance)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL)'

    //Invoking : GosuFL#gosuPublicFun(String, int)
    publicFunction111.invoke(gInstance, "Ed", 42)
    publicFunction111.invoke(gInstance)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL)'
    publicFunction111.invoke(GosuFL, String, int)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.LANG.__PSI__.METATYPE<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL>, GW.LANG.__PSI__.METATYPE<JAVA.LANG.STRING>, GW.LANG.__PSI__.METATYPE<INT>)'
    publicFunction111.invoke(GosuFL, "Ed", 42)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.LANG.__PSI__.METATYPE<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL>, JAVA.LANG.STRING, INT)'
    publicFunction111.invoke(gInstance, String, int)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, GW.LANG.__PSI__.METATYPE<JAVA.LANG.STRING>, GW.LANG.__PSI__.METATYPE<INT>)'
    publicFunction111.invoke("Ed", 42)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(JAVA.LANG.STRING, INT)'
    publicFunction111.invoke(String, int)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.LANG.__PSI__.METATYPE<JAVA.LANG.STRING>, GW.LANG.__PSI__.METATYPE<INT>)'
    publicFunction111.invoke(gInstance, "Ed")      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING)'
    publicFunction111.invoke(gInstance, 42)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, INT)'
    //Invoking : GosuFL#gosuPublicFun("mystring", 44)
    publicFunction112.invoke(gInstance, "Ed", 42)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)'
    publicFunction112.invoke(gInstance)
    //Invoking : GosuFL#gosuPublicFun()
    publicFunction113.invoke(gInstance, "Ed", 42)
    publicFunction113.invoke(gInstance)      //## issuekeys: 'INVOKE(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL)'
  }
}