package gw.specContrib.featureLiterals.gosuMembersBinding

class Errant_BindGosuPropertiesAs {
  //binding gosu class property (one with 'as' keyword)
  var gosuProp = GosuFL#MyProp
  function getSetPropertiesFeatureLiterals () {
    var gInstance : GosuFL
    //set the values
    //correct arguments
    gosuProp.set(gInstance, "Ed")

    //incorrect arguments
    gosuProp.set(gInstance, "Ed", 42)      //## issuekeys: 'SET(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL, JAVA.LANG.STRING)' IN 'GW.LANG.REFLECT.FEATURES.PROPERTYREFERENCE' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL, JAVA.LANG.STRING, INT)'
    gosuProp.set(gInstance, 42)      //## issuekeys: 'SET(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL, JAVA.LANG.STRING)' IN 'GW.LANG.REFLECT.FEATURES.PROPERTYREFERENCE' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL, INT)'
    gosuProp.set("Ed")      //## issuekeys: 'SET(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL, JAVA.LANG.STRING)' IN 'GW.LANG.REFLECT.FEATURES.PROPERTYREFERENCE' CANNOT BE APPLIED TO '(JAVA.LANG.STRING)'
    gosuProp.set("Ed", 42)      //## issuekeys: 'SET(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL, JAVA.LANG.STRING)' IN 'GW.LANG.REFLECT.FEATURES.PROPERTYREFERENCE' CANNOT BE APPLIED TO '(JAVA.LANG.STRING, INT)'


    //get the values
    var x1111 = gosuProp.get(gInstance)
    var x1112 = gosuProp.get("hi")      //## issuekeys: 'GET(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL)' IN 'GW.LANG.REFLECT.FEATURES.PROPERTYREFERENCE' CANNOT BE APPLIED TO '(JAVA.LANG.STRING)'
    var x1113 = gosuProp.get()      //## issuekeys: 'GET(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL)' IN 'GW.LANG.REFLECT.FEATURES.PROPERTYREFERENCE' CANNOT BE APPLIED TO '()'

   }
}