package gw.specContrib.featureLiterals.gosuMembersBinding

class Errant_BindGosuProperties {
  //binding java class property
  var gosuInternalMyProp = GosuFL#MyPropInternal
  var gosuPrivateMyProp = GosuFL#MyPropPrivate
  var gosuProtectedMyProp = GosuFL#MyPropProtected
  var gosuPublicMyProp = GosuFL#MyPropPublic

  function getSetPropertiesFeatureLiterals () {
    var gInstance : GosuFL
    //set the values
    //correct arguments
    gosuInternalMyProp.set(gInstance, "Ed")
    gosuPrivateMyProp.set(gInstance, "Ed")
    gosuProtectedMyProp.set(gInstance, "Ed")
    gosuPublicMyProp.set(gInstance, "Ed")

    //incorrect arguments
    gosuInternalMyProp.set(gInstance, "Ed", 42)      //## issuekeys: 'SET(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL, JAVA.LANG.STRING)' IN 'GW.LANG.REFLECT.FEATURES.PROPERTYREFERENCE' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL, JAVA.LANG.STRING, INT)'
    gosuInternalMyProp.set(gInstance, 42)      //## issuekeys: 'SET(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL, JAVA.LANG.STRING)' IN 'GW.LANG.REFLECT.FEATURES.PROPERTYREFERENCE' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL, INT)'
    gosuInternalMyProp.set("Ed")      //## issuekeys: 'SET(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL, JAVA.LANG.STRING)' IN 'GW.LANG.REFLECT.FEATURES.PROPERTYREFERENCE' CANNOT BE APPLIED TO '(JAVA.LANG.STRING)'
    gosuInternalMyProp.set("Ed", 42)      //## issuekeys: 'SET(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL, JAVA.LANG.STRING)' IN 'GW.LANG.REFLECT.FEATURES.PROPERTYREFERENCE' CANNOT BE APPLIED TO '(JAVA.LANG.STRING, INT)'

    gosuPrivateMyProp.set(gInstance, "Ed", 42)      //## issuekeys: 'SET(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL, JAVA.LANG.STRING)' IN 'GW.LANG.REFLECT.FEATURES.PROPERTYREFERENCE' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL, JAVA.LANG.STRING, INT)'
    gosuPrivateMyProp.set(gInstance, 42)      //## issuekeys: 'SET(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL, JAVA.LANG.STRING)' IN 'GW.LANG.REFLECT.FEATURES.PROPERTYREFERENCE' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL, INT)'
    gosuPrivateMyProp.set("Ed")      //## issuekeys: 'SET(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL, JAVA.LANG.STRING)' IN 'GW.LANG.REFLECT.FEATURES.PROPERTYREFERENCE' CANNOT BE APPLIED TO '(JAVA.LANG.STRING)'
    gosuPrivateMyProp.set("Ed", 42)      //## issuekeys: 'SET(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL, JAVA.LANG.STRING)' IN 'GW.LANG.REFLECT.FEATURES.PROPERTYREFERENCE' CANNOT BE APPLIED TO '(JAVA.LANG.STRING, INT)'

    gosuProtectedMyProp.set(gInstance, "Ed", 42)      //## issuekeys: 'SET(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL, JAVA.LANG.STRING)' IN 'GW.LANG.REFLECT.FEATURES.PROPERTYREFERENCE' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL, JAVA.LANG.STRING, INT)'
    gosuProtectedMyProp.set(gInstance, 42)      //## issuekeys: 'SET(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL, JAVA.LANG.STRING)' IN 'GW.LANG.REFLECT.FEATURES.PROPERTYREFERENCE' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL, INT)'
    gosuProtectedMyProp.set("Ed")      //## issuekeys: 'SET(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL, JAVA.LANG.STRING)' IN 'GW.LANG.REFLECT.FEATURES.PROPERTYREFERENCE' CANNOT BE APPLIED TO '(JAVA.LANG.STRING)'
    gosuProtectedMyProp.set("Ed", 42)      //## issuekeys: 'SET(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL, JAVA.LANG.STRING)' IN 'GW.LANG.REFLECT.FEATURES.PROPERTYREFERENCE' CANNOT BE APPLIED TO '(JAVA.LANG.STRING, INT)'

    gosuPublicMyProp.set(gInstance, "Ed", 42)      //## issuekeys: 'SET(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL, JAVA.LANG.STRING)' IN 'GW.LANG.REFLECT.FEATURES.PROPERTYREFERENCE' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL, JAVA.LANG.STRING, INT)'
    gosuPublicMyProp.set(gInstance, 42)      //## issuekeys: 'SET(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL, JAVA.LANG.STRING)' IN 'GW.LANG.REFLECT.FEATURES.PROPERTYREFERENCE' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL, INT)'
    gosuPublicMyProp.set("Ed")      //## issuekeys: 'SET(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL, JAVA.LANG.STRING)' IN 'GW.LANG.REFLECT.FEATURES.PROPERTYREFERENCE' CANNOT BE APPLIED TO '(JAVA.LANG.STRING)'
    gosuPublicMyProp.set("Ed", 42)      //## issuekeys: 'SET(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL, JAVA.LANG.STRING)' IN 'GW.LANG.REFLECT.FEATURES.PROPERTYREFERENCE' CANNOT BE APPLIED TO '(JAVA.LANG.STRING, INT)'

    //get the values
    var x1111 = gosuInternalMyProp.get(gInstance)
    var x1112 = gosuInternalMyProp.get("hi")      //## issuekeys: 'GET(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL)' IN 'GW.LANG.REFLECT.FEATURES.PROPERTYREFERENCE' CANNOT BE APPLIED TO '(JAVA.LANG.STRING)'
    var x1113 = gosuInternalMyProp.get()      //## issuekeys: 'GET(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL)' IN 'GW.LANG.REFLECT.FEATURES.PROPERTYREFERENCE' CANNOT BE APPLIED TO '()'

    var x1121 = gosuPrivateMyProp.get(gInstance)
    var x1122 = gosuPrivateMyProp.get("hi")      //## issuekeys: 'GET(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL)' IN 'GW.LANG.REFLECT.FEATURES.PROPERTYREFERENCE' CANNOT BE APPLIED TO '(JAVA.LANG.STRING)'
    var x1123 = gosuPrivateMyProp.get()      //## issuekeys: 'GET(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL)' IN 'GW.LANG.REFLECT.FEATURES.PROPERTYREFERENCE' CANNOT BE APPLIED TO '()'

    var x1131 = gosuProtectedMyProp.get(gInstance)
    var x1132 = gosuProtectedMyProp.get("hi")      //## issuekeys: 'GET(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL)' IN 'GW.LANG.REFLECT.FEATURES.PROPERTYREFERENCE' CANNOT BE APPLIED TO '(JAVA.LANG.STRING)'
    var x1133 = gosuProtectedMyProp.get()      //## issuekeys: 'GET(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL)' IN 'GW.LANG.REFLECT.FEATURES.PROPERTYREFERENCE' CANNOT BE APPLIED TO '()'

    var x1141 = gosuPublicMyProp.get(gInstance)
    var x1142 = gosuPublicMyProp.get("hi")      //## issuekeys: 'GET(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL)' IN 'GW.LANG.REFLECT.FEATURES.PROPERTYREFERENCE' CANNOT BE APPLIED TO '(JAVA.LANG.STRING)'
    var x1143 = gosuPublicMyProp.get()      //## issuekeys: 'GET(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.GosuFL)' IN 'GW.LANG.REFLECT.FEATURES.PROPERTYREFERENCE' CANNOT BE APPLIED TO '()'
  }
}