package gw.specContrib.featureLiterals.gosuMembersBinding

class Errant_BindGosuPropertiesAsToInstance {
  var jack : GosuFL
  //binding java class property to instance
  var gosuMyProp = jack#MyProp

  function getSetPropertiesFeatureLiterals () {
    var gInstance : GosuFL
    //set the values
    //correct arguments
    gosuMyProp.set("Ed")

    //incorrect arguments
    gosuMyProp.set(gInstance,"Ed")      //## issuekeys: 'SET(JAVA.LANG.STRING)' IN 'GW.LANG.REFLECT.FEATURES.BOUNDPROPERTYREFERENCE' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.JAVACLASS, JAVA.LANG.STRING)'
    gosuMyProp.set(gInstance, "Ed", 42)      //## issuekeys: 'SET(JAVA.LANG.STRING)' IN 'GW.LANG.REFLECT.FEATURES.BOUNDPROPERTYREFERENCE' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.JAVACLASS, JAVA.LANG.STRING, INT)'
    gosuMyProp.set(gInstance, 42)      //## issuekeys: 'SET(JAVA.LANG.STRING)' IN 'GW.LANG.REFLECT.FEATURES.BOUNDPROPERTYREFERENCE' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.JAVACLASS, INT)'
    gosuMyProp.set("Ed", 42)      //## issuekeys: 'SET(JAVA.LANG.STRING)' IN 'GW.LANG.REFLECT.FEATURES.BOUNDPROPERTYREFERENCE' CANNOT BE APPLIED TO '(JAVA.LANG.STRING, INT)'


    //get the values
    var x1111 = gosuMyProp.get()
    var x1112 = gosuMyProp.get(gInstance)      //## issuekeys: 'GET()' IN 'GW.LANG.REFLECT.FEATURES.BOUNDPROPERTYREFERENCE' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.JAVAFEATURELITERALS.JAVACLASS)'
    var x1113 = gosuMyProp.get("hi")      //## issuekeys: 'GET()' IN 'GW.LANG.REFLECT.FEATURES.BOUNDPROPERTYREFERENCE' CANNOT BE APPLIED TO '(JAVA.LANG.STRING)'


  }
}