package gw.specContrib.featureLiterals.gosuMembersBinding

class Errant_BindGosuMethodsToInstance {
  var jack : GosuFL

  //methods
  //IDE-1375
  var internalFunction111 = jack#gosuInternalFun(String,  int)
  var internalFunction112 = jack#gosuInternalFun("mystring", 44)
  var internalFunction113 = jack#gosuInternalFun()
  var internalFunction114 = jack#gosuInternalFun(GosuFL)      //## issuekeys: CANNOT RESOLVE METHOD 'GOSUINTERNALFUN(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL)'
  var internalFunction115 = jack#gosuInternalFun(GosuFL, String, int)      //## issuekeys: CANNOT RESOLVE METHOD 'GOSUINTERNALFUN(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)'
  var internalFunction116 = jack#gosuInternalFun(jack, "mystring", 42)      //## issuekeys: 'GOSUINTERNALFUN(JAVA.LANG.STRING, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)'
  var internalFunction117 = jack#gosuInternalFun(int, String)      //## issuekeys: CANNOT RESOLVE METHOD 'GOSUINTERNALFUN(INT, JAVA.LANG.STRING)'
  var internalFunction118 = jack#gosuInternalFun(42, "mystring")      //## issuekeys: 'GOSUINTERNALFUN(JAVA.LANG.STRING, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL' CANNOT BE APPLIED TO '(INT, JAVA.LANG.STRING)'
  var internalFunction119 = jack#gosuInternalFun      //## issuekeys: CANNOT RESOLVE SYMBOL 'GOSUINTERNALFUN'

  var privateFunction111 = jack#gosuPrivateFun(String, int)
  var privateFunction112 = jack#gosuPrivateFun("mystring", 44)
  var privateFunction113 = jack#gosuPrivateFun()
  var privateFunction114 = jack#gosuPrivateFun(GosuFL)      //## issuekeys: CANNOT RESOLVE METHOD 'GOSUPRIVATEFUN(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL)'
  var privateFunction115 = jack#gosuPrivateFun(GosuFL, String, int)      //## issuekeys: CANNOT RESOLVE METHOD 'GOSUPRIVATEFUN(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)'
  var privateFunction116 = jack#gosuPrivateFun(jack, "mystring", 42)      //## issuekeys: 'GOSUPRIVATEFUN(JAVA.LANG.STRING, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)'
  var privateFunction117 = jack#gosuPrivateFun(int, String)      //## issuekeys: CANNOT RESOLVE METHOD 'GOSUPRIVATEFUN(INT, JAVA.LANG.STRING)'
  var privateFunction118 = jack#gosuPrivateFun(42, "mystring")      //## issuekeys: 'GOSUPRIVATEFUN(JAVA.LANG.STRING, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL' CANNOT BE APPLIED TO '(INT, JAVA.LANG.STRING)'
  var privateFunction119 = jack#gosuPrivateFun      //## issuekeys: CANNOT RESOLVE SYMBOL 'GOSUPRIVATEFUN'

  var protectedFunction111 = jack#gosuProtectedFun(String, int)
  var protectedFunction112 = jack#gosuProtectedFun("mystring", 44)
  var protectedFunction113 = jack#gosuProtectedFun()
  var protectedFunction114 = jack#gosuProtectedFun(GosuFL)      //## issuekeys: CANNOT RESOLVE METHOD 'GOSUPROTECTEDFUN(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL)'
  var protectedFunction115 = jack#gosuProtectedFun(GosuFL, String, int)      //## issuekeys: CANNOT RESOLVE METHOD 'GOSUPROTECTEDFUN(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)'
  var protectedFunction116 = jack#gosuProtectedFun(jack, "mystring", 42)      //## issuekeys: 'GOSUPROTECTEDFUN(JAVA.LANG.STRING, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)'
  var protectedFunction117 = jack#gosuProtectedFun(int, String)      //## issuekeys: CANNOT RESOLVE METHOD 'GOSUPROTECTEDFUN(INT, JAVA.LANG.STRING)'
  var protectedFunction118 = jack#gosuProtectedFun(42, "mystring")      //## issuekeys: 'GOSUPROTECTEDFUN(JAVA.LANG.STRING, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL' CANNOT BE APPLIED TO '(INT, JAVA.LANG.STRING)'
  var protectedFunction119 = jack#gosuProtectedFun      //## issuekeys: CANNOT RESOLVE SYMBOL 'GOSUPROTECTEDFUN'


  var publicFunction111 = jack#gosuPublicFun(String, int)
  var publicFunction112 = jack#gosuPublicFun("mystring", 44)
  var publicFunction113 = jack#gosuPublicFun()
  var publicFunction114 = jack#gosuPublicFun(GosuFL)      //## issuekeys: CANNOT RESOLVE METHOD 'GOSUPUBLICFUN(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL)'
  var publicFunction115 = jack#gosuPublicFun(GosuFL, String, int)      //## issuekeys: CANNOT RESOLVE METHOD 'GOSUPUBLICFUN(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)'
  var publicFunction116 = jack#gosuPublicFun(jack, "mystring", 42)      //## issuekeys: 'GOSUPUBLICFUN(JAVA.LANG.STRING, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)'
  var publicFunction117 = jack#gosuPublicFun(int, String)      //## issuekeys: CANNOT RESOLVE METHOD 'GOSUPUBLICFUN(INT, JAVA.LANG.STRING)'
  var publicFunction118 = jack#gosuPublicFun(42, "mystring")      //## issuekeys: 'GOSUPUBLICFUN(JAVA.LANG.STRING, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL' CANNOT BE APPLIED TO '(INT, JAVA.LANG.STRING)'
  var publicFunction119 = jack#gosuPublicFun      //## issuekeys: CANNOT RESOLVE SYMBOL 'GOSUPUBLICFUN'


  function invokeGosuFunctions() {
    var gInstance : GosuFL

    //Invoking : GosuFL#gosuInternalFun(String, int)
    internalFunction111.invoke("Ed", 42)
    internalFunction111.invoke(gInstance, "Ed", 42)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)'
    internalFunction111.invoke(gInstance)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL)'
    internalFunction111.invoke(GosuFL, String, int)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.LANG.__PSI__.METATYPE<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL>, GW.LANG.__PSI__.METATYPE<JAVA.LANG.STRING>, GW.LANG.__PSI__.METATYPE<INT>)'
    internalFunction111.invoke(GosuFL, "Ed", 42)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.LANG.__PSI__.METATYPE<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL>, JAVA.LANG.STRING, INT)'
    internalFunction111.invoke(gInstance, String, int)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, GW.LANG.__PSI__.METATYPE<JAVA.LANG.STRING>, GW.LANG.__PSI__.METATYPE<INT>)'
    internalFunction111.invoke(String, int)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.LANG.__PSI__.METATYPE<JAVA.LANG.STRING>, GW.LANG.__PSI__.METATYPE<INT>)'
    internalFunction111.invoke(gInstance, "Ed")      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING)'
    internalFunction111.invoke(gInstance, 42)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, INT)'
    //Invoking : jack#gosuInternalFun("mystring", 44)
    internalFunction112.invoke()
    internalFunction112.invoke("Ed", 42)      //## issuekeys: 'INVOKE()' IN '' CANNOT BE APPLIED TO '(JAVA.LANG.STRING, INT)'
    internalFunction112.invoke(gInstance, "Ed", 42)      //## issuekeys: 'INVOKE()' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)'
    internalFunction112.invoke(gInstance)      //## issuekeys: 'INVOKE()' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL)'
    //Invoking : jack#gosuInternalFun()
    internalFunction113.invoke()      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '()'
    internalFunction113.invoke("Ed", 42)
    internalFunction113.invoke(gInstance, "Ed", 42)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)'
    internalFunction113.invoke(gInstance)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL)'




    //Invoking : GosuFL#gosuPrivateFun(String, int)
    privateFunction111.invoke("Ed", 42)
    privateFunction111.invoke(gInstance, "Ed", 42)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)'
    privateFunction111.invoke(gInstance)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL)'
    privateFunction111.invoke(GosuFL, String, int)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.LANG.__PSI__.METATYPE<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL>, GW.LANG.__PSI__.METATYPE<JAVA.LANG.STRING>, GW.LANG.__PSI__.METATYPE<INT>)'
    privateFunction111.invoke(GosuFL, "Ed", 42)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.LANG.__PSI__.METATYPE<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL>, JAVA.LANG.STRING, INT)'
    privateFunction111.invoke(gInstance, String, int)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, GW.LANG.__PSI__.METATYPE<JAVA.LANG.STRING>, GW.LANG.__PSI__.METATYPE<INT>)'
    privateFunction111.invoke(String, int)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.LANG.__PSI__.METATYPE<JAVA.LANG.STRING>, GW.LANG.__PSI__.METATYPE<INT>)'
    privateFunction111.invoke(gInstance, "Ed")      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING)'
    privateFunction111.invoke(gInstance, 42)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, INT)'
    //Invoking : jack#gosuPrivateFun("mystring", 44)
    privateFunction112.invoke()
    privateFunction112.invoke("Ed", 42)      //## issuekeys: 'INVOKE()' IN '' CANNOT BE APPLIED TO '(JAVA.LANG.STRING, INT)'
    privateFunction112.invoke(gInstance, "Ed", 42)      //## issuekeys: 'INVOKE()' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)'
    privateFunction112.invoke(gInstance)      //## issuekeys: 'INVOKE()' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL)'
    //Invoking : jack#gosuPrivateFun()
    privateFunction113.invoke()      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '()'
    privateFunction113.invoke("Ed", 42)
    privateFunction113.invoke(gInstance, "Ed", 42)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)'
    privateFunction113.invoke(gInstance)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL)'

    //Invoking : GosuFL#gosuProtectedFun(String, int)
    protectedFunction111.invoke("Ed", 42)
    protectedFunction111.invoke(gInstance, "Ed", 42)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)'
    protectedFunction111.invoke(gInstance)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL)'
    protectedFunction111.invoke(GosuFL, String, int)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.LANG.__PSI__.METATYPE<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL>, GW.LANG.__PSI__.METATYPE<JAVA.LANG.STRING>, GW.LANG.__PSI__.METATYPE<INT>)'
    protectedFunction111.invoke(GosuFL, "Ed", 42)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.LANG.__PSI__.METATYPE<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL>, JAVA.LANG.STRING, INT)'
    protectedFunction111.invoke(gInstance, String, int)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, GW.LANG.__PSI__.METATYPE<JAVA.LANG.STRING>, GW.LANG.__PSI__.METATYPE<INT>)'
    protectedFunction111.invoke(String, int)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.LANG.__PSI__.METATYPE<JAVA.LANG.STRING>, GW.LANG.__PSI__.METATYPE<INT>)'
    protectedFunction111.invoke(gInstance, "Ed")      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING)'
    protectedFunction111.invoke(gInstance, 42)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, INT)'
    //Invoking : jack#gosuProtectedFun("mystring", 44)
    protectedFunction112.invoke()
    protectedFunction112.invoke("Ed", 42)      //## issuekeys: 'INVOKE()' IN '' CANNOT BE APPLIED TO '(JAVA.LANG.STRING, INT)'
    protectedFunction112.invoke(gInstance, "Ed", 42)      //## issuekeys: 'INVOKE()' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)'
    protectedFunction112.invoke(gInstance)      //## issuekeys: 'INVOKE()' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL)'
    //Invoking : jack#gosuProtectedFun()
    protectedFunction113.invoke()      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '()'
    protectedFunction113.invoke("Ed", 42)
    protectedFunction113.invoke(gInstance, "Ed", 42)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)'
    protectedFunction113.invoke(gInstance)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL)'

    //Invoking : GosuFL#gosuPublicFun(String, int)
    publicFunction111.invoke("Ed", 42)
    publicFunction111.invoke(gInstance, "Ed", 42)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)'
    publicFunction111.invoke(gInstance)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL)'
    publicFunction111.invoke(GosuFL, String, int)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.LANG.__PSI__.METATYPE<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL>, GW.LANG.__PSI__.METATYPE<JAVA.LANG.STRING>, GW.LANG.__PSI__.METATYPE<INT>)'
    publicFunction111.invoke(GosuFL, "Ed", 42)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.LANG.__PSI__.METATYPE<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL>, JAVA.LANG.STRING, INT)'
    publicFunction111.invoke(gInstance, String, int)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, GW.LANG.__PSI__.METATYPE<JAVA.LANG.STRING>, GW.LANG.__PSI__.METATYPE<INT>)'
    publicFunction111.invoke(String, int)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.LANG.__PSI__.METATYPE<JAVA.LANG.STRING>, GW.LANG.__PSI__.METATYPE<INT>)'
    publicFunction111.invoke(gInstance, "Ed")      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING)'
    publicFunction111.invoke(gInstance, 42)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, INT)'
    //Invoking : jack#gosuPublicFun("mystring", 44)
    publicFunction112.invoke()
    publicFunction112.invoke("Ed", 42)      //## issuekeys: 'INVOKE()' IN '' CANNOT BE APPLIED TO '(JAVA.LANG.STRING, INT)'
    publicFunction112.invoke(gInstance, "Ed", 42)      //## issuekeys: 'INVOKE()' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)'
    publicFunction112.invoke(gInstance)      //## issuekeys: 'INVOKE()' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL)'
    //Invoking : jack#gosuPublicFun()
    publicFunction113.invoke()      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '()'
    publicFunction113.invoke("Ed", 42)
    publicFunction113.invoke(gInstance, "Ed", 42)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL, JAVA.LANG.STRING, INT)'
    publicFunction113.invoke(gInstance)      //## issuekeys: 'INVOKE(JAVA.LANG.STRING, INT)' IN '' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.FEATURELITERALS.FEATURELITERALSMAIN.GOSUFEATURELITERALS.GOSUFL)'
  }
}