package gw.specContrib.classes.method_Scoring.primitive_Types

class Errant_IntFloatDoubleMethods {
  class A {
  }

  class B {
  }

  class C {
  }


  function funIntFloatDouble(i: int, j: int): A {
    return null
  }

  function funIntFloatDouble(i: float, j: float): B {
    return null
  }

  function funIntFloatDouble(i: double, j: double): C {
    return null
  }


  var d1: double = 42.5
  var d2: double = 43.5

  function caller() {
    //char
    //IDE-1391 (char, char) case
    var primTypeC1111: A = funIntFloatDouble('c', 'c')
    var primTypeC1112: A = funIntFloatDouble('c', 1b)
    var primTypeC1113: A = funIntFloatDouble('c', 1s)
    var primTypeC1114: A = funIntFloatDouble('c', 42)
    var primTypeC1115: A = funIntFloatDouble('c', 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'
    var primTypeC1116: A = funIntFloatDouble('c', 100L)      //## issuekeys: AMBIGUOUS METHOD CALL: BOTH 'ERRANT_INTFLOATDOUBLEMETHODS.FUNINTFLOATDOUBLE(FLOAT, FLOAT)' AND 'ERRANT_INTFLOATDOUBLEMETHODS.FUNINTFLOATDOUBLE(DOUBLE, DOUBLE)' MATCH
    var primTypeC1117: A = funIntFloatDouble('c', 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'
    var primTypeC1118: A = funIntFloatDouble('c', d1)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'

    var primTypeC2111: B = funIntFloatDouble('c', 'c')      //## issuekeys: AMBIGUOUS METHOD CALL: BOTH 'ERRANT_INTFLOATDOUBLEMETHODS.FUNINTFLOATDOUBLE(INT, INT)' AND 'ERRANT_INTFLOATDOUBLEMETHODS.FUNINTFLOATDOUBLE(FLOAT, FLOAT)' MATCH
    var primTypeC2112: B = funIntFloatDouble('c', 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'
    var primTypeC2113: B = funIntFloatDouble('c', 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'
    var primTypeC2114: B = funIntFloatDouble('c', 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'
    var primTypeC2115: B = funIntFloatDouble('c', 42.5f)
    // IDE-474 Goes to (float, float) as Java does
    var primTypeC2116: B = funIntFloatDouble('c', 100L)
    var primTypeC2117: B = funIntFloatDouble('c', 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'
    var primTypeC2118: B = funIntFloatDouble('c', d1)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'

    var primTypeC3111: C = funIntFloatDouble('c', 'c')      //## issuekeys: AMBIGUOUS METHOD CALL: BOTH 'ERRANT_INTFLOATDOUBLEMETHODS.FUNINTFLOATDOUBLE(INT, INT)' AND 'ERRANT_INTFLOATDOUBLEMETHODS.FUNINTFLOATDOUBLE(FLOAT, FLOAT)' MATCH
    var primTypeC3112: C = funIntFloatDouble('c', 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C'
    var primTypeC3113: C = funIntFloatDouble('c', 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C'
    var primTypeC3114: C = funIntFloatDouble('c', 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C'
    var primTypeC3115: C = funIntFloatDouble('c', 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C'
    //IDE-1436 - Goes to (float, float) as Java does (see also IDE-474)
    var primTypeC3116: C = funIntFloatDouble('c', 100L)   //## issuekeys: INCOMPATIBLE TYPES
    var primTypeC3117: C = funIntFloatDouble('c', 42.5)
    var primTypeC3118: C = funIntFloatDouble('c', d1)

    var primTypeC4111 = funIntFloatDouble('c', 'c')
    var primTypeC4112 = funIntFloatDouble('c', 1b)
    var primTypeC4113 = funIntFloatDouble('c', 1s)
    var primTypeC4114 = funIntFloatDouble('c', 42)
    var primTypeC4115 = funIntFloatDouble('c', 42.5f)
    var primTypeC4116 = funIntFloatDouble('c', 100L)
    var primTypeC4117 = funIntFloatDouble('c', 42.5)
    var primTypeC4118 = funIntFloatDouble('c', d1)

    //byte
    var primTypeB1111: A = funIntFloatDouble(1b, 'c')
    var primTypeB1112: A = funIntFloatDouble(1b, 1b)
    var primTypeB1113: A = funIntFloatDouble(1b, 1s)
    var primTypeB1114: A = funIntFloatDouble(1b, 42)
    var primTypeB1115: A = funIntFloatDouble(1b, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'
    // IDE-474 Goes to (float, float) as Java does
    var primTypeB1116: A = funIntFloatDouble(1b, 100L)      //## issuekeys: INCOMPATIBLE TYPES
    var primTypeB1117: A = funIntFloatDouble(1b, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'
    var primTypeB1118: A = funIntFloatDouble(1b, d1)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'

    var primTypeB2111: B = funIntFloatDouble(1b, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'
    var primTypeB2112: B = funIntFloatDouble(1b, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'
    var primTypeB2113: B = funIntFloatDouble(1b, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'
    var primTypeB2114: B = funIntFloatDouble(1b, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'
    var primTypeB2115: B = funIntFloatDouble(1b, 42.5f)
    // IDE-474 Goes to (float, float) as Java does
    var primTypeB2116: B = funIntFloatDouble(1b, 100L)
    var primTypeB2117: B = funIntFloatDouble(1b, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'
    var primTypeB2118: B = funIntFloatDouble(1b, d1)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'

    var primTypeB3111: C = funIntFloatDouble(1b, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C'
    var primTypeB3112: C = funIntFloatDouble(1b, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C'
    var primTypeB3113: C = funIntFloatDouble(1b, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C'
    var primTypeB3114: C = funIntFloatDouble(1b, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C'
    var primTypeB3115: C = funIntFloatDouble(1b, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C'
    // IDE-474 Goes to (float, float) as Java does
    var primTypeB3116: C = funIntFloatDouble(1b, 100L)    //## issuekeys: INCOMPATIBLE TYPES
    var primTypeB3117: C = funIntFloatDouble(1b, 42.5)
    var primTypeB3118: C = funIntFloatDouble(1b, d1)

    var primTypeB4111 = funIntFloatDouble(1b, 'c')
    var primTypeB4112 = funIntFloatDouble(1b, 1b)
    var primTypeB4113 = funIntFloatDouble(1b, 1s)
    var primTypeB4114 = funIntFloatDouble(1b, 42)
    var primTypeB4115 = funIntFloatDouble(1b, 42.5f)
    //IDE-1436 - Goes to (float, float) as Java does (see also IDE-474)
    var primTypeB4116 = funIntFloatDouble(1b, 100L)
    var primTypeB4117 = funIntFloatDouble(1b, 42.5)
    var primTypeB4118 = funIntFloatDouble(1b, d1)

    //Short
    var primTypeS1111: A = funIntFloatDouble(1s, 'c')
    var primTypeS1112: A = funIntFloatDouble(1s, 1b)
    var primTypeS1113: A = funIntFloatDouble(1s, 1s)
    var primTypeS1114: A = funIntFloatDouble(1s, 42)
    var primTypeS1115: A = funIntFloatDouble(1s, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'
    // IDE-474 Goes to (float, float) as Java does
    var primTypeS1116: A = funIntFloatDouble(1s, 100L)      //## issuekeys: INCOMPATIBLE TYPES
    var primTypeS1117: A = funIntFloatDouble(1s, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'
    var primTypeS1118: A = funIntFloatDouble(1s, d1)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'

    var primTypeS2111: B = funIntFloatDouble(1s, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'
    var primTypeS2112: B = funIntFloatDouble(1s, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'
    var primTypeS2113: B = funIntFloatDouble(1s, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'
    var primTypeS2114: B = funIntFloatDouble(1s, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'
    var primTypeS2115: B = funIntFloatDouble(1s, 42.5f)
    // IDE-474 Goes to (float, float) as Java does
    var primTypeS2116: B = funIntFloatDouble(1s, 100L)
    var primTypeS2117: B = funIntFloatDouble(1s, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'
    var primTypeS2118: B = funIntFloatDouble(1s, d1)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'

    var primTypeS3111: C = funIntFloatDouble(1s, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C'
    var primTypeS3112: C = funIntFloatDouble(1s, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C'
    var primTypeS3113: C = funIntFloatDouble(1s, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C'
    var primTypeS3114: C = funIntFloatDouble(1s, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C'
    var primTypeS3115: C = funIntFloatDouble(1s, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C'
    // IDE-474 Goes to (float, float) as Java does
    var primTypeS3116: C = funIntFloatDouble(1s, 100L)   //## issuekeys: INCOMPATIBLE TYPES
    var primTypeS3117: C = funIntFloatDouble(1s, 42.5)
    var primTypeS3118: C = funIntFloatDouble(1s, d1)

    var primTypeS4111 = funIntFloatDouble(1s, 'c')
    var primTypeS4112 = funIntFloatDouble(1s, 1b)
    var primTypeS4113 = funIntFloatDouble(1s, 1s)
    var primTypeS4114 = funIntFloatDouble(1s, 42)
    var primTypeS4115 = funIntFloatDouble(1s, 42.5f)
    var primTypeS4116 = funIntFloatDouble(1s, 100L)
    var primTypeS4117 = funIntFloatDouble(1s, 42.5)
    var primTypeS4118 = funIntFloatDouble(1s, d1)

    //Integer
    var primTypeI1111: A = funIntFloatDouble(42, 'c')
    var primTypeI1112: A = funIntFloatDouble(42, 1b)
    var primTypeI1113: A = funIntFloatDouble(42, 1s)
    var primTypeI1114: A = funIntFloatDouble(42, 42)
    var primTypeI1115: A = funIntFloatDouble(42, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'
    var primTypeI1116: A = funIntFloatDouble(42, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'
    var primTypeI1117: A = funIntFloatDouble(42, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'
    var primTypeI1118: A = funIntFloatDouble(42, d1)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'

    var primTypeI2111: B = funIntFloatDouble(42, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'
    var primTypeI2112: B = funIntFloatDouble(42, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'
    var primTypeI2113: B = funIntFloatDouble(42, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'
    var primTypeI2114: B = funIntFloatDouble(42, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'
    //IDE-820 Fixed in OS Gosu. Pending in Parser
    var primTypeI2115: B = funIntFloatDouble(42, 42.5f)
    // IDE-474 Goes to (float, float) as Java does
    var primTypeI2116: B = funIntFloatDouble(42, 100L)
    var primTypeI2117: B = funIntFloatDouble(42, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'
    var primTypeI2118: B = funIntFloatDouble(42, d1)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'

    var primTypeI3111: C = funIntFloatDouble(42, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C'
    var primTypeI3112: C = funIntFloatDouble(42, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C'
    var primTypeI3113: C = funIntFloatDouble(42, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C'
    var primTypeI3114: C = funIntFloatDouble(42, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C'
    //IDE-820 Fixed in OS Gosu. Pending in Parser
    var primTypeI3115: C = funIntFloatDouble(42, 42.5f)   //## issuekeys: INCOMPATIBLE TYPES. FOUND:
    // IDE-474 Goes to (float, float) as Java does
    var primTypeI3116: C = funIntFloatDouble(42, 100L)    //## issuekeys: INCOMPATIBLE TYPES
    var primTypeI3117: C = funIntFloatDouble(42, 42.5)
    var primTypeI3118: C = funIntFloatDouble(42, d1)

    var primTypeI4111 = funIntFloatDouble(42, 'c')
    var primTypeI4112 = funIntFloatDouble(42, 1b)
    var primTypeI4113 = funIntFloatDouble(42, 1s)
    var primTypeI4114 = funIntFloatDouble(42, 42)
    var primTypeI4115 = funIntFloatDouble(42, 42.5f)
    var primTypeI4116 = funIntFloatDouble(42, 100L)
    var primTypeI4117 = funIntFloatDouble(42, 42.5)
    var primTypeI4118 = funIntFloatDouble(42, d1)

    //Float
    var primTypeF1111: A = funIntFloatDouble(42.5f, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'
    var primTypeF1112: A = funIntFloatDouble(42.5f, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'
    var primTypeF1113: A = funIntFloatDouble(42.5f, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'
    var primTypeF1114: A = funIntFloatDouble(42.5f, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'
    var primTypeF1115: A = funIntFloatDouble(42.5f, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'
    var primTypeF1116: A = funIntFloatDouble(42.5f, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'
    var primTypeF1117: A = funIntFloatDouble(42.5f, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'
    var primTypeF1118: A = funIntFloatDouble(42.5f, d1)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'

    var primTypeF2111: B = funIntFloatDouble(42.5f, 'c')
    var primTypeF2112: B = funIntFloatDouble(42.5f, 1b)
    var primTypeF2113: B = funIntFloatDouble(42.5f, 1s)
    //IDE-820 Fixed in OS Gosu. Pending in Parser
    var primTypeF2114: B = funIntFloatDouble(42.5f, 42)
    var primTypeF2115: B = funIntFloatDouble(42.5f, 42.5f)
    // IDE-474 Goes to (float, float) as Java does
    var primTypeF2116: B = funIntFloatDouble(42.5f, 100L)
    var primTypeF2117: B = funIntFloatDouble(42.5f, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'
    var primTypeF2118: B = funIntFloatDouble(42.5f, d1)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'

    var primTypeF3111: C = funIntFloatDouble(42.5f, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C'
    var primTypeF3112: C = funIntFloatDouble(42.5f, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C'
    var primTypeF3113: C = funIntFloatDouble(42.5f, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C'
    //IDE-820
    var primTypeF3114: C = funIntFloatDouble(42.5f, 42)      //## issuekeys: INCOMPATIBLE TYPES.
    var primTypeF3115: C = funIntFloatDouble(42.5f, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C'
    // IDE-474 Goes to (float, float) as Java does
    var primTypeF3116: C = funIntFloatDouble(42.5f, 100L)    //## issuekeys: INCOMPATIBLE TYPES
    var primTypeF3117: C = funIntFloatDouble(42.5f, 42.5)
    var primTypeF3118: C = funIntFloatDouble(42.5f, d1)

    var primTypeF4111 = funIntFloatDouble(42.5f, 'c')
    var primTypeF4112 = funIntFloatDouble(42.5f, 1b)
    var primTypeF4113 = funIntFloatDouble(42.5f, 1s)
    var primTypeF4114 = funIntFloatDouble(42.5f, 42)
    var primTypeF4115 = funIntFloatDouble(42.5f, 42.5f)
    var primTypeF4116 = funIntFloatDouble(42.5f, 100L)
    var primTypeF4117 = funIntFloatDouble(42.5f, 42.5)
    var primTypeF4118 = funIntFloatDouble(42.5f, d1)

    //Long
    // IDE-474 Goes to (float, float) as Java does
    var primTypeL1111: A = funIntFloatDouble(100L, 'c')      //## issuekeys: INCOMPATIBLE TYPES
    var primTypeL1112: A = funIntFloatDouble(100L, 1b)      //## issuekeys: INCOMPATIBLE TYPES
    var primTypeL1113: A = funIntFloatDouble(100L, 1s)      //## issuekeys: INCOMPATIBLE TYPES
    var primTypeL1114: A = funIntFloatDouble(100L, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'
    var primTypeL1115: A = funIntFloatDouble(100L, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'
    var primTypeL1116: A = funIntFloatDouble(100L, 100L)      //## issuekeys: INCOMPATIBLE TYPES
    var primTypeL1117: A = funIntFloatDouble(100L, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'
    var primTypeL1118: A = funIntFloatDouble(100L, d1)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'

    var primTypeL2111: B = funIntFloatDouble(100L, 'c')
    var primTypeL2112: B = funIntFloatDouble(100L, 1b)
    var primTypeL2113: B = funIntFloatDouble(100L, 1s)
    var primTypeL2114: B = funIntFloatDouble(100L, 42)
    var primTypeL2115: B = funIntFloatDouble(100L, 42.5f)
    var primTypeL2116: B = funIntFloatDouble(100L, 100L)
    var primTypeL2117: B = funIntFloatDouble(100L, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'
    var primTypeL2118: B = funIntFloatDouble(100L, d1)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'

    var primTypeL3111: C = funIntFloatDouble(100L, 'c')      //## issuekeys: INCOMPATIBLE TYPES
    var primTypeL3112: C = funIntFloatDouble(100L, 1b)      //## issuekeys: INCOMPATIBLE TYPES
    var primTypeL3113: C = funIntFloatDouble(100L, 1s)      //## issuekeys: INCOMPATIBLE TYPES
    var primTypeL3114: C = funIntFloatDouble(100L, 42)      //## issuekeys: INCOMPATIBLE TYPES
    var primTypeL3115: C = funIntFloatDouble(100L, 42.5f)   //## issuekeys: INCOMPATIBLE TYPES
    var primTypeL3116: C = funIntFloatDouble(100L, 100L)    //## issuekeys: INCOMPATIBLE TYPES
    var primTypeL3117: C = funIntFloatDouble(100L, 42.5)
    var primTypeL3118: C = funIntFloatDouble(100L, d1)

    //IDE-1436
    var primTypeL4111 = funIntFloatDouble(100L, 'c')
    var primTypeL4112 = funIntFloatDouble(100L, 1b)
    var primTypeL4113 = funIntFloatDouble(100L, 1s)
    var primTypeL4114 = funIntFloatDouble(100L, 42)
    var primTypeL4115 = funIntFloatDouble(100L, 42.5f)
    var primTypeL4116 = funIntFloatDouble(100L, 100L)
    var primTypeL4117 = funIntFloatDouble(100L, 42.5)
    var primTypeL4118 = funIntFloatDouble(100L, d1)

    //Double (as a constant which may be treated as float when function(double, double) is not there)
    var primTypeD1111: A = funIntFloatDouble(42.5, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'
    var primTypeD1112: A = funIntFloatDouble(42.5, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'
    var primTypeD1113: A = funIntFloatDouble(42.5, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'
    var primTypeD1114: A = funIntFloatDouble(42.5, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'
    var primTypeD1115: A = funIntFloatDouble(42.5, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'
    var primTypeD1116: A = funIntFloatDouble(42.5, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'
    var primTypeD1117: A = funIntFloatDouble(42.5, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'
    var primTypeD1118: A = funIntFloatDouble(42.5, d1)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'

    var primTypeD2111: B = funIntFloatDouble(42.5, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'
    var primTypeD2112: B = funIntFloatDouble(42.5, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'
    var primTypeD2113: B = funIntFloatDouble(42.5, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'
    var primTypeD2114: B = funIntFloatDouble(42.5, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'
    var primTypeD2115: B = funIntFloatDouble(42.5, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'
    var primTypeD2116: B = funIntFloatDouble(42.5, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'
    var primTypeD2117: B = funIntFloatDouble(42.5, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'
    var primTypeD2118: B = funIntFloatDouble(42.5, d1)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'

    var primTypeD3111: C = funIntFloatDouble(42.5, 'c')
    var primTypeD3112: C = funIntFloatDouble(42.5, 1b)
    var primTypeD3113: C = funIntFloatDouble(42.5, 1s)
    var primTypeD3114: C = funIntFloatDouble(42.5, 42)
    var primTypeD3115: C = funIntFloatDouble(42.5, 42.5f)
    var primTypeD3116: C = funIntFloatDouble(42.5, 100L)
    var primTypeD3117: C = funIntFloatDouble(42.5, 42.5)
    var primTypeD3118: C = funIntFloatDouble(42.5, d1)

    var primTypeD4111 = funIntFloatDouble(42.5, 'c')
    var primTypeD4112 = funIntFloatDouble(42.5, 1b)
    var primTypeD4113 = funIntFloatDouble(42.5, 1s)
    var primTypeD4114 = funIntFloatDouble(42.5, 42)
    var primTypeD4115 = funIntFloatDouble(42.5, 42.5f)
    var primTypeD4116 = funIntFloatDouble(42.5, 100L)
    var primTypeD4117 = funIntFloatDouble(42.5, 42.5)
    var primTypeD4118 = funIntFloatDouble(42.5, d1)

    //Double extracted as a variable
    var primTypeDV1111: A = funIntFloatDouble(d1, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'
    var primTypeDV1112: A = funIntFloatDouble(d1, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'
    var primTypeDV1113: A = funIntFloatDouble(d1, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'
    var primTypeDV1114: A = funIntFloatDouble(d1, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'
    var primTypeDV1115: A = funIntFloatDouble(d1, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'
    var primTypeDV1116: A = funIntFloatDouble(d1, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'
    var primTypeDV1117: A = funIntFloatDouble(d1, d2)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.A'

    var primTypeDV2111: B = funIntFloatDouble(d1, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'
    var primTypeDV2112: B = funIntFloatDouble(d1, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'
    var primTypeDV2113: B = funIntFloatDouble(d1, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'
    var primTypeDV2114: B = funIntFloatDouble(d1, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'
    var primTypeDV2115: B = funIntFloatDouble(d1, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'
    var primTypeDV2116: B = funIntFloatDouble(d1, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'
    var primTypeDV2117: B = funIntFloatDouble(d1, d2)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTFLOATDOUBLEMETHODS.B'

    var primTypeDV3111: C = funIntFloatDouble(d1, 'c')
    var primTypeDV3112: C = funIntFloatDouble(d1, 1b)
    var primTypeDV3113: C = funIntFloatDouble(d1, 1s)
    var primTypeDV3114: C = funIntFloatDouble(d1, 42)
    var primTypeDV3115: C = funIntFloatDouble(d1, 42.5f)
    var primTypeDV3116: C = funIntFloatDouble(d1, 100L)
    var primTypeDV3117: C = funIntFloatDouble(d1, d2)

    var primTypeDV4111 = funIntFloatDouble(d1, 'c')
    var primTypeDV4112 = funIntFloatDouble(d1, 1b)
    var primTypeDV4113 = funIntFloatDouble(d1, 1s)
    var primTypeDV4114 = funIntFloatDouble(d1, 42)
    var primTypeDV4115 = funIntFloatDouble(d1, 42.5f)
    var primTypeDV4116 = funIntFloatDouble(d1, 100L)
    var primTypeDV4117 = funIntFloatDouble(d1, d2)

  }
}