package gw.specContrib.classes.method_Scoring.primitive_Types

class Errant_IntLongFloatMethods {

  class A {
  }

  class B {
  }

  class C {
  }

  function funIntLongFloat(i: int, j: int): A {
    return null
  }

  function funIntLongFloat(i: long, j: long): B {
    return null
  }

  function funIntLongFloat(i: float, j: float): C {
    return null
  }



  var d1: double = 42.5
  var d2: double = 43.5

  function caller() {
    //char
    //IDE-1391 for (char, char)
    var primTypeC1111: A = funIntLongFloat('c', 'c')
    var primTypeC1112: A = funIntLongFloat('c', 1b)
    var primTypeC1113: A = funIntLongFloat('c', 1s)
    var primTypeC1114: A = funIntLongFloat('c', 42)
    var primTypeC1115: A = funIntLongFloat('c', 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A'
    var primTypeC1116: A = funIntLongFloat('c', 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A'
    var primTypeC1117: A = funIntLongFloat('c', 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A'
    var primTypeC1118: A = funIntLongFloat('c', d1)      //## issuekeys: 'FUNINTLONGFLOAT(FLOAT, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(CHAR, DOUBLE)'

    var primTypeC2111: B = funIntLongFloat('c', 'c')      //## issuekeys: AMBIGUOUS METHOD CALL: BOTH 'ERRANT_INTLONGFLOATMETHODS.FUNINTLONGFLOAT(INT, INT)' AND 'ERRANT_INTLONGFLOATMETHODS.FUNINTLONGFLOAT(LONG, LONG)' MATCH
    var primTypeC2112: B = funIntLongFloat('c', 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B'
    var primTypeC2113: B = funIntLongFloat('c', 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B'
    var primTypeC2114: B = funIntLongFloat('c', 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B'
    var primTypeC2115: B = funIntLongFloat('c', 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B'
    var primTypeC2116: B = funIntLongFloat('c', 100L)
    var primTypeC2117: B = funIntLongFloat('c', 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B'
    var primTypeC2118: B = funIntLongFloat('c', d1)      //## issuekeys: 'FUNINTLONGFLOAT(FLOAT, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(CHAR, DOUBLE)'

    var primTypeC3111: C = funIntLongFloat('c', 'c')      //## issuekeys: AMBIGUOUS METHOD CALL: BOTH 'ERRANT_INTLONGFLOATMETHODS.FUNINTLONGFLOAT(INT, INT)' AND 'ERRANT_INTLONGFLOATMETHODS.FUNINTLONGFLOAT(LONG, LONG)' MATCH
    var primTypeC3112: C = funIntLongFloat('c', 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C'
    var primTypeC3113: C = funIntLongFloat('c', 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C'
    var primTypeC3114: C = funIntLongFloat('c', 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C'
    var primTypeC3115: C = funIntLongFloat('c', 42.5f)
    var primTypeC3116: C = funIntLongFloat('c', 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C'
    var primTypeC3117: C = funIntLongFloat('c', 42.5)
    var primTypeC3118: C = funIntLongFloat('c', d1)      //## issuekeys: 'FUNINTLONGFLOAT(FLOAT, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(CHAR, DOUBLE)'

    //IDE-1391 for (char, char)
    var primTypeC4111 = funIntLongFloat('c', 'c')
    var primTypeC4112 = funIntLongFloat('c', 1b)
    var primTypeC4113 = funIntLongFloat('c', 1s)
    var primTypeC4114 = funIntLongFloat('c', 42)
    var primTypeC4115 = funIntLongFloat('c', 42.5f)
    var primTypeC4116 = funIntLongFloat('c', 100L)
    var primTypeC4117 = funIntLongFloat('c', 42.5)
    var primTypeC4118 = funIntLongFloat('c', d1)          //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(CHAR, DOUBLE)'

    //byte
    var primTypeB1111: A = funIntLongFloat(1b, 'c')
    var primTypeB1112: A = funIntLongFloat(1b, 1b)
    var primTypeB1113: A = funIntLongFloat(1b, 1s)
    var primTypeB1114: A = funIntLongFloat(1b, 42)
    var primTypeB1115: A = funIntLongFloat(1b, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A'
    var primTypeB1116: A = funIntLongFloat(1b, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A'
    var primTypeB1117: A = funIntLongFloat(1b, 42.5)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(BYTE, DOUBLE)'
    var primTypeB1118: A = funIntLongFloat(1b, d1)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(BYTE, DOUBLE)'

    var primTypeB2111: B = funIntLongFloat(1b, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B'
    var primTypeB2112: B = funIntLongFloat(1b, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B'
    var primTypeB2113: B = funIntLongFloat(1b, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B'
    var primTypeB2114: B = funIntLongFloat(1b, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B'
    var primTypeB2115: B = funIntLongFloat(1b, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B'
    var primTypeB2116: B = funIntLongFloat(1b, 100L)
    var primTypeB2117: B = funIntLongFloat(1b, 42.5)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(BYTE, DOUBLE)'
    var primTypeB2118: B = funIntLongFloat(1b, d1)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(BYTE, DOUBLE)'

    var primTypeB3111: C = funIntLongFloat(1b, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C'
    var primTypeB3112: C = funIntLongFloat(1b, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C'
    var primTypeB3113: C = funIntLongFloat(1b, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C'
    var primTypeB3114: C = funIntLongFloat(1b, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C'
    var primTypeB3115: C = funIntLongFloat(1b, 42.5f)
    var primTypeB3116: C = funIntLongFloat(1b, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C'
    var primTypeB3117: C = funIntLongFloat(1b, 42.5)
    var primTypeB3118: C = funIntLongFloat(1b, d1)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(BYTE, DOUBLE)'

    var primTypeB4111 = funIntLongFloat(1b, 'c')
    var primTypeB4112 = funIntLongFloat(1b, 1b)
    var primTypeB4113 = funIntLongFloat(1b, 1s)
    var primTypeB4114 = funIntLongFloat(1b, 42)
    var primTypeB4115 = funIntLongFloat(1b, 42.5f)
    var primTypeB4116 = funIntLongFloat(1b, 100L)
    //IDE-1388 OS Gosu GOOD. Parser shows error here BAD
    var primTypeB4117 = funIntLongFloat(1b, 42.5)
    var primTypeB4118 = funIntLongFloat(1b, d1)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(BYTE, DOUBLE)'

    //short
    var primTypeS1111: A = funIntLongFloat(1s, 'c')
    var primTypeS1112: A = funIntLongFloat(1s, 1b)
    var primTypeS1113: A = funIntLongFloat(1s, 1s)
    var primTypeS1114: A = funIntLongFloat(1s, 42)
    var primTypeS1115: A = funIntLongFloat(1s, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A'
    var primTypeS1116: A = funIntLongFloat(1s, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A'
    var primTypeS1117: A = funIntLongFloat(1s, 42.5)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(SHORT, DOUBLE)'
    var primTypeS1118: A = funIntLongFloat(1s, d1)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(SHORT, DOUBLE)'

    var primTypeS2111: B = funIntLongFloat(1s, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B'
    var primTypeS2112: B = funIntLongFloat(1s, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B'
    var primTypeS2113: B = funIntLongFloat(1s, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B'
    var primTypeS2114: B = funIntLongFloat(1s, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B'
    var primTypeS2115: B = funIntLongFloat(1s, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B'
    var primTypeS2116: B = funIntLongFloat(1s, 100L)
    var primTypeS2117: B = funIntLongFloat(1s, 42.5)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(SHORT, DOUBLE)'
    var primTypeS2118: B = funIntLongFloat(1s, d1)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(SHORT, DOUBLE)'

    var primTypeS3111: C = funIntLongFloat(1s, 'c')     //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C'
    var primTypeS3112: C = funIntLongFloat(1s, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C'
    var primTypeS3113: C = funIntLongFloat(1s, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C'
    var primTypeS3114: C = funIntLongFloat(1s, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C'
    var primTypeS3115: C = funIntLongFloat(1s, 42.5f)
    var primTypeS3116: C = funIntLongFloat(1s, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C'
    //IDE-1388
    var primTypeS3117: C = funIntLongFloat(1s, 42.5)
    var primTypeS3118: C = funIntLongFloat(1s, d1)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(SHORT, DOUBLE)'

    var primTypeS4111 = funIntLongFloat(1s, 'c')
    var primTypeS4112 = funIntLongFloat(1s, 1b)
    var primTypeS4113 = funIntLongFloat(1s, 1s)
    var primTypeS4114 = funIntLongFloat(1s, 42)
    var primTypeS4115 = funIntLongFloat(1s, 42.5f)
    var primTypeS4116 = funIntLongFloat(1s, 100L)
    //IDE-1388 Need to be fixed in parser. Should not show error
    var primTypeS4117 = funIntLongFloat(1s, 42.5)
    var primTypeS4118 = funIntLongFloat(1s, d1)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(SHORT, DOUBLE)'

    //int
    var primTypeI1111: A = funIntLongFloat(42, 'c')
    var primTypeI1112: A = funIntLongFloat(42, 1b)
    var primTypeI1113: A = funIntLongFloat(42, 1s)
    var primTypeI1114: A = funIntLongFloat(42, 42)
    var primTypeI1115: A = funIntLongFloat(42, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A'
    var primTypeI1116: A = funIntLongFloat(42, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A'
    var primTypeI1117: A = funIntLongFloat(42, 42.5)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(INT, DOUBLE)'
    var primTypeI1118: A = funIntLongFloat(42, d1)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(INT, DOUBLE)'

    var primTypeI2111: B = funIntLongFloat(42, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B'
    var primTypeI2112: B = funIntLongFloat(42, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B'
    var primTypeI2113: B = funIntLongFloat(42, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B'
    var primTypeI2114: B = funIntLongFloat(42, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B'
    var primTypeI2115: B = funIntLongFloat(42, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B'
    var primTypeI2116: B = funIntLongFloat(42, 100L)
    var primTypeI2117: B = funIntLongFloat(42, 42.5)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(INT, DOUBLE)'
    var primTypeI2118: B = funIntLongFloat(42, d1)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(INT, DOUBLE)'

    var primTypeI3111: C = funIntLongFloat(42, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C'
    var primTypeI3112: C = funIntLongFloat(42, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C'
    var primTypeI3113: C = funIntLongFloat(42, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C'
    var primTypeI3114: C = funIntLongFloat(42, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C'
    var primTypeI3115: C = funIntLongFloat(42, 42.5f)
    var primTypeI3116: C = funIntLongFloat(42, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C'
    //IDE-1388
    var primTypeI3117: C = funIntLongFloat(42, 42.5)
    var primTypeI3118: C = funIntLongFloat(42, d1)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(INT, DOUBLE)'

    var primTypeI4111 = funIntLongFloat(42, 'c')
    var primTypeI4112 = funIntLongFloat(42, 1b)
    var primTypeI4113 = funIntLongFloat(42, 1s)
    var primTypeI4114 = funIntLongFloat(42, 42)
    var primTypeI4115 = funIntLongFloat(42, 42.5f)
    var primTypeI4116 = funIntLongFloat(42, 100L)
    //IDE-1388
    var primTypeI4117 = funIntLongFloat(42, 42.5)
    var primTypeI4118 = funIntLongFloat(42, d1)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(INT, DOUBLE)'

    //float
    var primTypeF1111: A = funIntLongFloat(42.5f, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A'
    var primTypeF1112: A = funIntLongFloat(42.5f, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A'
    var primTypeF1113: A = funIntLongFloat(42.5f, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A'
    var primTypeF1114: A = funIntLongFloat(42.5f, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A'
    var primTypeF1115: A = funIntLongFloat(42.5f, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A'
    var primTypeF1116: A = funIntLongFloat(42.5f, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A'
    var primTypeF1117: A = funIntLongFloat(42.5f, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A'
    var primTypeF1118: A = funIntLongFloat(42.5f, d1)      //## issuekeys: 'FUNINTLONGFLOAT(FLOAT, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(FLOAT, DOUBLE)'

    var primTypeF2111: B = funIntLongFloat(42.5f, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B'
    var primTypeF2112: B = funIntLongFloat(42.5f, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B'
    var primTypeF2113: B = funIntLongFloat(42.5f, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B'
    var primTypeF2114: B = funIntLongFloat(42.5f, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B'
    var primTypeF2115: B = funIntLongFloat(42.5f, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B'
    var primTypeF2116: B = funIntLongFloat(42.5f, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B'
    var primTypeF2117: B = funIntLongFloat(42.5f, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B'
    var primTypeF2118: B = funIntLongFloat(42.5f, d1)      //## issuekeys: 'FUNINTLONGFLOAT(FLOAT, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(FLOAT, DOUBLE)'

    var primTypeF3111: C = funIntLongFloat(42.5f, 'c')
    var primTypeF3112: C = funIntLongFloat(42.5f, 1b)
    var primTypeF3113: C = funIntLongFloat(42.5f, 1s)
    var primTypeF3114: C = funIntLongFloat(42.5f, 42)
    var primTypeF3115: C = funIntLongFloat(42.5f, 42.5f)
    var primTypeF3116: C = funIntLongFloat(42.5f, 100L)
    var primTypeF3117: C = funIntLongFloat(42.5f, 42.5)
    var primTypeF3118: C = funIntLongFloat(42.5f, d1)      //## issuekeys: 'FUNINTLONGFLOAT(FLOAT, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(FLOAT, DOUBLE)'

    var primTypeF4111 = funIntLongFloat(42.5f, 'c')
    var primTypeF4112 = funIntLongFloat(42.5f, 1b)
    var primTypeF4113 = funIntLongFloat(42.5f, 1s)
    var primTypeF4114 = funIntLongFloat(42.5f, 42)
    var primTypeF4115 = funIntLongFloat(42.5f, 42.5f)
    var primTypeF4116 = funIntLongFloat(42.5f, 100L)
    var primTypeF4117 = funIntLongFloat(42.5f, 42.5)
    var primTypeF4118 = funIntLongFloat(42.5f, d1)      //## issuekeys: 'FUNINTLONGFLOAT(FLOAT, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(FLOAT, DOUBLE)'

    //long
    var primTypeL1111: A = funIntLongFloat(100L, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A'
    var primTypeL1112: A = funIntLongFloat(100L, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A'
    var primTypeL1113: A = funIntLongFloat(100L, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A'
    var primTypeL1114: A = funIntLongFloat(100L, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A'
    var primTypeL1115: A = funIntLongFloat(100L, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A'
    var primTypeL1116: A = funIntLongFloat(100L, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A'
    var primTypeL1117: A = funIntLongFloat(100L, 42.5)      //## issuekeys: 'FUNINTLONGFLOAT(LONG, LONG)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(LONG, DOUBLE)'
    var primTypeL1118: A = funIntLongFloat(100L, d1)      //## issuekeys: 'FUNINTLONGFLOAT(LONG, LONG)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(LONG, DOUBLE)'

    var primTypeL2111: B = funIntLongFloat(100L, 'c')
    var primTypeL2112: B = funIntLongFloat(100L, 1b)
    var primTypeL2113: B = funIntLongFloat(100L, 1s)
    var primTypeL2114: B = funIntLongFloat(100L, 42)
    var primTypeL2115: B = funIntLongFloat(100L, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B'
    var primTypeL2116: B = funIntLongFloat(100L, 100L)
    var primTypeL2117: B = funIntLongFloat(100L, 42.5)      //## issuekeys: 'FUNINTLONGFLOAT(LONG, LONG)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(LONG, DOUBLE)'
    var primTypeL2118: B = funIntLongFloat(100L, d1)      //## issuekeys: 'FUNINTLONGFLOAT(LONG, LONG)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(LONG, DOUBLE)'

    var primTypeL3111: C = funIntLongFloat(100L, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C'
    var primTypeL3112: C = funIntLongFloat(100L, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C'
    var primTypeL3113: C = funIntLongFloat(100L, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C'
    var primTypeL3114: C = funIntLongFloat(100L, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C'
    var primTypeL3115: C = funIntLongFloat(100L, 42.5f)
    var primTypeL3116: C = funIntLongFloat(100L, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C'
    var primTypeL3117: C = funIntLongFloat(100L, 42.5)
    var primTypeL3118: C = funIntLongFloat(100L, d1)      //## issuekeys: 'FUNINTLONGFLOAT(LONG, LONG)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(LONG, DOUBLE)'

    var primTypeL4111 = funIntLongFloat(100L, 'c')
    var primTypeL4112 = funIntLongFloat(100L, 1b)
    var primTypeL4113 = funIntLongFloat(100L, 1s)
    var primTypeL4114 = funIntLongFloat(100L, 42)
    var primTypeL4115 = funIntLongFloat(100L, 42.5f)
    var primTypeL4116 = funIntLongFloat(100L, 100L)
    var primTypeL4117 = funIntLongFloat(100L, 42.5)
    var primTypeL4118 = funIntLongFloat(100L, d1)      //## issuekeys: 'FUNINTLONGFLOAT(LONG, LONG)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(LONG, DOUBLE)'

    //double
    var primTypeD1111: A = funIntLongFloat(42.5, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A'
    var primTypeD1112: A = funIntLongFloat(42.5, 1b)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, BYTE)'
    var primTypeD1113: A = funIntLongFloat(42.5, 1s)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, SHORT)'
    var primTypeD1114: A = funIntLongFloat(42.5, 42)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, INT)'
    var primTypeD1115: A = funIntLongFloat(42.5, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A'
    var primTypeD1116: A = funIntLongFloat(42.5, 100L)      //## issuekeys: 'FUNINTLONGFLOAT(LONG, LONG)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, LONG)'
    var primTypeD1117: A = funIntLongFloat(42.5, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.A'
    var primTypeD1118: A = funIntLongFloat(42.5, d1)      //## issuekeys: 'FUNINTLONGFLOAT(FLOAT, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, DOUBLE)'

    var primTypeD2111: B = funIntLongFloat(42.5, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B'
    var primTypeD2112: B = funIntLongFloat(42.5, 1b)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, BYTE)'
    var primTypeD2113: B = funIntLongFloat(42.5, 1s)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, SHORT)'
    var primTypeD2114: B = funIntLongFloat(42.5, 42)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, INT)'
    var primTypeD2115: B = funIntLongFloat(42.5, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B'
    var primTypeD2116: B = funIntLongFloat(42.5, 100L)      //## issuekeys: 'FUNINTLONGFLOAT(LONG, LONG)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, LONG)'
    var primTypeD2117: B = funIntLongFloat(42.5, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS.B'
    var primTypeD2118: B = funIntLongFloat(42.5, d1)      //## issuekeys: 'FUNINTLONGFLOAT(FLOAT, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, DOUBLE)'

    var primTypeD3111: C = funIntLongFloat(42.5, 'c')
    //IDE-1388 for next 2,3,4,6 cases for Parser. OS Gosu is good after the fix.
    var primTypeD3112: C = funIntLongFloat(42.5, 1b)
    var primTypeD3113: C = funIntLongFloat(42.5, 1s)
    var primTypeD3114: C = funIntLongFloat(42.5, 42)
    var primTypeD3115: C = funIntLongFloat(42.5, 42.5f)
    var primTypeD3116: C = funIntLongFloat(42.5, 100L)
    var primTypeD3117: C = funIntLongFloat(42.5, 42.5)
    var primTypeD3118: C = funIntLongFloat(42.5, d1)      //## issuekeys: 'FUNINTLONGFLOAT(FLOAT, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, DOUBLE)'

    var primTypeD4111 = funIntLongFloat(42.5, 'c')
    //IDE-1388 for next 2,3,4,6 cases for Parser. OS Gosu is good after the fix.
    var primTypeD4112 = funIntLongFloat(42.5, 1b)
    var primTypeD4113 = funIntLongFloat(42.5, 1s)
    var primTypeD4114 = funIntLongFloat(42.5, 42)
    var primTypeD4115 = funIntLongFloat(42.5, 42.5f)
    var primTypeD4116 = funIntLongFloat(42.5, 100L)
    var primTypeD4117 = funIntLongFloat(42.5, 42.5)
    var primTypeD4118 = funIntLongFloat(42.5, d1)      //## issuekeys: 'FUNINTLONGFLOAT(FLOAT, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, DOUBLE)'

    //double extracted as a variable
    var primTypeDV1111: A = funIntLongFloat(d1, 'c')      //## issuekeys: 'FUNINTLONGFLOAT(FLOAT, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, CHAR)'
    var primTypeDV1112: A = funIntLongFloat(d1, 1b)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, BYTE)'
    var primTypeDV1113: A = funIntLongFloat(d1, 1s)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, SHORT)'
    var primTypeDV1114: A = funIntLongFloat(d1, 42)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, INT)'
    var primTypeDV1115: A = funIntLongFloat(d1, 42.5f)      //## issuekeys: 'FUNINTLONGFLOAT(FLOAT, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, FLOAT)'
    var primTypeDV1116: A = funIntLongFloat(d1, 100L)      //## issuekeys: 'FUNINTLONGFLOAT(LONG, LONG)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, LONG)'
    var primTypeDV1117: A = funIntLongFloat(d1, d2)      //## issuekeys: 'FUNINTLONGFLOAT(FLOAT, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, DOUBLE)'

    var primTypeDV2111: B = funIntLongFloat(d1, 'c')      //## issuekeys: 'FUNINTLONGFLOAT(FLOAT, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, CHAR)'
    var primTypeDV2112: B = funIntLongFloat(d1, 1b)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, BYTE)'
    var primTypeDV2113: B = funIntLongFloat(d1, 1s)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, SHORT)'
    var primTypeDV2114: B = funIntLongFloat(d1, 42)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, INT)'
    var primTypeDV2115: B = funIntLongFloat(d1, 42.5f)      //## issuekeys: 'FUNINTLONGFLOAT(FLOAT, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, FLOAT)'
    var primTypeDV2116: B = funIntLongFloat(d1, 100L)      //## issuekeys: 'FUNINTLONGFLOAT(LONG, LONG)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, LONG)'
    var primTypeDV2117: B = funIntLongFloat(d1, d2)      //## issuekeys: 'FUNINTLONGFLOAT(FLOAT, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, DOUBLE)'

    var primTypeDV3111: C = funIntLongFloat(d1, 'c')      //## issuekeys: 'FUNINTLONGFLOAT(FLOAT, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, CHAR)'
    var primTypeDV3112: C = funIntLongFloat(d1, 1b)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, BYTE)'
    var primTypeDV3113: C = funIntLongFloat(d1, 1s)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, SHORT)'
    var primTypeDV3114: C = funIntLongFloat(d1, 42)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, INT)'
    var primTypeDV3115: C = funIntLongFloat(d1, 42.5f)      //## issuekeys: 'FUNINTLONGFLOAT(FLOAT, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, FLOAT)'
    var primTypeDV3116: C = funIntLongFloat(d1, 100L)      //## issuekeys: 'FUNINTLONGFLOAT(LONG, LONG)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, LONG)'
    var primTypeDV3117: C = funIntLongFloat(d1, d2)      //## issuekeys: 'FUNINTLONGFLOAT(FLOAT, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, DOUBLE)'

    var primTypeDV4111 = funIntLongFloat(d1, 'c')      //## issuekeys: 'FUNINTLONGFLOAT(FLOAT, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, CHAR)'
    var primTypeDV4112 = funIntLongFloat(d1, 1b)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, BYTE)'
    var primTypeDV4113 = funIntLongFloat(d1, 1s)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, SHORT)'
    var primTypeDV4114 = funIntLongFloat(d1, 42)      //## issuekeys: 'FUNINTLONGFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, INT)'
    var primTypeDV4115 = funIntLongFloat(d1, 42.5f)      //## issuekeys: 'FUNINTLONGFLOAT(FLOAT, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, FLOAT)'
    var primTypeDV4116 = funIntLongFloat(d1, 100L)      //## issuekeys: 'FUNINTLONGFLOAT(LONG, LONG)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, LONG)'
    var primTypeDV4117 = funIntLongFloat(d1, d2)      //## issuekeys: 'FUNINTLONGFLOAT(FLOAT, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGFLOATMETHODS' CANNOT BE APPLIED TO '(DOUBLE, DOUBLE)'

  }
}