package gw.specContrib.classes.method_Scoring.primitive_Types

class Errant_AllPrimitiveTypesMethods {
  class Char1 {
  }

  class Byte1 {
  }

  class Short1 {
  }

  class Int1 {
  }

  class Float1 {
  }

  class Long1 {
  }

  class Double1 {
  }


  function fun(i: char, j: char): Char1 {
    return null
  }

  function fun(i: byte, j: byte): Byte1 {
    return null
  }

  function fun(i: short, j: short): Short1 {
    return null
  }

  function fun(i: int, j: int): Int1 {
    return null
  }

  function fun(i: long, j: long): Long1 {
    return null
  }

  function fun(i: float, j: float): Float1 {
    return null
  }

  function fun(i: double, j: double): Double1 {
    return null
  }

  //Sets with type on LHS specified
  function callerChar() {
    var primTypeC1111: Char1 = fun('c', 'c')
    var primTypeC1112: Char1 = fun('c', 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.INT1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.CHAR1'
    var primTypeC1113: Char1 = fun('c', 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.INT1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.CHAR1'
    var primTypeC1114: Char1 = fun('c', 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.INT1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.CHAR1'
    var primTypeC1115: Char1 = fun('c', 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.FLOAT1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.CHAR1'
    var primTypeC1116: Char1 = fun('c', 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.LONG1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.CHAR1'
    var primTypeC1117: Char1 = fun('c', 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.DOUBLE1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.CHAR1'

    //Reverse
    var primTypeC2111: Char1 = fun('c', 'c')
    var primTypeC2112: Char1 = fun(1b, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.INT1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.CHAR1'
    var primTypeC2113: Char1 = fun(1s, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.INT1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.CHAR1'
    var primTypeC2114: Char1 = fun(42, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.INT1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.CHAR1'
    var primTypeC2115: Char1 = fun(42.5f, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.FLOAT1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.CHAR1'
    var primTypeC2116: Char1 = fun(100L, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.LONG1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.CHAR1'
    var primTypeC2117: Char1 = fun(42.5, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.DOUBLE1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.CHAR1'

    //LHS not specified
    var primTypeC3111 = fun('c', 'c')
    //IDE-1381 - OS Gosu shows error here - Fixed
    var primTypeC3112 = fun('c', 1b)
    var primTypeC3113 = fun('c', 1s)
    var primTypeC3114 = fun('c', 42)
    var primTypeC3115 = fun('c', 42.5f)
    var primTypeC3116 = fun('c', 100L)
    var primTypeC3117 = fun('c', 42.5)

  }

  function callerByte() {
    var primTypeB1111: Byte1 = fun(1b, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.INT1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.BYTE1'
    var primTypeB1112: Byte1 = fun(1b, 1b)
    var primTypeB1113: Byte1 = fun(1b, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.SHORT1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.BYTE1'
    var primTypeB1114: Byte1 = fun(1b, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.INT1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.BYTE1'
    var primTypeB1115: Byte1 = fun(1b, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.FLOAT1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.BYTE1'
    var primTypeB1116: Byte1 = fun(1b, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.LONG1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.BYTE1'
    var primTypeB1117: Byte1 = fun(1b, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.DOUBLE1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.BYTE1'

    var primTypeB2111: Byte1 = fun('c', 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.INT1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.BYTE1'
    var primTypeB2112: Byte1 = fun(1b, 1b)
    var primTypeB2113: Byte1 = fun(1s, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.SHORT1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.BYTE1'
    var primTypeB2114: Byte1 = fun(42, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.INT1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.BYTE1'
    var primTypeB2115: Byte1 = fun(42.5f, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.FLOAT1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.BYTE1'
    var primTypeB2116: Byte1 = fun(100L, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.LONG1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.BYTE1'
    var primTypeB2117: Byte1 = fun(42.5, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.DOUBLE1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.BYTE1'

    //IDE-1381 - OS Gosu shows error here - Fixed
    var primTypeB3111 = fun(1b, 'c')
    var primTypeB3112 = fun(1b, 1b)
    var primTypeB3113 = fun(1b, 1s)
    var primTypeB3114 = fun(1b, 42)
    var primTypeB3115 = fun(1b, 42.5f)
    var primTypeB3116 = fun(1b, 100L)
    var primTypeB3117 = fun(1b, 42.5)

  }

  function callerShort() {
    var primTypeS1111: Short1 = fun(1s, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.INT1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.SHORT1'
    var primTypeS1112: Short1 = fun(1s, 1b)
    var primTypeS1113: Short1 = fun(1s, 1s)
    var primTypeS1114: Short1 = fun(1s, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.INT1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.SHORT1'
    var primTypeS1115: Short1 = fun(1s, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.FLOAT1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.SHORT1'
    var primTypeS1116: Short1 = fun(1s, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.LONG1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.SHORT1'
    var primTypeS1117: Short1 = fun(1s, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.DOUBLE1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.SHORT1'

    var primTypeS2111: Short1 = fun('c', 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.INT1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.SHORT1'
    var primTypeS2112: Short1 = fun(1b, 1s)
    var primTypeS2113: Short1 = fun(1s, 1s)
    var primTypeS2114: Short1 = fun(42, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.INT1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.SHORT1'
    var primTypeS2115: Short1 = fun(42.5f, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.FLOAT1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.SHORT1'
    var primTypeS2116: Short1 = fun(100L, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.LONG1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.SHORT1'
    var primTypeS2117: Short1 = fun(42.5, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.DOUBLE1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.SHORT1'

    var primTypeS3111 = fun(1s, 'c')
    var primTypeS3112 = fun(1s, 1b)
    var primTypeS3113 = fun(1s, 1s)
    var primTypeS3114 = fun(1s, 42)
    var primTypeS3115 = fun(1s, 42.5f)
    var primTypeS3116 = fun(1s, 100L)
    var primTypeS3117 = fun(1s, 42.5)

  }

  function callerInt() {
    var primTypeI1111: Int1 = fun(42, 'c')
    var primTypeI1112: Int1 = fun(42, 1b)
    var primTypeI1113: Int1 = fun(42, 1s)
    var primTypeI1114: Int1 = fun(42, 42)
    var primTypeI1115: Int1 = fun(42, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.DOUBLE1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.INT1'
    var primTypeI1116: Int1 = fun(42, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.LONG1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.INT1'
    var primTypeI1117: Int1 = fun(42, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.DOUBLE1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.INT1'

    var primTypeI2111: Int1 = fun('c', 42)
    var primTypeI2112: Int1 = fun(1b, 42)
    var primTypeI2113: Int1 = fun(1s, 42)
    var primTypeI2114: Int1 = fun(42, 42)
    var primTypeI2115: Int1 = fun(42.5f, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.DOUBLE1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.INT1'
    var primTypeI2116: Int1 = fun(100L, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.LONG1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.INT1'
    var primTypeI2117: Int1 = fun(42.5, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.DOUBLE1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.INT1'

    var primTypeI3111 = fun(42, 'c')
    var primTypeI3112 = fun(42, 1b)
    var primTypeI3113 = fun(42, 1s)
    var primTypeI3114 = fun(42, 42)
    var primTypeI3115 = fun(42, 42.5f)
    var primTypeI3116 = fun(42, 100L)
    var primTypeI3117 = fun(42, 42.5)

  }

  function callerFloat() {
    var primTypeF1111: Float1 = fun(42.5f, 'c')
    var primTypeF1112: Float1 = fun(42.5f, 1b)
    var primTypeF1113: Float1 = fun(42.5f, 1s)
    //IDE-820 Needs to be fixed in Parser. Should go to (float, float)
    var primTypeF1114: Float1 = fun(42.5f, 42)
    var primTypeF1115: Float1 = fun(42.5f, 42.5f)
    //IDE-474 Goes to (float, float) as Java does
    var primTypeF1116: Float1 = fun(42.5f, 100L)
    var primTypeF1117: Float1 = fun(42.5f, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.DOUBLE1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.FLOAT1'

    var primTypeF2111: Float1 = fun('c', 42.5f)
    var primTypeF2112: Float1 = fun(1b, 42.5f)
    var primTypeF2113: Float1 = fun(1s, 42.5f)
    //IDE-820 Needs to be fixed in Parser. Should go to (float, float)
    var primTypeF2114: Float1 = fun(42, 42.5f)
    var primTypeF2115: Float1 = fun(42.5f, 42.5f)
    //IDE-474 Goes to (float, float) as Java does
    var primTypeF2116: Float1 = fun(100L, 42.5f)
    var primTypeF2117: Float1 = fun(42.5, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.DOUBLE1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.FLOAT1'

    var primTypeF3111 = fun(42.5f, 'c')
    var primTypeF3112 = fun(42.5f, 1b)
    var primTypeF3113 = fun(42.5f, 1s)
    var primTypeF3114 = fun(42.5f, 42)
    var primTypeF3115 = fun(42.5f, 42.5f)
    var primTypeF3116 = fun(42.5f, 100L)
    var primTypeF3117 = fun(42.5f, 42.5)
  }

  function callerLong() {
    var primTypeL1111: Long1 = fun(100L, 'c')
    var primTypeL1112: Long1 = fun(100L, 1b)
    var primTypeL1113: Long1 = fun(100L, 1s)
    var primTypeL1114: Long1 = fun(100L, 42)
    var primTypeL1115: Long1 = fun(100L, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.FLOAT1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.LONG1'
    var primTypeL1116: Long1 = fun(100L, 100L)
    var primTypeL1117: Long1 = fun(100L, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.DOUBLE1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.LONG1'

    var primTypeL2111: Long1 = fun('c', 100L)
    var primTypeL2112: Long1 = fun(1b, 100L)
    var primTypeL2113: Long1 = fun(1s, 100L)
    var primTypeL2114: Long1 = fun(42, 100L)
    var primTypeL2115: Long1 = fun(42.5f, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.FLOAT1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.LONG1'
    var primTypeL2116: Long1 = fun(100L, 100L)
    var primTypeL2117: Long1 = fun(42.5, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.DOUBLE1', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_ALLPRIMITIVETYPES.LONG1'

    var primTypeL3111 = fun(100L, 'c')
    var primTypeL3112 = fun(100L, 1b)
    var primTypeL3113 = fun(100L, 1s)
    var primTypeL3114 = fun(100L, 42)
    var primTypeL3115 = fun(100L, 42.5f)
    var primTypeL3116 = fun(100L, 100L)
    var primTypeL3117 = fun(100L, 42.5)
  }

  function callerDouble() {
    var primTypeD1111: Double1 = fun(42.5, 'c')
    var primTypeD1112: Double1 = fun(42.5, 1b)
    var primTypeD1113: Double1 = fun(42.5, 1s)
    var primTypeD1114: Double1 = fun(42.5, 42)
    var primTypeD1115: Double1 = fun(42.5, 42.5f)
    var primTypeD1116: Double1 = fun(42.5, 100L)
    var primTypeD1117: Double1 = fun(42.5, 42.5)

    var primTypeD2111: Double1 = fun('c', 42.5)
    var primTypeD2112: Double1 = fun(1b, 42.5)
    var primTypeD2113: Double1 = fun(1s, 42.5)
    var primTypeD2114: Double1 = fun(42, 42.5)
    var primTypeD2115: Double1 = fun(42.5f, 42.5)
    var primTypeD2116: Double1 = fun(100L, 42.5)
    var primTypeD2117: Double1 = fun(42.5, 42.5)

    var primTypeD3111 = fun(42.5, 'c')
    var primTypeD3112 = fun(42.5, 1b)
    var primTypeD3113 = fun(42.5, 1s)
    var primTypeD3114 = fun(42.5, 42)
    var primTypeD3115 = fun(42.5, 42.5f)
    var primTypeD3116 = fun(42.5, 100L)
    var primTypeD3117 = fun(42.5, 42.5)
  }

}