package gw.specContrib.classes.method_Scoring.primitive_Types

class Errant_IntFloatMethods {

  class A {
  }

  class B {
  }

  class C {
  }

  function funIntFloat(i: int, j: int): A {
    return null
  }

  function funIntFloat(i: float, j: float): B {
    return null
  }


  function caller() {
    //char
    //IDE-1391 for (char, char) - there should not be any error here. Call should go to (int, int).
    // Fixed for OS Gosu. Pending for Parser
    var primTypeC1111: A = funIntFloat('c', 'c')
    var primTypeC1112: A = funIntFloat('c', 1b)
    var primTypeC1113: A = funIntFloat('c', 1s)
    var primTypeC1114: A = funIntFloat('c', 42)
    var primTypeC1115: A = funIntFloat('c', 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A'
    var primTypeC1116: A = funIntFloat('c', 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A'
    var primTypeC1117: A = funIntFloat('c', 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A'

    //IDE-1391 for (char, char)
    var primTypeC2111: B = funIntFloat('c', 'c')      //## issuekeys: AMBIGUOUS METHOD CALL: BOTH 'CASE1.FUNINTFLOAT(INT, INT)' AND 'CASE1.FUNINTFLOAT(FLOAT, FLOAT)' MATCH
    var primTypeC2112: B = funIntFloat(1b, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B'
    var primTypeC2113: B = funIntFloat(1s, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B'
    var primTypeC2114: B = funIntFloat(42, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B'
    var primTypeC2115: B = funIntFloat(42.5f, 'c')
    //IDE-1392 - Parser Good. OS Gosu goes to (int, int) bad  - FIXED
    var primTypeC2116: B = funIntFloat(100L, 'c')
    var primTypeC2117: B = funIntFloat(42.5, 'c')

    //byte
    var primTypeB1111: A = funIntFloat(1b, 'c')
    var primTypeB1112: A = funIntFloat(1b, 1b)
    var primTypeB1113: A = funIntFloat(1b, 1s)
    var primTypeB1114: A = funIntFloat(1b, 42)
    var primTypeB1115: A = funIntFloat(1b, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A'
    var primTypeB1116: A = funIntFloat(1b, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A'
    var primTypeB1117: A = funIntFloat(1b, 42.5)      //## issuekeys: 'FUNINTFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.CASE1' CANNOT BE APPLIED TO '(BYTE, DOUBLE)'

    var primTypeB2111: B = funIntFloat(1b, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B'
    var primTypeB2112: B = funIntFloat(1b, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B'
    var primTypeB2113: B = funIntFloat(1b, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B'
    var primTypeB2114: B = funIntFloat(1b, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B'
    var primTypeB2115: B = funIntFloat(1b, 42.5f)
    var primTypeB2116: B = funIntFloat(1b, 100L)
    //IDE-494
    var primTypeB2117: B = funIntFloat(1b, 42.5)

    //short
    var primTypeS1111: A = funIntFloat(1s, 'c')
    var primTypeS1112: A = funIntFloat(1s, 1b)
    var primTypeS1113: A = funIntFloat(1s, 1s)
    var primTypeS1114: A = funIntFloat(1s, 42)
    var primTypeS1115: A = funIntFloat(1s, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A'
    var primTypeS1116: A = funIntFloat(1s, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A'
    var primTypeS1117: A = funIntFloat(1s, 42.5)      //## issuekeys: 'FUNINTFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.CASE1' CANNOT BE APPLIED TO '(SHORT, DOUBLE)'

    var primTypeS2111: B = funIntFloat(1s, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B'
    var primTypeS2112: B = funIntFloat(1s, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B'
    var primTypeS2113: B = funIntFloat(1s, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B'
    var primTypeS2114: B = funIntFloat(1s, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B'
    var primTypeS2115: B = funIntFloat(1s, 42.5f)
    var primTypeS2116: B = funIntFloat(1s, 100L)
    //IDE-494
    var primTypeS2117: B = funIntFloat(1s, 42.5)

    //int
    var primTypeI1111: A = funIntFloat(42, 'c')
    var primTypeI1112: A = funIntFloat(42, 1b)
    var primTypeI1113: A = funIntFloat(42, 1s)
    var primTypeI1114: A = funIntFloat(42, 42)
    var primTypeI1115: A = funIntFloat(42, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A'
    var primTypeI1116: A = funIntFloat(42, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A'
    var primTypeI1117: A = funIntFloat(42, 42.5)      //## issuekeys: 'FUNINTFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.CASE1' CANNOT BE APPLIED TO '(INT, DOUBLE)'

    var primTypeI2111: B = funIntFloat(42, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B'
    var primTypeI2112: B = funIntFloat(42, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B'
    var primTypeI2113: B = funIntFloat(42, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B'
    var primTypeI2114: B = funIntFloat(42, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B'
    var primTypeI2115: B = funIntFloat(42, 42.5f)
    //IDE-1392
    var primTypeI2116: B = funIntFloat(42, 100L)
    //IDE-494
    var primTypeI2117: B = funIntFloat(42, 42.5)

    //float
    var primTypeF1111: A = funIntFloat(42.5f, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A'
    var primTypeF1112: A = funIntFloat(42.5f, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A'
    var primTypeF1113: A = funIntFloat(42.5f, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A'
    var primTypeF1114: A = funIntFloat(42.5f, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A'
    var primTypeF1115: A = funIntFloat(42.5f, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A'
    var primTypeF1116: A = funIntFloat(42.5f, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A'
    var primTypeF1117: A = funIntFloat(42.5f, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A'

    var primTypeF2111: B = funIntFloat(42.5f, 'c')
    var primTypeF2112: B = funIntFloat(42.5f, 1b)
    var primTypeF2113: B = funIntFloat(42.5f, 1s)
    var primTypeF2114: B = funIntFloat(42.5f, 42)
    var primTypeF2115: B = funIntFloat(42.5f, 42.5f)
    var primTypeF2116: B = funIntFloat(42.5f, 100L)
    var primTypeF2117: B = funIntFloat(42.5f, 42.5)

    //long
    var primTypeL1111: A = funIntFloat(100L, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A'
    var primTypeL1112: A = funIntFloat(100L, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A'
    var primTypeL1113: A = funIntFloat(100L, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A'
    var primTypeL1114: A = funIntFloat(100L, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A'
    var primTypeL1115: A = funIntFloat(100L, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A'
    var primTypeL1116: A = funIntFloat(100L, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A'
    var primTypeL1117: A = funIntFloat(100L, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A'

    var primTypeL2111: B = funIntFloat(100L, 'c')
    var primTypeL2112: B = funIntFloat(100L, 1b)
    var primTypeL2113: B = funIntFloat(100L, 1s)
    var primTypeL2114: B = funIntFloat(100L, 42)
    var primTypeL2115: B = funIntFloat(100L, 42.5f)
    var primTypeL2116: B = funIntFloat(100L, 100L)
    var primTypeL2117: B = funIntFloat(100L, 42.5)

    //double - but the literal is acting as a float here - IDE-494
    var primTypeD1111: A = funIntFloat(42.5, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A'
    var primTypeD1112: A = funIntFloat(42.5, 1b)      //## issuekeys: 'FUNINTFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.CASE1' CANNOT BE APPLIED TO '(DOUBLE, BYTE)'
    var primTypeD1113: A = funIntFloat(42.5, 1s)      //## issuekeys: 'FUNINTFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.CASE1' CANNOT BE APPLIED TO '(DOUBLE, SHORT)'
    var primTypeD1114: A = funIntFloat(42.5, 42)      //## issuekeys: 'FUNINTFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.CASE1' CANNOT BE APPLIED TO '(DOUBLE, INT)'
    var primTypeD1115: A = funIntFloat(42.5, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A'
    var primTypeD1116: A = funIntFloat(42.5, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A'
    var primTypeD1117: A = funIntFloat(42.5, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.A'

    //IDE-1388, IDE-494 impact the following cases - 2112, 2113, 2114
    var primTypeD2111: B = funIntFloat(42.5, 'c')
    var primTypeD2112: B = funIntFloat(42.5, 1b)
    var primTypeD2113: B = funIntFloat(42.5, 1s)
    var primTypeD2114: B = funIntFloat(42.5, 42)
    var primTypeD2115: B = funIntFloat(42.5, 42.5f)
    var primTypeD2116: B = funIntFloat(42.5, 100L)
    var primTypeD2117: B = funIntFloat(42.5, 42.5)

    //Double extracted as a variable
    var d1: double = 42.5
    var d2: double = 43.5
    var primTypeDV1111: A = funIntFloat(d1, 'c')      //## issuekeys: 'FUNINTFLOAT(FLOAT, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.CASE1' CANNOT BE APPLIED TO '(DOUBLE, CHAR)'
    var primTypeDV1112: A = funIntFloat(d1, 1b)      //## issuekeys: 'FUNINTFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.CASE1' CANNOT BE APPLIED TO '(DOUBLE, BYTE)'
    var primTypeDV1113: A = funIntFloat(d1, 1s)      //## issuekeys: 'FUNINTFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.CASE1' CANNOT BE APPLIED TO '(DOUBLE, SHORT)'
    var primTypeDV1114: A = funIntFloat(d1, 42)      //## issuekeys: 'FUNINTFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.CASE1' CANNOT BE APPLIED TO '(DOUBLE, INT)'
    var primTypeDV1115: A = funIntFloat(d1, 42.5f)      //## issuekeys: 'FUNINTFLOAT(FLOAT, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.CASE1' CANNOT BE APPLIED TO '(DOUBLE, FLOAT)'
    var primTypeDV1116: A = funIntFloat(d1, 100L)      //## issuekeys: 'FUNINTFLOAT(FLOAT, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.CASE1' CANNOT BE APPLIED TO '(DOUBLE, LONG)'
    var primTypeDV1117: A = funIntFloat(d1, d2)      //## issuekeys: 'FUNINTFLOAT(FLOAT, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.CASE1' CANNOT BE APPLIED TO '(DOUBLE, DOUBLE)'

    var primTypeDV2111: B = funIntFloat(d1, 'c')      //## issuekeys: 'FUNINTFLOAT(FLOAT, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.CASE1' CANNOT BE APPLIED TO '(DOUBLE, CHAR)'
    var primTypeDV2112: B = funIntFloat(d1, 1b)      //## issuekeys: 'FUNINTFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.CASE1' CANNOT BE APPLIED TO '(DOUBLE, BYTE)'
    var primTypeDV2113: B = funIntFloat(d1, 1s)      //## issuekeys: 'FUNINTFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.CASE1' CANNOT BE APPLIED TO '(DOUBLE, SHORT)'
    var primTypeDV2114: B = funIntFloat(d1, 42)      //## issuekeys: 'FUNINTFLOAT(INT, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.CASE1' CANNOT BE APPLIED TO '(DOUBLE, INT)'
    var primTypeDV2115: B = funIntFloat(d1, 42.5f)      //## issuekeys: 'FUNINTFLOAT(FLOAT, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.CASE1' CANNOT BE APPLIED TO '(DOUBLE, FLOAT)'
    var primTypeDV2116: B = funIntFloat(d1, 100L)      //## issuekeys: 'FUNINTFLOAT(FLOAT, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.CASE1' CANNOT BE APPLIED TO '(DOUBLE, LONG)'
    var primTypeDV2117: B = funIntFloat(d1, d2)      //## issuekeys: 'FUNINTFLOAT(FLOAT, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.ERRANT_INTFLOAT.CASE1' CANNOT BE APPLIED TO '(DOUBLE, DOUBLE)'

  }
}