package gw.specContrib.classes.method_Scoring.primitive_Types

class Errant_IntLongDoubleMethods {
  class A {
  }

  class B {
  }

  class C {
  }

  function funIntLongDouble(i: int, j: int): A {
    return null
  }

  function funIntLongDouble(i: long, j: long): B {
    return null
  }

  function funIntLongDouble(i: double, j: double): C {
    return null
  }

  var d1: double = 42.5
  var d2: double = 43.5

  function caller() {
    //char
    //IDE-1391 for (char, char) - there should not be any error here. Call should go to (int, int).
    // Fixed for OS Gosu. Pending for Parser
    var primTypeC1111: A = funIntLongDouble('c', 'c')
    var primTypeC1112: A = funIntLongDouble('c', 1b)
    var primTypeC1113: A = funIntLongDouble('c', 1s)
    var primTypeC1114: A = funIntLongDouble('c', 42)
    var primTypeC1115: A = funIntLongDouble('c', 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeC1116: A = funIntLongDouble('c', 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeC1117: A = funIntLongDouble('c', 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeC1118: A = funIntLongDouble('c', d1)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'

    var primTypeC2111: B = funIntLongDouble('c', 'c')      //## issuekeys: AMBIGUOUS METHOD CALL: BOTH 'CASE1.FUNINTLONGDOUBLE(INT, INT)' AND 'CASE1.FUNINTLONGDOUBLE(LONG, LONG)' MATCH
    var primTypeC2112: B = funIntLongDouble('c', 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeC2113: B = funIntLongDouble('c', 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeC2114: B = funIntLongDouble('c', 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeC2115: B = funIntLongDouble('c', 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeC2116: B = funIntLongDouble('c', 100L)
    var primTypeC2117: B = funIntLongDouble('c', 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeC2118: B = funIntLongDouble('c', d1)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'

    var primTypeC3111: C = funIntLongDouble('c', 'c')      //## issuekeys: AMBIGUOUS METHOD CALL: BOTH 'CASE1.FUNINTLONGDOUBLE(INT, INT)' AND 'CASE1.FUNINTLONGDOUBLE(LONG, LONG)' MATCH
    var primTypeC3112: C = funIntLongDouble('c', 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C'
    var primTypeC3113: C = funIntLongDouble('c', 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C'
    var primTypeC3114: C = funIntLongDouble('c', 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C'
    var primTypeC3115: C = funIntLongDouble('c', 42.5f)
    var primTypeC3116: C = funIntLongDouble('c', 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C'
    var primTypeC3117: C = funIntLongDouble('c', 42.5)
    var primTypeC3118: C = funIntLongDouble('c', d1)

    var primTypeC4111 = funIntLongDouble('c', 'c')
    var primTypeC4112 = funIntLongDouble('c', 1b)
    var primTypeC4113 = funIntLongDouble('c', 1s)
    var primTypeC4114 = funIntLongDouble('c', 42)
    var primTypeC4115 = funIntLongDouble('c', 42.5f)
    var primTypeC4116 = funIntLongDouble('c', 100L)
    var primTypeC4117 = funIntLongDouble('c', 42.5)
    var primTypeC4118 = funIntLongDouble('c', d1)

    //byte
    var primTypeB1111: A = funIntLongDouble(1b, 'c')
    var primTypeB1112: A = funIntLongDouble(1b, 1b)
    var primTypeB1113: A = funIntLongDouble(1b, 1s)
    var primTypeB1114: A = funIntLongDouble(1b, 42)
    var primTypeB1115: A = funIntLongDouble(1b, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeB1116: A = funIntLongDouble(1b, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeB1117: A = funIntLongDouble(1b, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeB1118: A = funIntLongDouble(1b, d1)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'

    var primTypeB2111: B = funIntLongDouble(1b, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeB2112: B = funIntLongDouble(1b, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeB2113: B = funIntLongDouble(1b, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeB2114: B = funIntLongDouble(1b, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeB2115: B = funIntLongDouble(1b, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeB2116: B = funIntLongDouble(1b, 100L)
    var primTypeB2117: B = funIntLongDouble(1b, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeB2118: B = funIntLongDouble(1b, d1)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'

    var primTypeB3111: C = funIntLongDouble(1b, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C'
    var primTypeB3112: C = funIntLongDouble(1b, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C'
    var primTypeB3113: C = funIntLongDouble(1b, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C'
    var primTypeB3114: C = funIntLongDouble(1b, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C'
    var primTypeB3115: C = funIntLongDouble(1b, 42.5f)
    var primTypeB3116: C = funIntLongDouble(1b, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C'
    var primTypeB3117: C = funIntLongDouble(1b, 42.5)
    var primTypeB3118: C = funIntLongDouble(1b, d1)

    var primTypeB4111 = funIntLongDouble(1b, 'c')
    var primTypeB4112 = funIntLongDouble(1b, 1b)
    var primTypeB4113 = funIntLongDouble(1b, 1s)
    var primTypeB4114 = funIntLongDouble(1b, 42)
    var primTypeB4115 = funIntLongDouble(1b, 42.5f)
    var primTypeB4116 = funIntLongDouble(1b, 100L)
    var primTypeB4117 = funIntLongDouble(1b, 42.5)
    var primTypeB4118 = funIntLongDouble(1b, d1)

    //short
    var primTypeS1111: A = funIntLongDouble(1s, 'c')
    var primTypeS1112: A = funIntLongDouble(1s, 1b)
    var primTypeS1113: A = funIntLongDouble(1s, 1s)
    var primTypeS1114: A = funIntLongDouble(1s, 42)
    var primTypeS1115: A = funIntLongDouble(1s, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeS1116: A = funIntLongDouble(1s, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeS1117: A = funIntLongDouble(1s, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeS1118: A = funIntLongDouble(1s, d1)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'

    var primTypeS2111: B = funIntLongDouble(1s, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeS2112: B = funIntLongDouble(1s, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeS2113: B = funIntLongDouble(1s, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeS2114: B = funIntLongDouble(1s, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeS2115: B = funIntLongDouble(1s, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeS2116: B = funIntLongDouble(1s, 100L)
    var primTypeS2117: B = funIntLongDouble(1s, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeS2118: B = funIntLongDouble(1s, d1)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'

    var primTypeS3111: C = funIntLongDouble(1s, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C'
    var primTypeS3112: C = funIntLongDouble(1s, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C'
    var primTypeS3113: C = funIntLongDouble(1s, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C'
    var primTypeS3114: C = funIntLongDouble(1s, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C'
    var primTypeS3115: C = funIntLongDouble(1s, 42.5f)
    var primTypeS3116: C = funIntLongDouble(1s, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C'
    var primTypeS3117: C = funIntLongDouble(1s, 42.5)
    var primTypeS3118: C = funIntLongDouble(1s, d1)

    var primTypeS4111 = funIntLongDouble(1s, 'c')
    var primTypeS4112 = funIntLongDouble(1s, 1b)
    var primTypeS4113 = funIntLongDouble(1s, 1s)
    var primTypeS4114 = funIntLongDouble(1s, 42)
    var primTypeS4115 = funIntLongDouble(1s, 42.5f)
    var primTypeS4116 = funIntLongDouble(1s, 100L)
    var primTypeS4117 = funIntLongDouble(1s, 42.5)
    var primTypeS4118 = funIntLongDouble(1s, d1)

    //int
    var primTypeI1111: A = funIntLongDouble(42, 'c')
    var primTypeI1112: A = funIntLongDouble(42, 1b)
    var primTypeI1113: A = funIntLongDouble(42, 1s)
    var primTypeI1114: A = funIntLongDouble(42, 42)
    var primTypeI1115: A = funIntLongDouble(42, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeI1116: A = funIntLongDouble(42, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeI1117: A = funIntLongDouble(42, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeI1118: A = funIntLongDouble(42, d1)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'

    var primTypeI2111: B = funIntLongDouble(42, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeI2112: B = funIntLongDouble(42, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeI2113: B = funIntLongDouble(42, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeI2114: B = funIntLongDouble(42, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeI2115: B = funIntLongDouble(42, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeI2116: B = funIntLongDouble(42, 100L)
    var primTypeI2117: B = funIntLongDouble(42, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeI2118: B = funIntLongDouble(42, d1)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'

    var primTypeI3111: C = funIntLongDouble(42, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C'
    var primTypeI3112: C = funIntLongDouble(42, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C'
    var primTypeI3113: C = funIntLongDouble(42, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C'
    var primTypeI3114: C = funIntLongDouble(42, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C'
    var primTypeI3115: C = funIntLongDouble(42, 42.5f)
    var primTypeI3116: C = funIntLongDouble(42, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C'
    var primTypeI3117: C = funIntLongDouble(42, 42.5)
    var primTypeI3118: C = funIntLongDouble(42, d1)

    var primTypeI4111 = funIntLongDouble(42, 'c')
    var primTypeI4112 = funIntLongDouble(42, 1b)
    var primTypeI4113 = funIntLongDouble(42, 1s)
    var primTypeI4114 = funIntLongDouble(42, 42)
    var primTypeI4115 = funIntLongDouble(42, 42.5f)
    var primTypeI4116 = funIntLongDouble(42, 100L)
    var primTypeI4117 = funIntLongDouble(42, 42.5)
    var primTypeI4118 = funIntLongDouble(42, d1)

    //float
    var primTypeF1111: A = funIntLongDouble(42.5f, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeF1112: A = funIntLongDouble(42.5f, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeF1113: A = funIntLongDouble(42.5f, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeF1114: A = funIntLongDouble(42.5f, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeF1115: A = funIntLongDouble(42.5f, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeF1116: A = funIntLongDouble(42.5f, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeF1117: A = funIntLongDouble(42.5f, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeF1118: A = funIntLongDouble(42.5f, d1)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'

    var primTypeF2111: B = funIntLongDouble(42.5f, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeF2112: B = funIntLongDouble(42.5f, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeF2113: B = funIntLongDouble(42.5f, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeF2114: B = funIntLongDouble(42.5f, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeF2115: B = funIntLongDouble(42.5f, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeF2116: B = funIntLongDouble(42.5f, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeF2117: B = funIntLongDouble(42.5f, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeF2118: B = funIntLongDouble(42.5f, d1)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'

    var primTypeF3111: C = funIntLongDouble(42.5f, 'c')
    var primTypeF3112: C = funIntLongDouble(42.5f, 1b)
    var primTypeF3113: C = funIntLongDouble(42.5f, 1s)
    var primTypeF3114: C = funIntLongDouble(42.5f, 42)
    var primTypeF3115: C = funIntLongDouble(42.5f, 42.5f)
    var primTypeF3116: C = funIntLongDouble(42.5f, 100L)
    var primTypeF3117: C = funIntLongDouble(42.5f, 42.5)
    var primTypeF3118: C = funIntLongDouble(42.5f, d1)

    var primTypeF4111 = funIntLongDouble(42.5f, 'c')
    var primTypeF4112 = funIntLongDouble(42.5f, 1b)
    var primTypeF4113 = funIntLongDouble(42.5f, 1s)
    var primTypeF4114 = funIntLongDouble(42.5f, 42)
    var primTypeF4115 = funIntLongDouble(42.5f, 42.5f)
    var primTypeF4116 = funIntLongDouble(42.5f, 100L)
    var primTypeF4117 = funIntLongDouble(42.5f, 42.5)
    var primTypeF4118 = funIntLongDouble(42.5f, d1)

    //long
    var primTypeL1111: A = funIntLongDouble(100L, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeL1112: A = funIntLongDouble(100L, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeL1113: A = funIntLongDouble(100L, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeL1114: A = funIntLongDouble(100L, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeL1115: A = funIntLongDouble(100L, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeL1116: A = funIntLongDouble(100L, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeL1117: A = funIntLongDouble(100L, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeL1118: A = funIntLongDouble(100L, d1)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'

    var primTypeL2111: B = funIntLongDouble(100L, 'c')
    var primTypeL2112: B = funIntLongDouble(100L, 1b)
    var primTypeL2113: B = funIntLongDouble(100L, 1s)
    var primTypeL2114: B = funIntLongDouble(100L, 42)
    var primTypeL2115: B = funIntLongDouble(100L, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeL2116: B = funIntLongDouble(100L, 100L)
    var primTypeL2117: B = funIntLongDouble(100L, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeL2118: B = funIntLongDouble(100L, d1)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'

    var primTypeL3111: C = funIntLongDouble(100L, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C'
    var primTypeL3112: C = funIntLongDouble(100L, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C'
    var primTypeL3113: C = funIntLongDouble(100L, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C'
    var primTypeL3114: C = funIntLongDouble(100L, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C'
    var primTypeL3115: C = funIntLongDouble(100L, 42.5f)
    var primTypeL3116: C = funIntLongDouble(100L, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C'
    var primTypeL3117: C = funIntLongDouble(100L, 42.5)
    var primTypeL3118: C = funIntLongDouble(100L, d1)

    var primTypeL4111 = funIntLongDouble(100L, 'c')
    var primTypeL4112 = funIntLongDouble(100L, 1b)
    var primTypeL4113 = funIntLongDouble(100L, 1s)
    var primTypeL4114 = funIntLongDouble(100L, 42)
    var primTypeL4115 = funIntLongDouble(100L, 42.5f)
    var primTypeL4116 = funIntLongDouble(100L, 100L)
    var primTypeL4117 = funIntLongDouble(100L, 42.5)
    var primTypeL4118 = funIntLongDouble(100L, d1)

    //double
    var primTypeD1111: A = funIntLongDouble(42.5, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeD1112: A = funIntLongDouble(42.5, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeD1113: A = funIntLongDouble(42.5, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeD1114: A = funIntLongDouble(42.5, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeD1115: A = funIntLongDouble(42.5, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeD1116: A = funIntLongDouble(42.5, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeD1117: A = funIntLongDouble(42.5, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeD1118: A = funIntLongDouble(42.5, d1)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'

    var primTypeD2111: B = funIntLongDouble(42.5, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeD2112: B = funIntLongDouble(42.5, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeD2113: B = funIntLongDouble(42.5, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeD2114: B = funIntLongDouble(42.5, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeD2115: B = funIntLongDouble(42.5, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeD2116: B = funIntLongDouble(42.5, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeD2117: B = funIntLongDouble(42.5, 42.5)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeD2118: B = funIntLongDouble(42.5, d1)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'

    var primTypeD3111: C = funIntLongDouble(42.5, 'c')
    var primTypeD3112: C = funIntLongDouble(42.5, 1b)
    var primTypeD3113: C = funIntLongDouble(42.5, 1s)
    var primTypeD3114: C = funIntLongDouble(42.5, 42)
    var primTypeD3115: C = funIntLongDouble(42.5, 42.5f)
    var primTypeD3116: C = funIntLongDouble(42.5, 100L)
    var primTypeD3117: C = funIntLongDouble(42.5, 42.5)
    var primTypeD3118: C = funIntLongDouble(42.5, d1)

    var primTypeD4111 = funIntLongDouble(42.5, 'c')
    var primTypeD4112 = funIntLongDouble(42.5, 1b)
    var primTypeD4113 = funIntLongDouble(42.5, 1s)
    var primTypeD4114 = funIntLongDouble(42.5, 42)
    var primTypeD4115 = funIntLongDouble(42.5, 42.5f)
    var primTypeD4116 = funIntLongDouble(42.5, 100L)
    var primTypeD4117 = funIntLongDouble(42.5, 42.5)
    var primTypeD4118 = funIntLongDouble(42.5, d1)

    //Double extracted as a variable
    var primTypeDV1111: A = funIntLongDouble(d1, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeDV1112: A = funIntLongDouble(d1, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeDV1113: A = funIntLongDouble(d1, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeDV1114: A = funIntLongDouble(d1, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeDV1115: A = funIntLongDouble(d1, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeDV1116: A = funIntLongDouble(d1, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'
    var primTypeDV1117: A = funIntLongDouble(d1, d2)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.A'

    var primTypeDV2111: B = funIntLongDouble(d1, 'c')      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeDV2112: B = funIntLongDouble(d1, 1b)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeDV2113: B = funIntLongDouble(d1, 1s)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeDV2114: B = funIntLongDouble(d1, 42)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeDV2115: B = funIntLongDouble(d1, 42.5f)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeDV2116: B = funIntLongDouble(d1, 100L)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'
    var primTypeDV2117: B = funIntLongDouble(d1, d2)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.C', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.PRIMITIVES_METHODSCORING.TOBEPUSHED.ERRANT_INTLONGDOUBLEMETHODS.B'

    var primTypeDV3111: C = funIntLongDouble(d1, 'c')
    var primTypeDV3112: C = funIntLongDouble(d1, 1b)
    var primTypeDV3113: C = funIntLongDouble(d1, 1s)
    var primTypeDV3114: C = funIntLongDouble(d1, 42)
    var primTypeDV3115: C = funIntLongDouble(d1, 42.5f)
    var primTypeDV3116: C = funIntLongDouble(d1, 100L)
    var primTypeDV3117: C = funIntLongDouble(d1, d2)

    var primTypeDV4111 = funIntLongDouble(d1, 'c')
    var primTypeDV4112 = funIntLongDouble(d1, 1b)
    var primTypeDV4113 = funIntLongDouble(d1, 1s)
    var primTypeDV4114 = funIntLongDouble(d1, 42)
    var primTypeDV4115 = funIntLongDouble(d1, 42.5f)
    var primTypeDV4116 = funIntLongDouble(d1, 100L)
    var primTypeDV4117 = funIntLongDouble(d1, d2)


  }
}