package gw.internal.schema.gw.xsd.w3c.wsdl.types.complex;

/***************************************************************************/
/* THIS IS AUTOGENERATED CODE - DO NOT MODIFY OR YOUR CHANGES WILL BE LOST */
/* THIS CODE CAN BE REGENERATED USING 'xsd-codegen'                        */
/***************************************************************************/
public class TDefinitions extends gw.internal.schema.gw.xsd.w3c.wsdl.types.complex.TExtensibleDocumented implements gw.internal.xml.IXmlGeneratedClass {

  public static final javax.xml.namespace.QName $ATTRIBUTE_QNAME_Name = new javax.xml.namespace.QName( "", "name", "" );
  public static final javax.xml.namespace.QName $ATTRIBUTE_QNAME_TargetNamespace = new javax.xml.namespace.QName( "", "targetNamespace", "" );
  public static final javax.xml.namespace.QName $ELEMENT_QNAME_Binding = new javax.xml.namespace.QName( "http://schemas.xmlsoap.org/wsdl/", "binding", "wsdl" );
  public static final javax.xml.namespace.QName $ELEMENT_QNAME_Documentation = new javax.xml.namespace.QName( "http://schemas.xmlsoap.org/wsdl/", "documentation", "wsdl" );
  public static final javax.xml.namespace.QName $ELEMENT_QNAME_Import = new javax.xml.namespace.QName( "http://schemas.xmlsoap.org/wsdl/", "import", "wsdl" );
  public static final javax.xml.namespace.QName $ELEMENT_QNAME_Message = new javax.xml.namespace.QName( "http://schemas.xmlsoap.org/wsdl/", "message", "wsdl" );
  public static final javax.xml.namespace.QName $ELEMENT_QNAME_PortType = new javax.xml.namespace.QName( "http://schemas.xmlsoap.org/wsdl/", "portType", "wsdl" );
  public static final javax.xml.namespace.QName $ELEMENT_QNAME_Service = new javax.xml.namespace.QName( "http://schemas.xmlsoap.org/wsdl/", "service", "wsdl" );
  public static final javax.xml.namespace.QName $ELEMENT_QNAME_Types = new javax.xml.namespace.QName( "http://schemas.xmlsoap.org/wsdl/", "types", "wsdl" );
  public static final javax.xml.namespace.QName $QNAME = new javax.xml.namespace.QName( "http://schemas.xmlsoap.org/wsdl/", "tDefinitions", "wsdl" );
  public static final gw.util.concurrent.LockingLazyVar<gw.lang.reflect.IType> TYPE = new gw.util.concurrent.LockingLazyVar<gw.lang.reflect.IType>( gw.lang.reflect.TypeSystem.getGlobalLock() ) {
          @Override
          protected gw.lang.reflect.IType init() {
            return gw.lang.reflect.TypeSystem.getByFullName( "gw.xsd.w3c.wsdl.types.complex.TDefinitions" );
          }
        };
  private static final gw.util.concurrent.LockingLazyVar<java.lang.Object> SCHEMAINFO = new gw.util.concurrent.LockingLazyVar<java.lang.Object>( gw.lang.reflect.TypeSystem.getGlobalLock() ) {
          @Override
          protected java.lang.Object init() {
            gw.lang.reflect.IType type = TYPE.get();
            return getSchemaInfoByType( type );
          }
        };

  public TDefinitions() {
    super( TYPE.get(), SCHEMAINFO.get() );
  }

  protected TDefinitions( gw.lang.reflect.IType type, java.lang.Object schemaInfo ) {
    super( type, schemaInfo );
  }


  public java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_Binding> Binding() {
    //noinspection unchecked
    return (java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_Binding>) TYPE.get().getTypeInfo().getProperty( "Binding" ).getAccessor().getValue( this );
  }

  public void setBinding$( java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_Binding> param ) {
    TYPE.get().getTypeInfo().getProperty( "Binding" ).getAccessor().setValue( this, param );
  }


  public gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDocumented_Documentation Documentation() {
    return (gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDocumented_Documentation) TYPE.get().getTypeInfo().getProperty( "Documentation" ).getAccessor().getValue( this );
  }

  public void setDocumentation$( gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDocumented_Documentation param ) {
    TYPE.get().getTypeInfo().getProperty( "Documentation" ).getAccessor().setValue( this, param );
  }


  public java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_Import> Import() {
    //noinspection unchecked
    return (java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_Import>) TYPE.get().getTypeInfo().getProperty( "Import" ).getAccessor().getValue( this );
  }

  public void setImport$( java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_Import> param ) {
    TYPE.get().getTypeInfo().getProperty( "Import" ).getAccessor().setValue( this, param );
  }


  public java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_Message> Message() {
    //noinspection unchecked
    return (java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_Message>) TYPE.get().getTypeInfo().getProperty( "Message" ).getAccessor().getValue( this );
  }

  public void setMessage$( java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_Message> param ) {
    TYPE.get().getTypeInfo().getProperty( "Message" ).getAccessor().setValue( this, param );
  }


  public java.lang.String Name() {
    return (java.lang.String) TYPE.get().getTypeInfo().getProperty( "Name" ).getAccessor().getValue( this );
  }

  public void setName$( java.lang.String param ) {
    TYPE.get().getTypeInfo().getProperty( "Name" ).getAccessor().setValue( this, param );
  }


  public java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_PortType> PortType() {
    //noinspection unchecked
    return (java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_PortType>) TYPE.get().getTypeInfo().getProperty( "PortType" ).getAccessor().getValue( this );
  }

  public void setPortType$( java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_PortType> param ) {
    TYPE.get().getTypeInfo().getProperty( "PortType" ).getAccessor().setValue( this, param );
  }


  public java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_Service> Service() {
    //noinspection unchecked
    return (java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_Service>) TYPE.get().getTypeInfo().getProperty( "Service" ).getAccessor().getValue( this );
  }

  public void setService$( java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_Service> param ) {
    TYPE.get().getTypeInfo().getProperty( "Service" ).getAccessor().setValue( this, param );
  }


  public java.net.URI TargetNamespace() {
    return (java.net.URI) TYPE.get().getTypeInfo().getProperty( "TargetNamespace" ).getAccessor().getValue( this );
  }

  public void setTargetNamespace$( java.net.URI param ) {
    TYPE.get().getTypeInfo().getProperty( "TargetNamespace" ).getAccessor().setValue( this, param );
  }


  public java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_Types> Types() {
    //noinspection unchecked
    return (java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_Types>) TYPE.get().getTypeInfo().getProperty( "Types" ).getAccessor().getValue( this );
  }

  public void setTypes$( java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_Types> param ) {
    TYPE.get().getTypeInfo().getProperty( "Types" ).getAccessor().setValue( this, param );
  }

  @SuppressWarnings( {"UnusedDeclaration"} )
  private static final long FINGERPRINT = -6050492648119042255L;

}
