package gw.specContrib.classes.enhancements

enhancement Errant_EnhancementSymbolNameCollision2<B>: Errant_EnhancementSymbolNameCollision<B> {

  private function privateFunction(b: B) {}
  protected function protectedFunction(b: B) {}      //## issuekeys: THE FUNCTION 'PROTECTEDFUNCTION(B)' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.CLASSES.ENHANCEMENT.ERRANT_ENHANCEMENTSYMBOLNAMECOLLISION'. ENHANCEMENTS CANNOT OVERRIDE FUNCTIONS.
  internal function internalFunction(b: B) {}      //## issuekeys: THE FUNCTION 'INTERNALFUNCTION(B)' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.CLASSES.ENHANCEMENT.ERRANT_ENHANCEMENTSYMBOLNAMECOLLISION'. ENHANCEMENTS CANNOT OVERRIDE FUNCTIONS.
  public function publicFunction(b: B) {}      //## issuekeys: THE FUNCTION 'PUBLICFUNCTION(B)' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.CLASSES.ENHANCEMENT.ERRANT_ENHANCEMENTSYMBOLNAMECOLLISION'. ENHANCEMENTS CANNOT OVERRIDE FUNCTIONS.

  private property set PrivateProperty(b: B) {}
  protected property set ProtectedProperty(b: B) {}      //## issuekeys: THE FUNCTION 'SETPROTECTEDPROPERTY(B)' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.CLASSES.ENHANCEMENT.ERRANT_ENHANCEMENTSYMBOLNAMECOLLISION'. ENHANCEMENTS CANNOT OVERRIDE FUNCTIONS.
  internal property set InternalProperty(b: B) {}      //## issuekeys: THE FUNCTION 'SETINTERNALPROPERTY(B)' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.CLASSES.ENHANCEMENT.ERRANT_ENHANCEMENTSYMBOLNAMECOLLISION'. ENHANCEMENTS CANNOT OVERRIDE FUNCTIONS.
  public property set PublicProperty(b: B) {}      //## issuekeys: THE FUNCTION 'SETPUBLICPROPERTY(B)' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.CLASSES.ENHANCEMENT.ERRANT_ENHANCEMENTSYMBOLNAMECOLLISION'. ENHANCEMENTS CANNOT OVERRIDE FUNCTIONS.

}
