package gw.specContrib.structural

class Errant_ParameterizedStructures {
  class A{}
  class B extends A{}
  class C extends A{}
  class D extends B{}

  structure MyStructure1<T extends B, T2 extends B> {
    function funOne(t: T) : T
  }

  class MyClass1<E > {
    function funOne(t : E) : E {return null}
  }

  function test1() {
    var mystructure1: MyStructure1 = new MyClass1<B>()
    var mystructure2: MyStructure1 = new MyClass1<D>()      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.STRUCTURALTYPING.GENERICS.ERRANT_PARAMETERIZEDSTRUCTURES.MYCLASS1<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.STRUCTURALTYPING.GENERICS.ERRANT_PARAMETERIZEDSTRUCTURES.D>', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.STRUCTURALTYPING.GENERICS.ERRANT_PARAMETERIZEDSTRUCTURES.MYSTRUCTURE1'
    var mystructure3: MyStructure1 = new MyClass1<A>()      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.STRUCTURALTYPING.GENERICS.ERRANT_PARAMETERIZEDSTRUCTURES.MYCLASS1<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.STRUCTURALTYPING.GENERICS.ERRANT_PARAMETERIZEDSTRUCTURES.A>', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.STRUCTURALTYPING.GENERICS.ERRANT_PARAMETERIZEDSTRUCTURES.MYSTRUCTURE1'


  }

  structure MyStructure2<T1 extends B, T2 extends D> {
    function funOne(t: T1) : T2
  }

  class MyClass2<E, F > {
    function funOne(t : E) : F {return null}
  }

  function main() {
    var mystructure1: MyStructure2 = new MyClass2<B, B>()      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.STRUCTURALTYPING.GENERICS.ERRANT_PARAMETERIZEDSTRUCTURES.MYCLASS2<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.STRUCTURALTYPING.GENERICS.ERRANT_PARAMETERIZEDSTRUCTURES.B,GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.STRUCTURALTYPING.GENERICS.ERRANT_PARAMETERIZEDSTRUCTURES.B>', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.STRUCTURALTYPING.GENERICS.ERRANT_PARAMETERIZEDSTRUCTURES.MYSTRUCTURE2'
    var mystructure2: MyStructure2 = new MyClass2<B, D>()
    var mystructure3: MyStructure2 = new MyClass2<D, B>()      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.STRUCTURALTYPING.GENERICS.ERRANT_PARAMETERIZEDSTRUCTURES.MYCLASS2<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.STRUCTURALTYPING.GENERICS.ERRANT_PARAMETERIZEDSTRUCTURES.D,GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.STRUCTURALTYPING.GENERICS.ERRANT_PARAMETERIZEDSTRUCTURES.B>', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.STRUCTURALTYPING.GENERICS.ERRANT_PARAMETERIZEDSTRUCTURES.MYSTRUCTURE2'
    var mystructure4: MyStructure2 = new MyClass2<D, D>()      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.STRUCTURALTYPING.GENERICS.ERRANT_PARAMETERIZEDSTRUCTURES.MYCLASS2<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.STRUCTURALTYPING.GENERICS.ERRANT_PARAMETERIZEDSTRUCTURES.D,GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.STRUCTURALTYPING.GENERICS.ERRANT_PARAMETERIZEDSTRUCTURES.D>', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.STRUCTURALTYPING.GENERICS.ERRANT_PARAMETERIZEDSTRUCTURES.MYSTRUCTURE2'


  }
}