package gw.specContrib.classes.enhancements.shadowingMore.gosuVsGosu.propertiesVsProperties

enhancement Errant_ShadowingGosuPropertiesWithPropertiesInEnhancements: Errant_GosuPropertiesVsProperties {
  //properties in class being shadowed by properties in enhancement
  property get Prop1(): String {      //## issuekeys: THE FUNCTION 'GETPROP1()' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVAINTERACTION.SHADOWING.GOSUVSGOSU.PROPERTIESVSPROPERTIES.ERRANT_GOSUPROPERTIESVSPROPERTIES'. ENHANCEMENTS CANNOT OVERRIDE FUNCTIONS.
    return null
  }

  property get Prop2(): String {
    return null
  }

  property get Prop3(): String {      //## issuekeys: THE FUNCTION 'GETPROP3()' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVAINTERACTION.SHADOWING.GOSUVSGOSU.PROPERTIESVSPROPERTIES.ERRANT_GOSUPROPERTIESVSPROPERTIES'. ENHANCEMENTS CANNOT OVERRIDE FUNCTIONS.
    return null
  }

  property get Prop4(): String {      //## issuekeys: THE FUNCTION 'GETPROP4()' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVAINTERACTION.SHADOWING.GOSUVSGOSU.PROPERTIESVSPROPERTIES.ERRANT_GOSUPROPERTIESVSPROPERTIES'. ENHANCEMENTS CANNOT OVERRIDE FUNCTIONS.
    return null
  }

  property set Prop1(str1: String) {      //## issuekeys: THE FUNCTION 'SETPROP1(STRING)' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVAINTERACTION.SHADOWING.GOSUVSGOSU.PROPERTIESVSPROPERTIES.ERRANT_GOSUPROPERTIESVSPROPERTIES'. ENHANCEMENTS CANNOT OVERRIDE FUNCTIONS.
  }

  property set Prop2(str2: String) {
  }

  property set Prop3(str3: String) {      //## issuekeys: THE FUNCTION 'SETPROP3(STRING)' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVAINTERACTION.SHADOWING.GOSUVSGOSU.PROPERTIESVSPROPERTIES.ERRANT_GOSUPROPERTIESVSPROPERTIES'. ENHANCEMENTS CANNOT OVERRIDE FUNCTIONS.
  }

  property set Prop4(str4: String) {      //## issuekeys: THE FUNCTION 'SETPROP4(STRING)' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVAINTERACTION.SHADOWING.GOSUVSGOSU.PROPERTIESVSPROPERTIES.ERRANT_GOSUPROPERTIESVSPROPERTIES'. ENHANCEMENTS CANNOT OVERRIDE FUNCTIONS.
  }

}
