package gw.internal.schema.gw.xsd.w3c.xmlschema.anonymous.types.complex;

/***************************************************************************/
/* THIS IS AUTOGENERATED CODE - DO NOT MODIFY OR YOUR CHANGES WILL BE LOST */
/* THIS CODE CAN BE REGENERATED USING 'xsd-codegen'                        */
/***************************************************************************/
public class Any extends gw.internal.schema.gw.xsd.w3c.xmlschema.types.complex.Wildcard implements gw.internal.xml.IXmlGeneratedClass {

  public static final javax.xml.namespace.QName $ATTRIBUTE_QNAME_Id = new javax.xml.namespace.QName( "", "id", "" );
  public static final javax.xml.namespace.QName $ATTRIBUTE_QNAME_MaxOccurs = new javax.xml.namespace.QName( "", "maxOccurs", "" );
  public static final javax.xml.namespace.QName $ATTRIBUTE_QNAME_MinOccurs = new javax.xml.namespace.QName( "", "minOccurs", "" );
  public static final javax.xml.namespace.QName $ATTRIBUTE_QNAME_Namespace = new javax.xml.namespace.QName( "", "namespace", "" );
  public static final javax.xml.namespace.QName $ATTRIBUTE_QNAME_ProcessContents = new javax.xml.namespace.QName( "", "processContents", "" );
  public static final javax.xml.namespace.QName $ELEMENT_QNAME_Annotation = new javax.xml.namespace.QName( "http://www.w3.org/2001/XMLSchema", "annotation", "xs" );
  public static final gw.util.concurrent.LockingLazyVar<gw.lang.reflect.IType> TYPE = new gw.util.concurrent.LockingLazyVar<gw.lang.reflect.IType>( gw.lang.reflect.TypeSystem.getGlobalLock() ) {
          @Override
          protected gw.lang.reflect.IType init() {
            return gw.lang.reflect.TypeSystem.getByFullName( "gw.xsd.w3c.xmlschema.anonymous.types.complex.Any" );
          }
        };
  private static final gw.util.concurrent.LockingLazyVar<java.lang.Object> SCHEMAINFO = new gw.util.concurrent.LockingLazyVar<java.lang.Object>( gw.lang.reflect.TypeSystem.getGlobalLock() ) {
          @Override
          protected java.lang.Object init() {
            gw.lang.reflect.IType type = TYPE.get();
            return getSchemaInfoByType( type );
          }
        };

  public Any() {
    super( TYPE.get(), SCHEMAINFO.get() );
  }

  protected Any( gw.lang.reflect.IType type, java.lang.Object schemaInfo ) {
    super( type, schemaInfo );
  }


  public gw.internal.schema.gw.xsd.w3c.xmlschema.Annotation Annotation() {
    return (gw.internal.schema.gw.xsd.w3c.xmlschema.Annotation) TYPE.get().getTypeInfo().getProperty( "Annotation" ).getAccessor().getValue( this );
  }

  public void setAnnotation$( gw.internal.schema.gw.xsd.w3c.xmlschema.Annotation param ) {
    TYPE.get().getTypeInfo().getProperty( "Annotation" ).getAccessor().setValue( this, param );
  }


  public java.lang.String Id() {
    return (java.lang.String) TYPE.get().getTypeInfo().getProperty( "Id" ).getAccessor().getValue( this );
  }

  public void setId$( java.lang.String param ) {
    TYPE.get().getTypeInfo().getProperty( "Id" ).getAccessor().setValue( this, param );
  }


  public java.lang.String MaxOccurs() {
    return (java.lang.String) TYPE.get().getTypeInfo().getProperty( "MaxOccurs" ).getAccessor().getValue( this );
  }

  public void setMaxOccurs$( java.lang.String param ) {
    TYPE.get().getTypeInfo().getProperty( "MaxOccurs" ).getAccessor().setValue( this, param );
  }


  public java.math.BigInteger MinOccurs() {
    return (java.math.BigInteger) TYPE.get().getTypeInfo().getProperty( "MinOccurs" ).getAccessor().getValue( this );
  }

  public void setMinOccurs$( java.math.BigInteger param ) {
    TYPE.get().getTypeInfo().getProperty( "MinOccurs" ).getAccessor().setValue( this, param );
  }


  public java.lang.String Namespace() {
    return (java.lang.String) TYPE.get().getTypeInfo().getProperty( "Namespace" ).getAccessor().getValue( this );
  }

  public void setNamespace$( java.lang.String param ) {
    TYPE.get().getTypeInfo().getProperty( "Namespace" ).getAccessor().setValue( this, param );
  }


  public gw.internal.schema.gw.xsd.w3c.xmlschema.enums.Wildcard_ProcessContents ProcessContents() {
    return (gw.internal.schema.gw.xsd.w3c.xmlschema.enums.Wildcard_ProcessContents) TYPE.get().getTypeInfo().getProperty( "ProcessContents" ).getAccessor().getValue( this );
  }

  public void setProcessContents$( gw.internal.schema.gw.xsd.w3c.xmlschema.enums.Wildcard_ProcessContents param ) {
    TYPE.get().getTypeInfo().getProperty( "ProcessContents" ).getAccessor().setValue( this, param );
  }

  @SuppressWarnings( {"UnusedDeclaration"} )
  private static final long FINGERPRINT = 2110283714877373226L;

}
