package gw.specContrib.classes.enhancements.shadowingMore.gosuVsGosu.propertiesVsGettersSetters

enhancement Errant_ShadowingPropertiesWithGettersSetters: Errant_GosuPropertiesVsGettersSetters {
  //Shadowing properties with as keyword
  function getNameInternal(): String {      //## issuekeys: THE FUNCTION 'GETNAMEINTERNAL()' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVAINTERACTION.SHADOWING.GOSUVSGOSU.PROPERTIESVSGETTERSSETTERS.ERRANT_GOSUPROPERTIESVSGETTERSSETTERS'. ENHANCEMENTS CANNOT OVERRIDE FUNCTIONS.
    return null
  }

  function getNamePrivate(): String {      //## issuekeys: THE FUNCTION 'GETNAMEPRIVATE()' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVAINTERACTION.SHADOWING.GOSUVSGOSU.PROPERTIESVSGETTERSSETTERS.ERRANT_GOSUPROPERTIESVSGETTERSSETTERS'. ENHANCEMENTS CANNOT OVERRIDE FUNCTIONS.
    return null
  }

  function getNameProtected(): String {      //## issuekeys: THE FUNCTION 'GETNAMEPROTECTED()' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVAINTERACTION.SHADOWING.GOSUVSGOSU.PROPERTIESVSGETTERSSETTERS.ERRANT_GOSUPROPERTIESVSGETTERSSETTERS'. ENHANCEMENTS CANNOT OVERRIDE FUNCTIONS.
    return null
  }

  function getNamePublic(): String {      //## issuekeys: THE FUNCTION 'GETNAMEPUBLIC()' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVAINTERACTION.SHADOWING.GOSUVSGOSU.PROPERTIESVSGETTERSSETTERS.ERRANT_GOSUPROPERTIESVSGETTERSSETTERS'. ENHANCEMENTS CANNOT OVERRIDE FUNCTIONS.
    return null
  }

  function setNameInternal(str1: String {      //## issuekeys: THE FUNCTION 'SETNAMEINTERNAL(STRING)' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVAINTERACTION.SHADOWING.GOSUVSGOSU.PROPERTIESVSGETTERSSETTERS.ERRANT_GOSUPROPERTIESVSGETTERSSETTERS'. ENHANCEMENTS CANNOT OVERRIDE FUNCTIONS.
  }

  function setNamePrivate(str2: String {      //## issuekeys: THE FUNCTION 'SETNAMEPRIVATE(STRING)' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVAINTERACTION.SHADOWING.GOSUVSGOSU.PROPERTIESVSGETTERSSETTERS.ERRANT_GOSUPROPERTIESVSGETTERSSETTERS'. ENHANCEMENTS CANNOT OVERRIDE FUNCTIONS.
  }

  function setNameProtected(str3: String {      //## issuekeys: THE FUNCTION 'SETNAMEPROTECTED(STRING)' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVAINTERACTION.SHADOWING.GOSUVSGOSU.PROPERTIESVSGETTERSSETTERS.ERRANT_GOSUPROPERTIESVSGETTERSSETTERS'. ENHANCEMENTS CANNOT OVERRIDE FUNCTIONS.
  }

  function setNamePublic(str4: String {      //## issuekeys: THE FUNCTION 'SETNAMEPUBLIC(STRING)' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVAINTERACTION.SHADOWING.GOSUVSGOSU.PROPERTIESVSGETTERSSETTERS.ERRANT_GOSUPROPERTIESVSGETTERSSETTERS'. ENHANCEMENTS CANNOT OVERRIDE FUNCTIONS.
  }

  //Shadowing properties getters/setters with function getters/setters
  function getProp1(): String {      //## issuekeys: THE FUNCTION 'GETPROP1()' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVAINTERACTION.SHADOWING.GOSUVSGOSU.PROPERTIESVSGETTERSSETTERS.ERRANT_GOSUPROPERTIESVSGETTERSSETTERS'. ENHANCEMENTS CANNOT OVERRIDE FUNCTIONS.
    return null
  }

  function getProp2(): String {
    return null
  }

  function getProp3(): String {      //## issuekeys: THE FUNCTION 'GETPROP3()' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVAINTERACTION.SHADOWING.GOSUVSGOSU.PROPERTIESVSGETTERSSETTERS.ERRANT_GOSUPROPERTIESVSGETTERSSETTERS'. ENHANCEMENTS CANNOT OVERRIDE FUNCTIONS.
    return null
  }

  function getProp4(): String {      //## issuekeys: THE FUNCTION 'GETPROP4()' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVAINTERACTION.SHADOWING.GOSUVSGOSU.PROPERTIESVSGETTERSSETTERS.ERRANT_GOSUPROPERTIESVSGETTERSSETTERS'. ENHANCEMENTS CANNOT OVERRIDE FUNCTIONS.
    return null
  }

  function setProp1(str1: String) {      //## issuekeys: THE FUNCTION 'SETPROP1(STRING)' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVAINTERACTION.SHADOWING.GOSUVSGOSU.PROPERTIESVSGETTERSSETTERS.ERRANT_GOSUPROPERTIESVSGETTERSSETTERS'. ENHANCEMENTS CANNOT OVERRIDE FUNCTIONS.
  }

  function setProp2(str2: String) {
  }

  function setProp3(str3: String) {      //## issuekeys: THE FUNCTION 'SETPROP3(STRING)' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVAINTERACTION.SHADOWING.GOSUVSGOSU.PROPERTIESVSGETTERSSETTERS.ERRANT_GOSUPROPERTIESVSGETTERSSETTERS'. ENHANCEMENTS CANNOT OVERRIDE FUNCTIONS.
  }

  function setProp4(str4: String) {      //## issuekeys: THE FUNCTION 'SETPROP4(STRING)' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVAINTERACTION.SHADOWING.GOSUVSGOSU.PROPERTIESVSGETTERSSETTERS.ERRANT_GOSUPROPERTIESVSGETTERSSETTERS'. ENHANCEMENTS CANNOT OVERRIDE FUNCTIONS.
  }
}
