package gw.specContrib.classes.enhancements.shadowingMore.gosuVsGosu.gettersSettersVsProperties

enhancement Errant_ShadowingGosuGettersSettersWithPropertiesInEnhancements: Errant_GosuGettersSettersVsProperties {
  //IDE-1200 fixed
  internal property get MethodPropInternal(): String {      //## issuekeys: THE FUNCTION 'GETMETHODPROPINTERNAL()' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVAINTERACTION.SHADOWING.GOSUVSGOSU.GETTERSSETTERSVSPROPERTIES.ERRANT_GOSUGETTERSSETTERSVSPROPERTIES'. ENHANCEMENTS CANNOT OVERRIDE FUNCTIONS.
    return null
  }

  private property get MethodPropPrivate(): String {
    return null
  }

  protected property get MethodPropProtected(): String {      //## issuekeys: THE FUNCTION 'GETMETHODPROPPROTECTED()' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVAINTERACTION.SHADOWING.GOSUVSGOSU.GETTERSSETTERSVSPROPERTIES.ERRANT_GOSUGETTERSSETTERSVSPROPERTIES'. ENHANCEMENTS CANNOT OVERRIDE FUNCTIONS.
    return null
  }

  public property get MethodPropPublic(): String {      //## issuekeys: THE FUNCTION 'GETMETHODPROPPUBLIC()' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVAINTERACTION.SHADOWING.GOSUVSGOSU.GETTERSSETTERSVSPROPERTIES.ERRANT_GOSUGETTERSSETTERSVSPROPERTIES'. ENHANCEMENTS CANNOT OVERRIDE FUNCTIONS.
    return null
  }
}
