package gw.specContrib.classes.method_Scoring.objects_And_Primitive_Types

uses java.lang.Integer
uses java.lang.Long

class Errant_ObjectsPrimitives_intAndObject {
  class A{}
  class B{}

  function foo8(i: int, j: int) : A { return null }
  function foo8(i: Object, j: Object) : B { return null }

  function caller() {
    var a1111 : A =  foo8(42, 42)
    //IDE-1523
    var a1112 : A =  foo8(100L, 100L)            //## issuekeys: INCOMPATIBLE TYPES.
    var a1113 : A =  foo8(42, 100L)            //## issuekeys: INCOMPATIBLE TYPES.
    var a1114 : A =  foo8(100L, 42)            //## issuekeys: INCOMPATIBLE TYPES.
    //IDE-1515
    var a1115 : A =  foo8(42, new Integer(42))
    var a1116 : A =  foo8(new Integer(42), 42)

    var a1117 : A =  foo8(100L, new Long(100))            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_8.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_8.A'
    var a1118 : A =  foo8(new Long(100), 100L)            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_8.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_8.A'
    //IDE-1522
    var a1119 : A =  foo8(42, new Long(100))            //## issuekeys: INCOMPATIBLE TYPES.
    var a1120 : A =  foo8(new Integer(42), 100L)            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_8.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_8.A'
    var a1121 : A =  foo8(new Integer(42), new Long(100))                                    //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_8.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_8.A'
    var a1122 : A =  foo8(new Long(100), new Integer(42))                                    //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_8.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_8.A'

    var b1111 : B =  foo8(42, 42)                                    //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_8.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_8.B'
    //IDE-1523
    var b1112 : B =  foo8(100L, 100L)
    var b1113 : B =  foo8(42, 100L)
    var b1114 : B =  foo8(100L, 42)
    //IDE-1515
    var b1115 : B =  foo8(42, new Integer(42))                          //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_8.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_8.B'
    var b1116 : B =  foo8(new Integer(42), 42)                          //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_8.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_8.B'
    var b1117 : B =  foo8(100L, new Long(100))
    var b1118 : B =  foo8(new Long(100), 100L)
    //IDE-1522
    var b1119 : B =  foo8(42, new Long(100))
    var b1120 : B =  foo8(new Integer(42), 100L)
    var b1121 : B =  foo8(new Integer(42), new Long(100))
    var b1122 : B =  foo8(new Long(100), new Integer(42))

    var c1111 =  foo8(42, 42)
    //IDE-1523
    var c1112 =  foo8(100L, 100L)
    var c1113 =  foo8(42, 100L)
    var c1114 =  foo8(100L, 42)
    var c1115 =  foo8(42, new Integer(42))
    var c1116 =  foo8(new Integer(42), 42)
    var c1117 =  foo8(100L, new Long(100))
    var c1118 =  foo8(new Long(100), 100L)
    //IDE-1522
    var c1119 =  foo8(42, new Long(100))
    var c1120 =  foo8(new Integer(42), 100L)
    var c1121 =  foo8(new Integer(42), new Long(100))
    var c1122 =  foo8(new Long(100), new Integer(42))

  }
}