package gw.specContrib.classes.method_Scoring.objects_And_Primitive_Types

uses java.lang.*

class Errant_ObjectsPrimitives_SuperFloatSubfloat {
  interface A {}
  interface B extends A {}
  interface C extends B {}
  interface D extends C {}

  var dd : D
  var char1 : char
  var byte1 : byte
  var short1 : short
  var int1 : int
  var float1 : float
  var long1 : long
  var double1 : double

  var charObj1 : Character
  var byteObj1 : Byte
  var shortObj1 : Short
  var intObj1 : Integer
  var floatObj1 : Float
  var longObj1 : Long
  var doubleObj1 : Double
  class AA {}
  class KK {}

  function fun(i : A, j : Float) : AA {return null}
  function fun(i : B, j : float) : KK {return null}
  function caller() {
    var SuperIntegerSubint1111 : AA = fun(dd, char1)            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.KK', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.AA'
    var SuperIntegerSubint1112 : AA = fun(dd, byte1)            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.KK', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.AA'
    var SuperIntegerSubint1113 : AA = fun(dd, short1)            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.KK', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.AA'
    var SuperIntegerSubint1114 : AA = fun(dd, int1)            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.KK', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.AA'
    var SuperIntegerSubint1115 : AA = fun(dd, float1)             //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.KK', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.AA'
    var SuperIntegerSubint1116 : AA = fun(dd, long1)            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.KK', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.AA'
    var SuperIntegerSubint1117 : AA = fun(dd, double1)            //## issuekeys: 'FUN(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.B, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.D, DOUBLE)'

    var SuperIntegerSubint1211 : AA = fun(dd, charObj1)            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.KK', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.AA'
    var SuperIntegerSubint1212 : AA = fun(dd, byteObj1)            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.KK', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.AA'
    var SuperIntegerSubint1213 : AA = fun(dd, shortObj1)            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.KK', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.AA'
    var SuperIntegerSubint1214 : AA = fun(dd, intObj1)            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.KK', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.AA'
    var SuperIntegerSubint1215 : AA = fun(dd, floatObj1)
    var SuperIntegerSubint1216 : AA = fun(dd, longObj1)            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.KK', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.AA'
    var SuperIntegerSubint1217 : AA = fun(dd, doubleObj1)            //## issuekeys: 'FUN(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.B, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.D, JAVA.LANG.DOUBLE)'


    var SuperIntegerSubint2111 : KK = fun(dd, char1)
    var SuperIntegerSubint2112 : KK = fun(dd, byte1)
    var SuperIntegerSubint2113 : KK = fun(dd, short1)
    var SuperIntegerSubint2114 : KK = fun(dd, int1)
    var SuperIntegerSubint2115 : KK = fun(dd, float1)
    var SuperIntegerSubint2116 : KK = fun(dd, long1)
    var SuperIntegerSubint2117 : KK = fun(dd, double1)            //## issuekeys: 'FUN(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.B, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.D, DOUBLE)'

    var SuperIntegerSubint2211 : KK = fun(dd, charObj1)
    var SuperIntegerSubint2212 : KK = fun(dd, byteObj1)
    var SuperIntegerSubint2213 : KK = fun(dd, shortObj1)
    var SuperIntegerSubint2214 : KK = fun(dd, intObj1)
    var SuperIntegerSubint2215 : KK = fun(dd, floatObj1)            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.AA', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.KK'
    var SuperIntegerSubint2216 : KK = fun(dd, longObj1)
    var SuperIntegerSubint2217 : KK = fun(dd, doubleObj1)            //## issuekeys: 'FUN(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.B, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.D, JAVA.LANG.DOUBLE)'

    var SuperIntegerSubint3111 = fun(dd, char1)
    var SuperIntegerSubint3112 = fun(dd, byte1)
    var SuperIntegerSubint3113 = fun(dd, short1)
    var SuperIntegerSubint3114 = fun(dd, int1)
    var SuperIntegerSubint3115 = fun(dd, float1)
    var SuperIntegerSubint3116 = fun(dd, long1)
    var SuperIntegerSubint3117 = fun(dd, double1)            //## issuekeys: 'FUN(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.B, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.D, DOUBLE)'

    var SuperIntegerSubint3211 = fun(dd, charObj1)
    var SuperIntegerSubint3212 = fun(dd, byteObj1)
    var SuperIntegerSubint3213 = fun(dd, shortObj1)
    var SuperIntegerSubint3214 = fun(dd, intObj1)
    var SuperIntegerSubint3215 = fun(dd, floatObj1)
    var SuperIntegerSubint3216 = fun(dd, longObj1)
    var SuperIntegerSubint3217 = fun(dd, doubleObj1)            //## issuekeys: 'FUN(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.B, FLOAT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT' CANNOT BE APPLIED TO '(GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.OBJECTSPRIMITIVES_METHODSCORING.OBJECTSPRIMITIVES_SUPERFLOATSUBFLOAT.D, JAVA.LANG.DOUBLE)'
  }
}