package gw.specContrib.classes.property_Declarations.javaClassGosuSubClass;

public class Errant_JavaSuper_FunctionVsProperty_3 {
    String getNormalProperty()  { return null; }
    void setNormalProperty(String s){}

    //Should not show error as the function generated by property will be getsmallCaseProperty3() with small 's'
    String getSmallCaseProperty1()  { return null; }
    void setSmallCaseProperty1(String s){}

    String getSmallCaseProperty12()  { return null; }
    void setSmallCaseProperty12(String s){}

    String getsmallCaseProperty2() { return null; }
    void setsmallCaseProperty2(String s){}

    //Should not show error
    String getsmallCaseProperty3() { return null; }
    void setsmallCaseProperty3(String s){}

    String getOnlyGetter1() { return null; }
    String getOnlyGetter2() { return null; }
    String getOnlyGetter3() { return null; }

    void setOnlySetter1(String s) { }
    void setOnlySetter2(String s) { }
    void setOnlySetter3(String s) { }
}
