package gw.internal.schema.gw.xsd.w3c.wsdl;

/***************************************************************************/
/* THIS IS AUTOGENERATED CODE - DO NOT MODIFY OR YOUR CHANGES WILL BE LOST */
/* THIS CODE CAN BE REGENERATED USING 'xsd-codegen'                        */
/***************************************************************************/
public class Definitions extends gw.xml.XmlElement implements gw.internal.xml.IXmlGeneratedClass {

  public static final javax.xml.namespace.QName $ATTRIBUTE_QNAME_Name = new javax.xml.namespace.QName( "", "name", "" );
  public static final javax.xml.namespace.QName $ATTRIBUTE_QNAME_TargetNamespace = new javax.xml.namespace.QName( "", "targetNamespace", "" );
  public static final javax.xml.namespace.QName $ELEMENT_QNAME_Binding = new javax.xml.namespace.QName( "http://schemas.xmlsoap.org/wsdl/", "binding", "wsdl" );
  public static final javax.xml.namespace.QName $ELEMENT_QNAME_Documentation = new javax.xml.namespace.QName( "http://schemas.xmlsoap.org/wsdl/", "documentation", "wsdl" );
  public static final javax.xml.namespace.QName $ELEMENT_QNAME_Import = new javax.xml.namespace.QName( "http://schemas.xmlsoap.org/wsdl/", "import", "wsdl" );
  public static final javax.xml.namespace.QName $ELEMENT_QNAME_Message = new javax.xml.namespace.QName( "http://schemas.xmlsoap.org/wsdl/", "message", "wsdl" );
  public static final javax.xml.namespace.QName $ELEMENT_QNAME_PortType = new javax.xml.namespace.QName( "http://schemas.xmlsoap.org/wsdl/", "portType", "wsdl" );
  public static final javax.xml.namespace.QName $ELEMENT_QNAME_Service = new javax.xml.namespace.QName( "http://schemas.xmlsoap.org/wsdl/", "service", "wsdl" );
  public static final javax.xml.namespace.QName $ELEMENT_QNAME_Types = new javax.xml.namespace.QName( "http://schemas.xmlsoap.org/wsdl/", "types", "wsdl" );
  public static final javax.xml.namespace.QName $QNAME = new javax.xml.namespace.QName( "http://schemas.xmlsoap.org/wsdl/", "definitions", "wsdl" );
  public static final gw.util.concurrent.LockingLazyVar<gw.lang.reflect.IType> TYPE = new gw.util.concurrent.LockingLazyVar<gw.lang.reflect.IType>( gw.lang.reflect.TypeSystem.getGlobalLock() ) {
          @Override
          protected gw.lang.reflect.IType init() {
            return gw.lang.reflect.TypeSystem.getByFullName( "gw.xsd.w3c.wsdl.Definitions" );
          }
        };
  private static final gw.util.concurrent.LockingLazyVar<gw.lang.reflect.IType> TYPEINSTANCETYPE = new gw.util.concurrent.LockingLazyVar<gw.lang.reflect.IType>( gw.lang.reflect.TypeSystem.getGlobalLock() ) {
          @Override
          protected gw.lang.reflect.IType init() {
            return gw.lang.reflect.TypeSystem.getByFullName( "gw.xsd.w3c.wsdl.types.complex.TDefinitions" );
          }
        };

  public Definitions() {
    this( new gw.internal.schema.gw.xsd.w3c.wsdl.types.complex.TDefinitions() );
  }

  public Definitions( gw.internal.schema.gw.xsd.w3c.wsdl.types.complex.TDefinitions typeInstance ) {
    super( $QNAME, TYPE.get(), TYPEINSTANCETYPE.get(), typeInstance );
  }

  protected Definitions( javax.xml.namespace.QName qname, gw.lang.reflect.IType type, gw.lang.reflect.IType schemaDefinedTypeInstanceType, gw.internal.schema.gw.xsd.w3c.xmlschema.types.complex.AnyType typeInstance ) {
    super( qname, type, schemaDefinedTypeInstanceType, typeInstance );
  }


  public gw.internal.schema.gw.xsd.w3c.wsdl.types.complex.TDefinitions getTypeInstance() {
    //noinspection RedundantCast
    return (gw.internal.schema.gw.xsd.w3c.wsdl.types.complex.TDefinitions) super.getTypeInstance();
  }

  public void setTypeInstance( gw.internal.schema.gw.xsd.w3c.wsdl.types.complex.TDefinitions param ) {
    super.setTypeInstance( param );
  }


  public java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_Binding> Binding() {
    //noinspection unchecked
    return (java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_Binding>) TYPE.get().getTypeInfo().getProperty( "Binding" ).getAccessor().getValue( this );
  }

  public void setBinding$( java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_Binding> param ) {
    TYPE.get().getTypeInfo().getProperty( "Binding" ).getAccessor().setValue( this, param );
  }


  public gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDocumented_Documentation Documentation() {
    return (gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDocumented_Documentation) TYPE.get().getTypeInfo().getProperty( "Documentation" ).getAccessor().getValue( this );
  }

  public void setDocumentation$( gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDocumented_Documentation param ) {
    TYPE.get().getTypeInfo().getProperty( "Documentation" ).getAccessor().setValue( this, param );
  }


  public java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_Import> Import() {
    //noinspection unchecked
    return (java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_Import>) TYPE.get().getTypeInfo().getProperty( "Import" ).getAccessor().getValue( this );
  }

  public void setImport$( java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_Import> param ) {
    TYPE.get().getTypeInfo().getProperty( "Import" ).getAccessor().setValue( this, param );
  }


  public java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_Message> Message() {
    //noinspection unchecked
    return (java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_Message>) TYPE.get().getTypeInfo().getProperty( "Message" ).getAccessor().getValue( this );
  }

  public void setMessage$( java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_Message> param ) {
    TYPE.get().getTypeInfo().getProperty( "Message" ).getAccessor().setValue( this, param );
  }


  public java.lang.String Name() {
    return (java.lang.String) TYPE.get().getTypeInfo().getProperty( "Name" ).getAccessor().getValue( this );
  }

  public void setName$( java.lang.String param ) {
    TYPE.get().getTypeInfo().getProperty( "Name" ).getAccessor().setValue( this, param );
  }


  public java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_PortType> PortType() {
    //noinspection unchecked
    return (java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_PortType>) TYPE.get().getTypeInfo().getProperty( "PortType" ).getAccessor().getValue( this );
  }

  public void setPortType$( java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_PortType> param ) {
    TYPE.get().getTypeInfo().getProperty( "PortType" ).getAccessor().setValue( this, param );
  }


  public java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_Service> Service() {
    //noinspection unchecked
    return (java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_Service>) TYPE.get().getTypeInfo().getProperty( "Service" ).getAccessor().getValue( this );
  }

  public void setService$( java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_Service> param ) {
    TYPE.get().getTypeInfo().getProperty( "Service" ).getAccessor().setValue( this, param );
  }


  public java.net.URI TargetNamespace() {
    return (java.net.URI) TYPE.get().getTypeInfo().getProperty( "TargetNamespace" ).getAccessor().getValue( this );
  }

  public void setTargetNamespace$( java.net.URI param ) {
    TYPE.get().getTypeInfo().getProperty( "TargetNamespace" ).getAccessor().setValue( this, param );
  }


  public java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_Types> Types() {
    //noinspection unchecked
    return (java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_Types>) TYPE.get().getTypeInfo().getProperty( "Types" ).getAccessor().getValue( this );
  }

  public void setTypes$( java.util.List<gw.internal.schema.gw.xsd.w3c.wsdl.anonymous.elements.TDefinitions_Types> param ) {
    TYPE.get().getTypeInfo().getProperty( "Types" ).getAccessor().setValue( this, param );
  }

  public static gw.internal.schema.gw.xsd.w3c.wsdl.Definitions parse( byte[] byteArray ) {
    //noinspection RedundantArrayCreation
    return (gw.internal.schema.gw.xsd.w3c.wsdl.Definitions) TYPE.get().getTypeInfo().getMethod( "parse", gw.lang.reflect.TypeSystem.get( byte[].class ) ).getCallHandler().handleCall( null, new java.lang.Object[] { byteArray } );
  }

  public static gw.internal.schema.gw.xsd.w3c.wsdl.Definitions parse( byte[] byteArray, gw.xml.XmlParseOptions options ) {
    //noinspection RedundantArrayCreation
    return (gw.internal.schema.gw.xsd.w3c.wsdl.Definitions) TYPE.get().getTypeInfo().getMethod( "parse", gw.lang.reflect.TypeSystem.get( byte[].class ), gw.lang.reflect.TypeSystem.get( gw.xml.XmlParseOptions.class ) ).getCallHandler().handleCall( null, new java.lang.Object[] { byteArray, options } );
  }

  public static gw.internal.schema.gw.xsd.w3c.wsdl.Definitions parse( java.io.File file ) {
    //noinspection RedundantArrayCreation
    return (gw.internal.schema.gw.xsd.w3c.wsdl.Definitions) TYPE.get().getTypeInfo().getMethod( "parse", gw.lang.reflect.TypeSystem.get( java.io.File.class ) ).getCallHandler().handleCall( null, new java.lang.Object[] { file } );
  }

  public static gw.internal.schema.gw.xsd.w3c.wsdl.Definitions parse( java.io.File file, gw.xml.XmlParseOptions options ) {
    //noinspection RedundantArrayCreation
    return (gw.internal.schema.gw.xsd.w3c.wsdl.Definitions) TYPE.get().getTypeInfo().getMethod( "parse", gw.lang.reflect.TypeSystem.get( java.io.File.class ), gw.lang.reflect.TypeSystem.get( gw.xml.XmlParseOptions.class ) ).getCallHandler().handleCall( null, new java.lang.Object[] { file, options } );
  }

  public static gw.internal.schema.gw.xsd.w3c.wsdl.Definitions parse( java.io.InputStream inputStream ) {
    //noinspection RedundantArrayCreation
    return (gw.internal.schema.gw.xsd.w3c.wsdl.Definitions) TYPE.get().getTypeInfo().getMethod( "parse", gw.lang.reflect.TypeSystem.get( java.io.InputStream.class ) ).getCallHandler().handleCall( null, new java.lang.Object[] { inputStream } );
  }

  public static gw.internal.schema.gw.xsd.w3c.wsdl.Definitions parse( java.io.InputStream inputStream, gw.xml.XmlParseOptions options ) {
    //noinspection RedundantArrayCreation
    return (gw.internal.schema.gw.xsd.w3c.wsdl.Definitions) TYPE.get().getTypeInfo().getMethod( "parse", gw.lang.reflect.TypeSystem.get( java.io.InputStream.class ), gw.lang.reflect.TypeSystem.get( gw.xml.XmlParseOptions.class ) ).getCallHandler().handleCall( null, new java.lang.Object[] { inputStream, options } );
  }

  public static gw.internal.schema.gw.xsd.w3c.wsdl.Definitions parse( java.io.Reader reader ) {
    //noinspection RedundantArrayCreation
    return (gw.internal.schema.gw.xsd.w3c.wsdl.Definitions) TYPE.get().getTypeInfo().getMethod( "parse", gw.lang.reflect.TypeSystem.get( java.io.Reader.class ) ).getCallHandler().handleCall( null, new java.lang.Object[] { reader } );
  }

  public static gw.internal.schema.gw.xsd.w3c.wsdl.Definitions parse( java.io.Reader reader, gw.xml.XmlParseOptions options ) {
    //noinspection RedundantArrayCreation
    return (gw.internal.schema.gw.xsd.w3c.wsdl.Definitions) TYPE.get().getTypeInfo().getMethod( "parse", gw.lang.reflect.TypeSystem.get( java.io.Reader.class ), gw.lang.reflect.TypeSystem.get( gw.xml.XmlParseOptions.class ) ).getCallHandler().handleCall( null, new java.lang.Object[] { reader, options } );
  }

  public static gw.internal.schema.gw.xsd.w3c.wsdl.Definitions parse( java.lang.String xmlString ) {
    //noinspection RedundantArrayCreation
    return (gw.internal.schema.gw.xsd.w3c.wsdl.Definitions) TYPE.get().getTypeInfo().getMethod( "parse", gw.lang.reflect.TypeSystem.get( java.lang.String.class ) ).getCallHandler().handleCall( null, new java.lang.Object[] { xmlString } );
  }

  public static gw.internal.schema.gw.xsd.w3c.wsdl.Definitions parse( java.lang.String xmlString, gw.xml.XmlParseOptions options ) {
    //noinspection RedundantArrayCreation
    return (gw.internal.schema.gw.xsd.w3c.wsdl.Definitions) TYPE.get().getTypeInfo().getMethod( "parse", gw.lang.reflect.TypeSystem.get( java.lang.String.class ), gw.lang.reflect.TypeSystem.get( gw.xml.XmlParseOptions.class ) ).getCallHandler().handleCall( null, new java.lang.Object[] { xmlString, options } );
  }

  public static gw.internal.schema.gw.xsd.w3c.wsdl.Definitions parse( java.net.URL url ) {
    //noinspection RedundantArrayCreation
    return (gw.internal.schema.gw.xsd.w3c.wsdl.Definitions) TYPE.get().getTypeInfo().getMethod( "parse", gw.lang.reflect.TypeSystem.get( java.net.URL.class ) ).getCallHandler().handleCall( null, new java.lang.Object[] { url } );
  }

  public static gw.internal.schema.gw.xsd.w3c.wsdl.Definitions parse( java.net.URL url, gw.xml.XmlParseOptions options ) {
    //noinspection RedundantArrayCreation
    return (gw.internal.schema.gw.xsd.w3c.wsdl.Definitions) TYPE.get().getTypeInfo().getMethod( "parse", gw.lang.reflect.TypeSystem.get( java.net.URL.class ), gw.lang.reflect.TypeSystem.get( gw.xml.XmlParseOptions.class ) ).getCallHandler().handleCall( null, new java.lang.Object[] { url, options } );
  }

  @SuppressWarnings( {"UnusedDeclaration"} )
  private static final long FINGERPRINT = -6050492648119042255L;

}
