package gw.specContrib.interfaceMethods.defaultMethods

class Errant_DefaultAndAbstractConflict_1 {
  interface IA {
    function foo(): String {
      return null
    }
  }

  interface IB {
    abstract function foo() : String
  }

  //IDE-2607
  interface IC extends IA, IB {              //## issuekeys: GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVA8.DEFAULTMETHODS.ERRANT_DEFAULTANDABSTRACTCONFLICT_1.IC INHERITS ABSTRACT AND DEFAULT FOR FOO() FROM TYPES GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVA8.DEFAULTMETHODS.ERRANT_DEFAULTANDABSTRACTCONFLICT_1.IA AND GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVA8.DEFAULTMETHODS.ERRANT_DEFAULTANDABSTRACTCONFLICT_1.IB

  }

  class D1 implements IA, IB {              //## issuekeys: CLASS 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVA8.DEFAULTMETHODS.ERRANT_DEFAULTANDABSTRACTCONFLICT_1.IB' MUST EITHER BE DECLARED ABSTRACT OR IMPLEMENT ABSTRACT METHOD 'FOO()' IN 'IB'
  }
  class D2 implements IB, IA {              //## issuekeys: CLASS 'D2' MUST EITHER BE DECLARED ABSTRACT OR IMPLEMENT ABSTRACT METHOD 'FOO()' IN 'IB'
  }


  //IDE-2607
  abstract class C implements IA, IB {              //## issuekeys: GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVA8.DEFAULTMETHODS.ERRANT_DEFAULTANDABSTRACTCONFLICT_1.C INHERITS ABSTRACT AND DEFAULT FOR FOO() FROM TYPES GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVA8.DEFAULTMETHODS.ERRANT_DEFAULTANDABSTRACTCONFLICT_1.IA AND GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVA8.DEFAULTMETHODS.ERRANT_DEFAULTANDABSTRACTCONFLICT_1.IB

  }



}