package gw.specContrib.interfaceMethods.defaultMethods

uses java.lang.Iterable
uses java.util.Iterator

class Errant_DefaultAndAbstractConflict_2 {
  interface A {
    function iterator(): Iterator<Object> {
      return null
    }
  }

  //IDE-2614 - Error expected
  interface B11 extends A, Iterable<Object> {               //## issuekeys: GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVA8.DEFAULTMETHODS.ERRANT_DEFAULTANDABSTRACTCONFLICT_2.B11 INHERITS ABSTRACT AND DEFAULT FOR ITERATOR() FROM TYPES GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVA8.DEFAULTMETHODS.ERRANT_DEFAULTANDABSTRACTCONFLICT_2.A AND JAVA.LANG.ITERABLE
  }

  interface B12 extends Iterable<Object>, A {     //## issuekeys: GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVA8.DEFAULTMETHODS.ERRANT_DEFAULTANDABSTRACTCONFLICT_2.B11 INHERITS ABSTRACT AND DEFAULT FOR ITERATOR() FROM TYPES GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVA8.DEFAULTMETHODS.ERRANT_DEFAULTANDABSTRACTCONFLICT_2.A AND JAVA.LANG.ITERABLE
  }


  interface AA {
    function iterator(): Iterator {
      return null
    }
  }

  //IDE-2614 - Issue in both OS Gosu and Parser. Should be an error
  interface BB1 extends AA, Iterable {            //## issuekeys: GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVA8.DEFAULTMETHODS.ERRANT_DEFAULTANDABSTRACTCONFLICT_2.BB1 INHERITS ABSTRACT AND DEFAULT FOR ITERATOR() FROM TYPES GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVA8.DEFAULTMETHODS.ERRANT_DEFAULTANDABSTRACTCONFLICT_2.AA AND JAVA.LANG.ITERABLE
  }

  interface BB2 extends Iterable, AA {      //## issuekeys: GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVA8.DEFAULTMETHODS.ERRANT_DEFAULTANDABSTRACTCONFLICT_2.BB1 INHERITS ABSTRACT AND DEFAULT FOR ITERATOR() FROM TYPES GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVA8.DEFAULTMETHODS.ERRANT_DEFAULTANDABSTRACTCONFLICT_2.AA AND JAVA.LANG.ITERABLE
  }

  ///Multiple inheritance
  interface A2 {
    function iterator(): Iterator<Object> {
      return null
    }
  }

  interface B2 extends Iterable<Object> {
  }

  //IDE-2614
  interface I2 extends A2, B2 {            //## issuekeys: GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVA8.DEFAULTMETHODS.ERRANT_DEFAULTANDABSTRACTCONFLICT_2.I2 INHERITS ABSTRACT AND DEFAULT FOR ITERATOR() FROM TYPES GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.JAVA8.DEFAULTMETHODS.ERRANT_DEFAULTANDABSTRACTCONFLICT_2.A2 AND JAVA.LANG.ITERABLE

  }

  class C2 implements A2, B2 {            //## issuekeys: CLASS 'JAVA.LANG.ITERABLE' MUST EITHER BE DECLARED ABSTRACT OR IMPLEMENT ABSTRACT METHOD 'ITERATOR()' IN 'ITERABLE'

  }

  class D2 implements A2, B2 {
    override function iterator(): Iterator<Object> {
      return null
    }
  }
}