package gw.internal.schema.gw.xsd.w3c.xmlschema.types.simple;

/***************************************************************************/
/* THIS IS AUTOGENERATED CODE - DO NOT MODIFY OR YOUR CHANGES WILL BE LOST */
/* THIS CODE CAN BE REGENERATED USING 'xsd-codegen'                        */
/***************************************************************************/
public class ReducedDerivationControl extends gw.internal.schema.gw.xsd.w3c.xmlschema.types.simple.DerivationControl implements gw.internal.xml.IXmlGeneratedClass {

  public static final javax.xml.namespace.QName $QNAME = new javax.xml.namespace.QName( "http://www.w3.org/2001/XMLSchema", "reducedDerivationControl", "xs" );
  public static final gw.util.concurrent.LockingLazyVar<gw.lang.reflect.IType> TYPE = new gw.util.concurrent.LockingLazyVar<gw.lang.reflect.IType>( gw.lang.reflect.TypeSystem.getGlobalLock() ) {
          @Override
          protected gw.lang.reflect.IType init() {
            return gw.lang.reflect.TypeSystem.getByFullName( "gw.xsd.w3c.xmlschema.types.simple.ReducedDerivationControl" );
          }
        };
  private static final gw.util.concurrent.LockingLazyVar<java.lang.Object> SCHEMAINFO = new gw.util.concurrent.LockingLazyVar<java.lang.Object>( gw.lang.reflect.TypeSystem.getGlobalLock() ) {
          @Override
          protected java.lang.Object init() {
            gw.lang.reflect.IType type = TYPE.get();
            return getSchemaInfoByType( type );
          }
        };

  public ReducedDerivationControl() {
    super( TYPE.get(), SCHEMAINFO.get() );
  }

  protected ReducedDerivationControl( gw.lang.reflect.IType type, java.lang.Object schemaInfo ) {
    super( type, schemaInfo );
  }

  public ReducedDerivationControl( gw.internal.schema.gw.xsd.w3c.xmlschema.enums.ReducedDerivationControl value ) {
    this();
    TYPE.get().getTypeInfo().getProperty( "$Value" ).getAccessor().setValue( this, value );
  }


  @Deprecated
  public gw.internal.schema.gw.xsd.w3c.xmlschema.enums.DerivationControl getValue$$gw_xsd_w3c_xmlschema_types_simple_DerivationControl() {
    return super.getValue$$gw_xsd_w3c_xmlschema_types_simple_DerivationControl();
  }

  @Deprecated
  public void setValue$$gw_xsd_w3c_xmlschema_types_simple_DerivationControl( gw.internal.schema.gw.xsd.w3c.xmlschema.enums.DerivationControl param ) {
    super.setValue$$gw_xsd_w3c_xmlschema_types_simple_DerivationControl( param );
  }

  public gw.internal.schema.gw.xsd.w3c.xmlschema.enums.ReducedDerivationControl getValue$$gw_xsd_w3c_xmlschema_types_simple_ReducedDerivationControl() {
    return (gw.internal.schema.gw.xsd.w3c.xmlschema.enums.ReducedDerivationControl) TYPE.get().getTypeInfo().getProperty( "$Value" ).getAccessor().getValue( this );
  }

  public void setValue$$gw_xsd_w3c_xmlschema_types_simple_ReducedDerivationControl( gw.internal.schema.gw.xsd.w3c.xmlschema.enums.ReducedDerivationControl param ) {
    TYPE.get().getTypeInfo().getProperty( "$Value" ).getAccessor().setValue( this, param );
  }

  @SuppressWarnings( {"UnusedDeclaration"} )
  private static final long FINGERPRINT = 2110283714877373226L;

}
