package gw.specContrib.classes.method_Scoring.collections_And_Generics

uses java.io.Serializable
uses java.lang.*
uses java.util.*

class Errant_Generics_MethodScoring_5 {
  class A{}
  class B{}

  class P{}
  interface Q extends Serializable {}
  abstract class R extends java.lang.Number {}

  var pp : P
  var qq : Q
  var rr : R

  var aList : ArrayList
  var aListInt : ArrayList<Integer>

  var intArray : int[]
  var intObjArray : Integer[]
  var longArray : long[]
  var longObjArray : Long[]

  function foo5<T>(p: List<T>, i: int[]) : A {return  null}
  function foo5<T extends Serializable>(p: List<T>, i: long[]) : B {return null}

  function caller() {
    //IDE-1518
    var a1109 : A =  foo5({1, 2, 3}, {1,2,3})            //## issuekeys: AMBIGUOUS METHOD CALL: BOTH 'GENERICS_METHODSCORING_5.FOO5(LIST<INTEGER>, INT[])' AND 'GENERICS_METHODSCORING_5.FOO5(LIST<INTEGER>, LONG[])' MATCH
    var a1110 : A =  foo5({1L, 2L, 3L}, {1L,2L,3L})            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5.A'
    var a1111 : A =  foo5({1, 2, 3}, intArray)
    var a1112 : A =  foo5(aList, intArray)
    var a1113 : A =  foo5({pp, pp}, intArray)
    var a1114 : A =  foo5({qq, qq}, intArray)
    var a1115 : A =  foo5({rr, rr}, intArray)

    var a2111 : A =  foo5({1, 2, 3}, intObjArray)                  //## issuekeys: CANNOT RESOLVE METHOD 'FOO5(JAVA.UTIL.ARRAYLIST<JAVA.LANG.INTEGER>, JAVA.LANG.INTEGER[])'
    var a2112 : A =  foo5(aList, intObjArray)                  //## issuekeys: CANNOT RESOLVE METHOD 'FOO5(JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>, JAVA.LANG.INTEGER[])'
    var a2113 : A =  foo5({pp, pp}, intObjArray)                  //## issuekeys: 'FOO5(JAVA.UTIL.LIST<JAVA.LANG.OBJECT>, INT[])' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5' CANNOT BE APPLIED TO '(JAVA.UTIL.LIST<JAVA.LANG.OBJECT>, JAVA.LANG.INTEGER[])'
    var a2114 : A =  foo5({qq, qq}, intObjArray)                  //## issuekeys: CANNOT RESOLVE METHOD 'FOO5(JAVA.UTIL.ARRAYLIST<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5.Q>, JAVA.LANG.INTEGER[])'
    var a2115 : A =  foo5({rr, rr}, intObjArray)                  //## issuekeys: CANNOT RESOLVE METHOD 'FOO5(JAVA.UTIL.ARRAYLIST<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5.R>, JAVA.LANG.INTEGER[])'

    var a3111 : A =  foo5({1, 2, 3}, longArray)                  //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5.A'
    var a3112 : A =  foo5(aList, longArray)                  //## issuekeys: INFERRED TYPE 'JAVA.LANG.OBJECT' FOR TYPE PARAMETER 'T' IS NOT WITHIN ITS BOUND; SHOULD IMPLEMENT 'JAVA.IO.SERIALIZABLE'
    var a3113 : A =  foo5({pp, pp}, longArray)                  //## issuekeys: INFERRED TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5.P' FOR TYPE PARAMETER 'T' IS NOT WITHIN ITS BOUND; SHOULD IMPLEMENT 'JAVA.IO.SERIALIZABLE'
    var a3114 : A =  foo5({qq, qq}, longArray)                  //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5.A'
    var a3115 : A =  foo5({rr, rr}, longArray)                  //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5.A'

    var a4111 : A =  foo5({1, 2, 3}, longObjArray)                  //## issuekeys: CANNOT RESOLVE METHOD 'FOO5(JAVA.UTIL.ARRAYLIST<JAVA.LANG.INTEGER>, JAVA.LANG.LONG[])'
    var a4112 : A =  foo5(aList, longObjArray)                  //## issuekeys: CANNOT RESOLVE METHOD 'FOO5(JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>, JAVA.LANG.LONG[])'
    var a4113 : A =  foo5({pp, pp}, longObjArray)                  //## issuekeys: 'FOO5(JAVA.UTIL.LIST<JAVA.LANG.OBJECT>, INT[])' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5' CANNOT BE APPLIED TO '(JAVA.UTIL.LIST<JAVA.LANG.OBJECT>, JAVA.LANG.LONG[])'
    var a4114 : A =  foo5({qq, qq}, longObjArray)                  //## issuekeys: CANNOT RESOLVE METHOD 'FOO5(JAVA.UTIL.ARRAYLIST<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5.Q>, JAVA.LANG.LONG[])'
    var a4115 : A =  foo5({rr, rr}, longObjArray)                  //## issuekeys: CANNOT RESOLVE METHOD 'FOO5(JAVA.UTIL.ARRAYLIST<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5.R>, JAVA.LANG.LONG[])'

    //IDE-1518
    var b1109 : B =  foo5({1, 2, 3}, {1,2,3})            //## issuekeys: AMBIGUOUS METHOD CALL: BOTH 'GENERICS_METHODSCORING_5.FOO5(LIST<INTEGER>, INT[])' AND 'GENERICS_METHODSCORING_5.FOO5(LIST<INTEGER>, LONG[])' MATCH
    var b1110 : B =  foo5({1L, 2L, 3L}, {1L,2L,3L})
    var b1111 : B =  foo5({1, 2, 3}, intArray)                  //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5.B'
    var b1112 : B =  foo5(aList, intArray)                  //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5.B'
    var b1113 : B =  foo5({pp, pp}, intArray)                  //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5.B'
    var b1114 : B =  foo5({qq, qq}, intArray)                  //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5.B'
    var b1115 : B =  foo5({rr, rr}, intArray)                  //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5.B'

    var b2111 : B =  foo5({1, 2, 3}, intObjArray)                  //## issuekeys: CANNOT RESOLVE METHOD 'FOO5(JAVA.UTIL.ARRAYLIST<JAVA.LANG.INTEGER>, JAVA.LANG.INTEGER[])'
    var b2112 : B =  foo5(aList, intObjArray)                  //## issuekeys: CANNOT RESOLVE METHOD 'FOO5(JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>, JAVA.LANG.INTEGER[])'
    var b2113 : B =  foo5({pp, pp}, intObjArray)                  //## issuekeys: 'FOO5(JAVA.UTIL.LIST<JAVA.LANG.OBJECT>, INT[])' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5' CANNOT BE APPLIED TO '(JAVA.UTIL.LIST<JAVA.LANG.OBJECT>, JAVA.LANG.INTEGER[])'
    var b2114 : B =  foo5({qq, qq}, intObjArray)                  //## issuekeys: CANNOT RESOLVE METHOD 'FOO5(JAVA.UTIL.ARRAYLIST<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5.Q>, JAVA.LANG.INTEGER[])'
    var b2115 : B =  foo5({rr, rr}, intObjArray)                  //## issuekeys: CANNOT RESOLVE METHOD 'FOO5(JAVA.UTIL.ARRAYLIST<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5.R>, JAVA.LANG.INTEGER[])'

    var b3111 : B =  foo5({1, 2, 3}, longArray)
    var b3112 : B =  foo5(aList, longArray)                  //## issuekeys: INFERRED TYPE 'JAVA.LANG.OBJECT' FOR TYPE PARAMETER 'T' IS NOT WITHIN ITS BOUND; SHOULD IMPLEMENT 'JAVA.IO.SERIALIZABLE'
    var b3113 : B =  foo5({pp, pp}, longArray)                  //## issuekeys: INFERRED TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5.P' FOR TYPE PARAMETER 'T' IS NOT WITHIN ITS BOUND; SHOULD IMPLEMENT 'JAVA.IO.SERIALIZABLE'
    var b3114 : B =  foo5({qq, qq}, longArray)
    var b3115 : B =  foo5({rr, rr}, longArray)

    var b4111 : B =  foo5({1, 2, 3}, longObjArray)                  //## issuekeys: CANNOT RESOLVE METHOD 'FOO5(JAVA.UTIL.ARRAYLIST<JAVA.LANG.INTEGER>, JAVA.LANG.LONG[])'
    var b4112 : B =  foo5(aList, longObjArray)                  //## issuekeys: CANNOT RESOLVE METHOD 'FOO5(JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>, JAVA.LANG.LONG[])'
    var b4113 : B =  foo5({pp, pp}, longObjArray)                  //## issuekeys: 'FOO5(JAVA.UTIL.LIST<JAVA.LANG.OBJECT>, INT[])' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5' CANNOT BE APPLIED TO '(JAVA.UTIL.LIST<JAVA.LANG.OBJECT>, JAVA.LANG.LONG[])'
    var b4114 : B =  foo5({qq, qq}, longObjArray)                  //## issuekeys: CANNOT RESOLVE METHOD 'FOO5(JAVA.UTIL.ARRAYLIST<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5.Q>, JAVA.LANG.LONG[])'
    var b4115 : B =  foo5({rr, rr}, longObjArray)                  //## issuekeys: CANNOT RESOLVE METHOD 'FOO5(JAVA.UTIL.ARRAYLIST<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5.R>, JAVA.LANG.LONG[])'

    var c1111 =  foo5({1, 2, 3}, intArray)
    var c1112 =  foo5(aList, intArray)
    var c1113 =  foo5({pp, pp}, intArray)
    var c1114 =  foo5({qq, qq}, intArray)
    var c1115 =  foo5({rr, rr}, intArray)

    var c2111 =  foo5({1, 2, 3}, intObjArray)                  //## issuekeys: CANNOT RESOLVE METHOD 'FOO5(JAVA.UTIL.ARRAYLIST<JAVA.LANG.INTEGER>, JAVA.LANG.INTEGER[])'
    var c2112 =  foo5(aList, intObjArray)                  //## issuekeys: CANNOT RESOLVE METHOD 'FOO5(JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>, JAVA.LANG.INTEGER[])'
    var c2113 =  foo5({pp, pp}, intObjArray)                  //## issuekeys: 'FOO5(JAVA.UTIL.LIST<JAVA.LANG.OBJECT>, INT[])' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5' CANNOT BE APPLIED TO '(JAVA.UTIL.LIST<JAVA.LANG.OBJECT>, JAVA.LANG.INTEGER[])'
    var c2114 =  foo5({qq, qq}, intObjArray)                  //## issuekeys: CANNOT RESOLVE METHOD 'FOO5(JAVA.UTIL.ARRAYLIST<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5.Q>, JAVA.LANG.INTEGER[])'
    var c2115 =  foo5({rr, rr}, intObjArray)                  //## issuekeys: CANNOT RESOLVE METHOD 'FOO5(JAVA.UTIL.ARRAYLIST<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5.R>, JAVA.LANG.INTEGER[])'

    var c3111 =  foo5({1, 2, 3}, longArray)
    var c3112 =  foo5(aList, longArray)                  //## issuekeys: INFERRED TYPE 'JAVA.LANG.OBJECT' FOR TYPE PARAMETER 'T' IS NOT WITHIN ITS BOUND; SHOULD IMPLEMENT 'JAVA.IO.SERIALIZABLE'
    var c3113 =  foo5({pp, pp}, longArray)                  //## issuekeys: INFERRED TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5.P' FOR TYPE PARAMETER 'T' IS NOT WITHIN ITS BOUND; SHOULD IMPLEMENT 'JAVA.IO.SERIALIZABLE'
    var c3114 =  foo5({qq, qq}, longArray)
    var c3115 =  foo5({rr, rr}, longArray)

    var c4111 =  foo5({1, 2, 3}, longObjArray)                  //## issuekeys: CANNOT RESOLVE METHOD 'FOO5(JAVA.UTIL.ARRAYLIST<JAVA.LANG.INTEGER>, JAVA.LANG.LONG[])'
    var c4112 =  foo5(aList, longObjArray)                  //## issuekeys: CANNOT RESOLVE METHOD 'FOO5(JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>, JAVA.LANG.LONG[])'
    var c4113 =  foo5({pp, pp}, longObjArray)                  //## issuekeys: 'FOO5(JAVA.UTIL.LIST<JAVA.LANG.OBJECT>, INT[])' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5' CANNOT BE APPLIED TO '(JAVA.UTIL.LIST<JAVA.LANG.OBJECT>, JAVA.LANG.LONG[])'
    var c4114 =  foo5({qq, qq}, longObjArray)                  //## issuekeys: CANNOT RESOLVE METHOD 'FOO5(JAVA.UTIL.ARRAYLIST<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5.Q>, JAVA.LANG.LONG[])'
    var c4115 =  foo5({rr, rr}, longObjArray)                  //## issuekeys: CANNOT RESOLVE METHOD 'FOO5(JAVA.UTIL.ARRAYLIST<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_5.R>, JAVA.LANG.LONG[])'
 }
}