package gw.specContrib.classes.method_Scoring.collections_And_Generics

uses java.io.Serializable
uses java.lang.Cloneable
uses java.lang.Integer
uses java.lang.Long

class Errant_Generics_MethodScoring_7 {
  class A implements Serializable {}
  class B implements Cloneable {}
  class C implements Serializable, Cloneable {}

  class P{}
  class Q{}
  var intArray : int[]
  var longArray : long[]
  var a : A
  var b : B
  var c : C


  //7 extending multiple interfaces
  function foo7<T>(p: List<T>, i : int) : P {return null}
  function foo7<T extends Serializable & Cloneable>(p: List<T>, l : long ) : Q {return null}

  function caller() {

    var p1111 : P = foo7({1,2,3}, 42)
    var p1112 : P = foo7({100L,200L,300L}, 42)
    var p1113 : P = foo7({a,a,a}, 42)
    var p1114 : P = foo7({b,b,b}, 42)
    var p1115 : P = foo7({c,c,c}, 42)
    var p1116 : P = foo7({1,2,3}, 42L)            //## issuekeys: INFERRED TYPE 'JAVA.LANG.INTEGER' FOR TYPE PARAMETER 'T' IS NOT WITHIN ITS BOUND; SHOULD IMPLEMENT 'JAVA.LANG.CLONEABLE'
    var p1117 : P = foo7({100L,200L,300L}, 42L)            //## issuekeys: INFERRED TYPE 'JAVA.LANG.LONG' FOR TYPE PARAMETER 'T' IS NOT WITHIN ITS BOUND; SHOULD IMPLEMENT 'JAVA.LANG.CLONEABLE'
    var p1118 : P = foo7({a,a,a}, 42L)            //## issuekeys: INFERRED TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_7.A' FOR TYPE PARAMETER 'T' IS NOT WITHIN ITS BOUND; SHOULD IMPLEMENT 'JAVA.LANG.CLONEABLE'
    var p1119 : P = foo7({b,b,b}, 42L)            //## issuekeys: INFERRED TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_7.B' FOR TYPE PARAMETER 'T' IS NOT WITHIN ITS BOUND; SHOULD IMPLEMENT 'JAVA.IO.SERIALIZABLE'
    var p1120 : P = foo7({c,c,c}, 42L)            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_7.Q', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_7.P'
    var p1121 : P = foo7({c,c,c}, new Integer(42))
    var p1122 : P = foo7({c,c,c}, new Long(100))            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_7.Q', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_7.P'


    var q1111 : Q = foo7({1,2,3}, 42)            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_7.P', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_7.Q'
    var q1112 : Q = foo7({100L,200L,300L}, 42)            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_7.P', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_7.Q'
    var q1113 : Q = foo7({a,a,a}, 42)            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_7.P', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_7.Q'
    var q1114 : Q = foo7({b,b,b}, 42)            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_7.P', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_7.Q'
    var q1115 : Q = foo7({c,c,c}, 42)            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_7.P', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_7.Q'
    var q1116 : Q = foo7({1,2,3}, 42L)            //## issuekeys: INFERRED TYPE 'JAVA.LANG.INTEGER' FOR TYPE PARAMETER 'T' IS NOT WITHIN ITS BOUND; SHOULD IMPLEMENT 'JAVA.LANG.CLONEABLE'
    var q1117 : Q = foo7({100L,200L,300L}, 42L)   //## issuekeys: INFERRED TYPE 'JAVA.LANG.LONG' FOR TYPE PARAMETER 'T' IS NOT WITHIN ITS BOUND; SHOULD IMPLEMENT 'JAVA.LANG.CLONEABLE'
    var q1118 : Q = foo7({a,a,a}, 42L)            //## issuekeys: INFERRED TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_7.A' FOR TYPE PARAMETER 'T' IS NOT WITHIN ITS BOUND; SHOULD IMPLEMENT 'JAVA.LANG.CLONEABLE'
    var q1119 : Q = foo7({b,b,b}, 42L)            //## issuekeys: INFERRED TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_7.B' FOR TYPE PARAMETER 'T' IS NOT WITHIN ITS BOUND; SHOULD IMPLEMENT 'JAVA.IO.SERIALIZABLE'
    var q1120 : Q = foo7({c,c,c}, 42L)
    var q1121 : Q = foo7({c,c,c}, new Integer(42))            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_7.P', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_7.Q'
    var q1122 : Q = foo7({c,c,c}, new Long(100))

    var r1111 = foo7({1,2,3}, 42)
    var r1112 = foo7({100L,200L,300L}, 42)
    var r1113 = foo7({a,a,a}, 42)
    var r1114 = foo7({b,b,b}, 42)
    var r1115 = foo7({c,c,c}, 42)
    var r1116 = foo7({1,2,3}, 42L)            //## issuekeys: INFERRED TYPE 'JAVA.LANG.INTEGER' FOR TYPE PARAMETER 'T' IS NOT WITHIN ITS BOUND; SHOULD IMPLEMENT 'JAVA.LANG.CLONEABLE'
    var r1117 = foo7({100L,200L,300L}, 42L)            //## issuekeys: INFERRED TYPE 'JAVA.LANG.LONG' FOR TYPE PARAMETER 'T' IS NOT WITHIN ITS BOUND; SHOULD IMPLEMENT 'JAVA.LANG.CLONEABLE'
    var r1118 = foo7({a,a,a}, 42L)            //## issuekeys: INFERRED TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_7.A' FOR TYPE PARAMETER 'T' IS NOT WITHIN ITS BOUND; SHOULD IMPLEMENT 'JAVA.LANG.CLONEABLE'
    var r1119 = foo7({b,b,b}, 42L)            //## issuekeys: INFERRED TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_7.B' FOR TYPE PARAMETER 'T' IS NOT WITHIN ITS BOUND; SHOULD IMPLEMENT 'JAVA.IO.SERIALIZABLE'
    var r1120 = foo7({c,c,c}, 42L)
    var r1121 = foo7({c,c,c}, new Integer(42))
    var r1122 = foo7({c,c,c}, new Long(100))
  }
}