package gw.specContrib.classes.method_Scoring.collections_And_Generics

uses java.io.Serializable
uses java.lang.*
uses java.util.*

class Errant_Generics_MethodScoring_4 {
  class A{}
  class B{}

  class P{}
  interface Q extends Serializable {}
  abstract class R extends java.lang.Number {}

  var pp : P
  var qq : Q
  var rr : R

  var aList : ArrayList
  var aListInt : ArrayList<Integer>
  var aListLong : ArrayList<Double>

  var intArray : int[]
  var intObjArray : Integer[]
  var longArray : long[]
  var longObjArray : Long[]

  function foo4<T>(p: List<T>, i: int) : A {return null}
  function foo4<T extends Serializable>(p: List<T>, i: long) : B {return null}

  function caller() {
    var a1110 : A =  foo4({1,2,3}, 42)
    var a1111 : A =  foo4({1,2,3}, new Integer(42))
    var a1112 : A =  foo4(aList, 42)
    var a1113 : A =  foo4(aListInt, 42)
    var a1114 : A =  foo4(intArray, 42)            //## issuekeys: 'FOO4(JAVA.UTIL.LIST<JAVA.LANG.OBJECT>, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_4' CANNOT BE APPLIED TO '(INT[], INT)'
    var a1115 : A =  foo4({pp, pp}, 42)
    var a1116 : A =  foo4({qq, qq}, 42)
    var a1117 : A =  foo4({rr, rr}, 42)

    var a2110 : A =  foo4({1,2,3}, 42L)            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_4.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_4.A'
    var a2111 : A =  foo4({1,2,3}, new Long(42))            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_4.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_4.A'
    var a2112 : A =  foo4(aList, 42L)            //## issuekeys: INFERRED TYPE 'JAVA.LANG.OBJECT' FOR TYPE PARAMETER 'T' IS NOT WITHIN ITS BOUND; SHOULD IMPLEMENT 'JAVA.IO.SERIALIZABLE'
    var a2113 : A =  foo4(aListInt, 42L)            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_4.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_4.A'
    var a2114 : A =  foo4(intArray, 42L)            //## issuekeys: 'FOO4(JAVA.UTIL.LIST<JAVA.IO.SERIALIZABLE>, LONG)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_4' CANNOT BE APPLIED TO '(INT[], LONG)'
    var a2115 : A =  foo4({pp, pp}, 42L)            //## issuekeys: INFERRED TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_4.P' FOR TYPE PARAMETER 'T' IS NOT WITHIN ITS BOUND; SHOULD IMPLEMENT 'JAVA.IO.SERIALIZABLE'
    var a2116 : A =  foo4({qq, qq}, 42L)            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_4.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_4.A'
    var a2117 : A =  foo4({rr, rr}, 42L)            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_4.B', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_4.A'

    var b1110 : B =  foo4({1,2,3}, 42)            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_4.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_4.B'
    var b1111 : B =  foo4({1,2,3}, new Integer(42))            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_4.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_4.B'
    var b1112 : B =  foo4(aList, 42)            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_4.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_4.B'
    var b1113 : B =  foo4(aListInt, 42)            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_4.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_4.B'
    var b1114 : B =  foo4(intArray, 42)            //## issuekeys: 'FOO4(JAVA.UTIL.LIST<JAVA.LANG.OBJECT>, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_4' CANNOT BE APPLIED TO '(INT[], INT)'
    var b1115 : B =  foo4({pp, pp}, 42)            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_4.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_4.B'
    var b1116 : B =  foo4({qq, qq}, 42)            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_4.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_4.B'
    var b1117 : B =  foo4({rr, rr}, 42)            //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_4.A', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_4.B'

    var b2110 : B =  foo4({1,2,3}, 42L)
    var b2111 : B =  foo4({1,2,3}, new Long(42))
    var b2112 : B =  foo4(aList, 42L)            //## issuekeys: INFERRED TYPE 'JAVA.LANG.OBJECT' FOR TYPE PARAMETER 'T' IS NOT WITHIN ITS BOUND; SHOULD IMPLEMENT 'JAVA.IO.SERIALIZABLE'
    var b2113 : B =  foo4(aListInt, 42L)
    var b2114 : B =  foo4(intArray, 42L)            //## issuekeys: 'FOO4(JAVA.UTIL.LIST<JAVA.IO.SERIALIZABLE>, LONG)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_4' CANNOT BE APPLIED TO '(INT[], LONG)'
    var b2115 : B =  foo4({pp, pp}, 42L)            //## issuekeys: INFERRED TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_4.P' FOR TYPE PARAMETER 'T' IS NOT WITHIN ITS BOUND; SHOULD IMPLEMENT 'JAVA.IO.SERIALIZABLE'
    var b2116 : B =  foo4({qq, qq}, 42L)
    var b2117 : B =  foo4({rr, rr}, 42L)

    var c1110 =  foo4({1,2,3}, 42)
    var c1111 =  foo4({1,2,3}, new Integer(42))
    var c1112 =  foo4(aList, 42)
    var c1113 =  foo4(aListInt, 42)
    var c1114 =  foo4(intArray, 42)            //## issuekeys: 'FOO4(JAVA.UTIL.LIST<JAVA.LANG.OBJECT>, INT)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_4' CANNOT BE APPLIED TO '(INT[], INT)'
    var c1115 =  foo4({pp, pp}, 42)
    var c1116 =  foo4({qq, qq}, 42)
    var c1117 =  foo4({rr, rr}, 42)

    var c2110 =  foo4({1,2,3}, 42L)
    var c2111 =  foo4({1,2,3}, new Long(42))
    var c2112 =  foo4(aList, 42L)            //## issuekeys: INFERRED TYPE 'JAVA.LANG.OBJECT' FOR TYPE PARAMETER 'T' IS NOT WITHIN ITS BOUND; SHOULD IMPLEMENT 'JAVA.IO.SERIALIZABLE'
    var c2113 =  foo4(aListInt, 42L)
    var c2114 =  foo4(intArray, 42L)            //## issuekeys: 'FOO4(JAVA.UTIL.LIST<JAVA.IO.SERIALIZABLE>, LONG)' IN 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_4' CANNOT BE APPLIED TO '(INT[], LONG)'
    var c2115 =  foo4({pp, pp}, 42L)            //## issuekeys: INFERRED TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.GENERICS_METHODSCORING.GENERICS_METHODSCORING_4.P' FOR TYPE PARAMETER 'T' IS NOT WITHIN ITS BOUND; SHOULD IMPLEMENT 'JAVA.IO.SERIALIZABLE'
    var c2116 =  foo4({qq, qq}, 42L)
    var c2117 =  foo4({rr, rr}, 42L)
 }
}