package gw.internal.schema.gw.xsd.w3c.soap11_envelope;

/***************************************************************************/
/* THIS IS AUTOGENERATED CODE - DO NOT MODIFY OR YOUR CHANGES WILL BE LOST */
/* THIS CODE CAN BE REGENERATED USING 'xsd-codegen'                        */
/***************************************************************************/
public class Fault extends gw.xml.XmlElement implements gw.internal.xml.IXmlGeneratedClass {

  public static final javax.xml.namespace.QName $ELEMENT_QNAME_Detail = new javax.xml.namespace.QName( "", "detail", "" );
  public static final javax.xml.namespace.QName $ELEMENT_QNAME_Faultactor = new javax.xml.namespace.QName( "", "faultactor", "" );
  public static final javax.xml.namespace.QName $ELEMENT_QNAME_Faultcode = new javax.xml.namespace.QName( "", "faultcode", "" );
  public static final javax.xml.namespace.QName $ELEMENT_QNAME_Faultstring = new javax.xml.namespace.QName( "", "faultstring", "" );
  public static final javax.xml.namespace.QName $QNAME = new javax.xml.namespace.QName( "http://schemas.xmlsoap.org/soap/envelope/", "Fault", "tns" );
  public static final gw.util.concurrent.LockingLazyVar<gw.lang.reflect.IType> TYPE = new gw.util.concurrent.LockingLazyVar<gw.lang.reflect.IType>( gw.lang.reflect.TypeSystem.getGlobalLock() ) {
          @Override
          protected gw.lang.reflect.IType init() {
            return gw.lang.reflect.TypeSystem.getByFullName( "gw.xsd.w3c.soap11_envelope.Fault" );
          }
        };
  private static final gw.util.concurrent.LockingLazyVar<gw.lang.reflect.IType> TYPEINSTANCETYPE = new gw.util.concurrent.LockingLazyVar<gw.lang.reflect.IType>( gw.lang.reflect.TypeSystem.getGlobalLock() ) {
          @Override
          protected gw.lang.reflect.IType init() {
            return gw.lang.reflect.TypeSystem.getByFullName( "gw.xsd.w3c.soap11_envelope.types.complex.Fault" );
          }
        };

  public Fault() {
    this( new gw.internal.schema.gw.xsd.w3c.soap11_envelope.types.complex.Fault() );
  }

  public Fault( gw.internal.schema.gw.xsd.w3c.soap11_envelope.types.complex.Fault typeInstance ) {
    super( $QNAME, TYPE.get(), TYPEINSTANCETYPE.get(), typeInstance );
  }

  protected Fault( javax.xml.namespace.QName qname, gw.lang.reflect.IType type, gw.lang.reflect.IType schemaDefinedTypeInstanceType, gw.internal.schema.gw.xsd.w3c.xmlschema.types.complex.AnyType typeInstance ) {
    super( qname, type, schemaDefinedTypeInstanceType, typeInstance );
  }


  public gw.internal.schema.gw.xsd.w3c.soap11_envelope.types.complex.Fault getTypeInstance() {
    //noinspection RedundantCast
    return (gw.internal.schema.gw.xsd.w3c.soap11_envelope.types.complex.Fault) super.getTypeInstance();
  }

  public void setTypeInstance( gw.internal.schema.gw.xsd.w3c.soap11_envelope.types.complex.Fault param ) {
    super.setTypeInstance( param );
  }


  public gw.internal.schema.gw.xsd.w3c.soap11_envelope.anonymous.elements.Fault_Detail Detail() {
    return (gw.internal.schema.gw.xsd.w3c.soap11_envelope.anonymous.elements.Fault_Detail) TYPE.get().getTypeInfo().getProperty( "Detail" ).getAccessor().getValue( this );
  }

  public void setDetail$( gw.internal.schema.gw.xsd.w3c.soap11_envelope.anonymous.elements.Fault_Detail param ) {
    TYPE.get().getTypeInfo().getProperty( "Detail" ).getAccessor().setValue( this, param );
  }


  public java.net.URI Faultactor() {
    return (java.net.URI) TYPE.get().getTypeInfo().getProperty( "Faultactor" ).getAccessor().getValue( this );
  }

  public void setFaultactor$( java.net.URI param ) {
    TYPE.get().getTypeInfo().getProperty( "Faultactor" ).getAccessor().setValue( this, param );
  }


  public gw.internal.schema.gw.xsd.w3c.soap11_envelope.anonymous.elements.Fault_Faultactor Faultactor_elem() {
    return (gw.internal.schema.gw.xsd.w3c.soap11_envelope.anonymous.elements.Fault_Faultactor) TYPE.get().getTypeInfo().getProperty( "Faultactor_elem" ).getAccessor().getValue( this );
  }

  public void setFaultactor_elem$( gw.internal.schema.gw.xsd.w3c.soap11_envelope.anonymous.elements.Fault_Faultactor param ) {
    TYPE.get().getTypeInfo().getProperty( "Faultactor_elem" ).getAccessor().setValue( this, param );
  }


  public javax.xml.namespace.QName Faultcode() {
    return (javax.xml.namespace.QName) TYPE.get().getTypeInfo().getProperty( "Faultcode" ).getAccessor().getValue( this );
  }

  public void setFaultcode$( javax.xml.namespace.QName param ) {
    TYPE.get().getTypeInfo().getProperty( "Faultcode" ).getAccessor().setValue( this, param );
  }


  public gw.internal.schema.gw.xsd.w3c.soap11_envelope.anonymous.elements.Fault_Faultcode Faultcode_elem() {
    return (gw.internal.schema.gw.xsd.w3c.soap11_envelope.anonymous.elements.Fault_Faultcode) TYPE.get().getTypeInfo().getProperty( "Faultcode_elem" ).getAccessor().getValue( this );
  }

  public void setFaultcode_elem$( gw.internal.schema.gw.xsd.w3c.soap11_envelope.anonymous.elements.Fault_Faultcode param ) {
    TYPE.get().getTypeInfo().getProperty( "Faultcode_elem" ).getAccessor().setValue( this, param );
  }


  public java.lang.String Faultstring() {
    return (java.lang.String) TYPE.get().getTypeInfo().getProperty( "Faultstring" ).getAccessor().getValue( this );
  }

  public void setFaultstring$( java.lang.String param ) {
    TYPE.get().getTypeInfo().getProperty( "Faultstring" ).getAccessor().setValue( this, param );
  }


  public gw.internal.schema.gw.xsd.w3c.soap11_envelope.anonymous.elements.Fault_Faultstring Faultstring_elem() {
    return (gw.internal.schema.gw.xsd.w3c.soap11_envelope.anonymous.elements.Fault_Faultstring) TYPE.get().getTypeInfo().getProperty( "Faultstring_elem" ).getAccessor().getValue( this );
  }

  public void setFaultstring_elem$( gw.internal.schema.gw.xsd.w3c.soap11_envelope.anonymous.elements.Fault_Faultstring param ) {
    TYPE.get().getTypeInfo().getProperty( "Faultstring_elem" ).getAccessor().setValue( this, param );
  }

  public static gw.internal.schema.gw.xsd.w3c.soap11_envelope.Fault parse( byte[] byteArray ) {
    //noinspection RedundantArrayCreation
    return (gw.internal.schema.gw.xsd.w3c.soap11_envelope.Fault) TYPE.get().getTypeInfo().getMethod( "parse", gw.lang.reflect.TypeSystem.get( byte[].class ) ).getCallHandler().handleCall( null, new java.lang.Object[] { byteArray } );
  }

  public static gw.internal.schema.gw.xsd.w3c.soap11_envelope.Fault parse( byte[] byteArray, gw.xml.XmlParseOptions options ) {
    //noinspection RedundantArrayCreation
    return (gw.internal.schema.gw.xsd.w3c.soap11_envelope.Fault) TYPE.get().getTypeInfo().getMethod( "parse", gw.lang.reflect.TypeSystem.get( byte[].class ), gw.lang.reflect.TypeSystem.get( gw.xml.XmlParseOptions.class ) ).getCallHandler().handleCall( null, new java.lang.Object[] { byteArray, options } );
  }

  public static gw.internal.schema.gw.xsd.w3c.soap11_envelope.Fault parse( java.io.File file ) {
    //noinspection RedundantArrayCreation
    return (gw.internal.schema.gw.xsd.w3c.soap11_envelope.Fault) TYPE.get().getTypeInfo().getMethod( "parse", gw.lang.reflect.TypeSystem.get( java.io.File.class ) ).getCallHandler().handleCall( null, new java.lang.Object[] { file } );
  }

  public static gw.internal.schema.gw.xsd.w3c.soap11_envelope.Fault parse( java.io.File file, gw.xml.XmlParseOptions options ) {
    //noinspection RedundantArrayCreation
    return (gw.internal.schema.gw.xsd.w3c.soap11_envelope.Fault) TYPE.get().getTypeInfo().getMethod( "parse", gw.lang.reflect.TypeSystem.get( java.io.File.class ), gw.lang.reflect.TypeSystem.get( gw.xml.XmlParseOptions.class ) ).getCallHandler().handleCall( null, new java.lang.Object[] { file, options } );
  }

  public static gw.internal.schema.gw.xsd.w3c.soap11_envelope.Fault parse( java.io.InputStream inputStream ) {
    //noinspection RedundantArrayCreation
    return (gw.internal.schema.gw.xsd.w3c.soap11_envelope.Fault) TYPE.get().getTypeInfo().getMethod( "parse", gw.lang.reflect.TypeSystem.get( java.io.InputStream.class ) ).getCallHandler().handleCall( null, new java.lang.Object[] { inputStream } );
  }

  public static gw.internal.schema.gw.xsd.w3c.soap11_envelope.Fault parse( java.io.InputStream inputStream, gw.xml.XmlParseOptions options ) {
    //noinspection RedundantArrayCreation
    return (gw.internal.schema.gw.xsd.w3c.soap11_envelope.Fault) TYPE.get().getTypeInfo().getMethod( "parse", gw.lang.reflect.TypeSystem.get( java.io.InputStream.class ), gw.lang.reflect.TypeSystem.get( gw.xml.XmlParseOptions.class ) ).getCallHandler().handleCall( null, new java.lang.Object[] { inputStream, options } );
  }

  public static gw.internal.schema.gw.xsd.w3c.soap11_envelope.Fault parse( java.io.Reader reader ) {
    //noinspection RedundantArrayCreation
    return (gw.internal.schema.gw.xsd.w3c.soap11_envelope.Fault) TYPE.get().getTypeInfo().getMethod( "parse", gw.lang.reflect.TypeSystem.get( java.io.Reader.class ) ).getCallHandler().handleCall( null, new java.lang.Object[] { reader } );
  }

  public static gw.internal.schema.gw.xsd.w3c.soap11_envelope.Fault parse( java.io.Reader reader, gw.xml.XmlParseOptions options ) {
    //noinspection RedundantArrayCreation
    return (gw.internal.schema.gw.xsd.w3c.soap11_envelope.Fault) TYPE.get().getTypeInfo().getMethod( "parse", gw.lang.reflect.TypeSystem.get( java.io.Reader.class ), gw.lang.reflect.TypeSystem.get( gw.xml.XmlParseOptions.class ) ).getCallHandler().handleCall( null, new java.lang.Object[] { reader, options } );
  }

  public static gw.internal.schema.gw.xsd.w3c.soap11_envelope.Fault parse( java.lang.String xmlString ) {
    //noinspection RedundantArrayCreation
    return (gw.internal.schema.gw.xsd.w3c.soap11_envelope.Fault) TYPE.get().getTypeInfo().getMethod( "parse", gw.lang.reflect.TypeSystem.get( java.lang.String.class ) ).getCallHandler().handleCall( null, new java.lang.Object[] { xmlString } );
  }

  public static gw.internal.schema.gw.xsd.w3c.soap11_envelope.Fault parse( java.lang.String xmlString, gw.xml.XmlParseOptions options ) {
    //noinspection RedundantArrayCreation
    return (gw.internal.schema.gw.xsd.w3c.soap11_envelope.Fault) TYPE.get().getTypeInfo().getMethod( "parse", gw.lang.reflect.TypeSystem.get( java.lang.String.class ), gw.lang.reflect.TypeSystem.get( gw.xml.XmlParseOptions.class ) ).getCallHandler().handleCall( null, new java.lang.Object[] { xmlString, options } );
  }

  public static gw.internal.schema.gw.xsd.w3c.soap11_envelope.Fault parse( java.net.URL url ) {
    //noinspection RedundantArrayCreation
    return (gw.internal.schema.gw.xsd.w3c.soap11_envelope.Fault) TYPE.get().getTypeInfo().getMethod( "parse", gw.lang.reflect.TypeSystem.get( java.net.URL.class ) ).getCallHandler().handleCall( null, new java.lang.Object[] { url } );
  }

  public static gw.internal.schema.gw.xsd.w3c.soap11_envelope.Fault parse( java.net.URL url, gw.xml.XmlParseOptions options ) {
    //noinspection RedundantArrayCreation
    return (gw.internal.schema.gw.xsd.w3c.soap11_envelope.Fault) TYPE.get().getTypeInfo().getMethod( "parse", gw.lang.reflect.TypeSystem.get( java.net.URL.class ), gw.lang.reflect.TypeSystem.get( gw.xml.XmlParseOptions.class ) ).getCallHandler().handleCall( null, new java.lang.Object[] { url, options } );
  }

  @SuppressWarnings( {"UnusedDeclaration"} )
  private static final long FINGERPRINT = -8874048065522269573L;

}
