package gw.internal.schema.gw.xsd.w3c.xmlschema.anonymous.types.simple;

/***************************************************************************/
/* THIS IS AUTOGENERATED CODE - DO NOT MODIFY OR YOUR CHANGES WILL BE LOST */
/* THIS CODE CAN BE REGENERATED USING 'xsd-codegen'                        */
/***************************************************************************/
public class All_MinOccurs extends gw.internal.schema.gw.xsd.w3c.xmlschema.types.simple.NonNegativeInteger implements gw.internal.xml.IXmlGeneratedClass {

  public static final gw.util.concurrent.LockingLazyVar<gw.lang.reflect.IType> TYPE = new gw.util.concurrent.LockingLazyVar<gw.lang.reflect.IType>( gw.lang.reflect.TypeSystem.getGlobalLock() ) {
          @Override
          protected gw.lang.reflect.IType init() {
            return gw.lang.reflect.TypeSystem.getByFullName( "gw.xsd.w3c.xmlschema.anonymous.types.simple.All_MinOccurs" );
          }
        };
  private static final gw.util.concurrent.LockingLazyVar<java.lang.Object> SCHEMAINFO = new gw.util.concurrent.LockingLazyVar<java.lang.Object>( gw.lang.reflect.TypeSystem.getGlobalLock() ) {
          @Override
          protected java.lang.Object init() {
            gw.lang.reflect.IType type = TYPE.get();
            return getSchemaInfoByType( type );
          }
        };

  public All_MinOccurs() {
    super( TYPE.get(), SCHEMAINFO.get() );
  }

  protected All_MinOccurs( gw.lang.reflect.IType type, java.lang.Object schemaInfo ) {
    super( type, schemaInfo );
  }

  public All_MinOccurs( gw.internal.schema.gw.xsd.w3c.xmlschema.enums.All_MinOccurs value ) {
    this();
    TYPE.get().getTypeInfo().getProperty( "$Value" ).getAccessor().setValue( this, value );
  }


  @Deprecated
  public java.math.BigInteger getValue$$gw_xsd_w3c_xmlschema_types_simple_NonNegativeInteger() {
    return super.getValue$$gw_xsd_w3c_xmlschema_types_simple_NonNegativeInteger();
  }

  @Deprecated
  public void setValue$$gw_xsd_w3c_xmlschema_types_simple_NonNegativeInteger( java.math.BigInteger param ) {
    super.setValue$$gw_xsd_w3c_xmlschema_types_simple_NonNegativeInteger( param );
  }

  public gw.internal.schema.gw.xsd.w3c.xmlschema.enums.All_MinOccurs getValue$$gw_xsd_w3c_xmlschema_anonymous_types_simple_All_MinOccurs() {
    return (gw.internal.schema.gw.xsd.w3c.xmlschema.enums.All_MinOccurs) TYPE.get().getTypeInfo().getProperty( "$Value" ).getAccessor().getValue( this );
  }

  public void setValue$$gw_xsd_w3c_xmlschema_anonymous_types_simple_All_MinOccurs( gw.internal.schema.gw.xsd.w3c.xmlschema.enums.All_MinOccurs param ) {
    TYPE.get().getTypeInfo().getProperty( "$Value" ).getAccessor().setValue( this, param );
  }

  @SuppressWarnings( {"UnusedDeclaration"} )
  private static final long FINGERPRINT = 2110283714877373226L;

}
