package gw.specContrib.initializers.arrayListInitializers

uses java.math.BigDecimal
uses java.math.BigInteger
uses java.util.ArrayList
uses java.util.HashMap

class Errant_BigIntegerArrayListInitializer {
  class A{}
  class B{}
  var d1 : DateTime
  var d2 : DateTime
  var o : Object
  var aaa : A
  var bbb : B
  var arrayList : ArrayList
  var hashMap : HashMap

  var bigIntegerArrayList0111 : ArrayList<BigInteger> = {'c', 1b, 1s, 42, 42L}
  var bigIntegerArrayList0112 : ArrayList<BigInteger> = {'c', 1b, 1s, 42, 42.5f, 42L}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.FLOAT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList0113 : ArrayList<BigInteger> = {'c', 1b, 1s, 42, 42.5f, 42L, 42.5}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.DOUBLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList0114 : ArrayList<BigInteger> = {'c', 1b, 1s, 42, 42L, BigInteger.ONE}
  var bigIntegerArrayList0115 : ArrayList<BigInteger> = {'c', 1b, 1s, 42, 42.5f, 42L, 42.5, BigInteger.ONE, BigDecimal.TEN}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'


  var bigIntegerArrayList1111 : ArrayList<BigInteger> = {'c', 'c'}
  var bigIntegerArrayList1110 : ArrayList<BigInteger> = {'c', 1b}
  var bigIntegerArrayList1112 : ArrayList<BigInteger> = {'c', 1s}
  var bigIntegerArrayList1113 : ArrayList<BigInteger> = {'c', 42}
  var bigIntegerArrayList1114 : ArrayList<BigInteger> = {'c', 42.5f}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.FLOAT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1115 : ArrayList<BigInteger> = {'c', 42.5}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.DOUBLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1116 : ArrayList<BigInteger> = {'c', BigInteger.ONE}
  var bigIntegerArrayList1117 : ArrayList<BigInteger> = {'c', BigDecimal.TEN}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1118 : ArrayList<BigInteger> = {'c', d1}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1119 : ArrayList<BigInteger> = {'c', o}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1120 : ArrayList<BigInteger> = {'c', aaa}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1121 : ArrayList<BigInteger> = {'c', "mystring"}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1122 : ArrayList<BigInteger> = {'c', arrayList}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1123 : ArrayList<BigInteger> = {'c', hashMap}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'

  var bigIntegerArrayList1211 : ArrayList<BigInteger> = {1b, 'c'}
  var bigIntegerArrayList1210 : ArrayList<BigInteger> = {1b, 1b}
  var bigIntegerArrayList1212 : ArrayList<BigInteger> = {1b, 1s}
  var bigIntegerArrayList1213 : ArrayList<BigInteger> = {1b, 42}
  var bigIntegerArrayList1214 : ArrayList<BigInteger> = {1b, 42.5f}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.FLOAT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1215 : ArrayList<BigInteger> = {1b, 42.5}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.DOUBLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1216 : ArrayList<BigInteger> = {1b, BigInteger.ONE}
  var bigIntegerArrayList1217 : ArrayList<BigInteger> = {1b, BigDecimal.TEN}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.NUMBER & JAVA.LANG.COMPARABLE<JAVA.LANG.NUMBER & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1218 : ArrayList<BigInteger> = {1b, d1}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1219 : ArrayList<BigInteger> = {1b, o}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1220 : ArrayList<BigInteger> = {1b, aaa}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1221 : ArrayList<BigInteger> = {1b, "mystring"}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1222 : ArrayList<BigInteger> = {1b, arrayList}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1223 : ArrayList<BigInteger> = {1b, hashMap}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'

  var bigIntegerArrayList1311 : ArrayList<BigInteger> = {1s, 'c'}
  var bigIntegerArrayList1310 : ArrayList<BigInteger> = {1s, 1b}
  var bigIntegerArrayList1312 : ArrayList<BigInteger> = {1s, 1s}
  var bigIntegerArrayList1313 : ArrayList<BigInteger> = {1s, 42}
  var bigIntegerArrayList1314 : ArrayList<BigInteger> = {1s, 42.5f}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.FLOAT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1315 : ArrayList<BigInteger> = {1s, 42.5}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.DOUBLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1316 : ArrayList<BigInteger> = {1s, BigInteger.ONE}
  var bigIntegerArrayList1317 : ArrayList<BigInteger> = {1s, BigDecimal.TEN}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.NUMBER & JAVA.LANG.COMPARABLE<JAVA.LANG.NUMBER & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1318 : ArrayList<BigInteger> = {1s, d1}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1319 : ArrayList<BigInteger> = {1s, o}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1320 : ArrayList<BigInteger> = {1s, aaa}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1321 : ArrayList<BigInteger> = {1s, "mystring"}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1322 : ArrayList<BigInteger> = {1s, arrayList}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1323 : ArrayList<BigInteger> = {1s, hashMap}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'


  var bigIntegerArrayList1411 : ArrayList<BigInteger> = {42, 'c'}
  var bigIntegerArrayList1410 : ArrayList<BigInteger> = {42, 1b}
  var bigIntegerArrayList1412 : ArrayList<BigInteger> = {42, 1s}
  var bigIntegerArrayList1413 : ArrayList<BigInteger> = {42, 42}
  var bigIntegerArrayList1414 : ArrayList<BigInteger> = {42, 42.5f}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.FLOAT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1415 : ArrayList<BigInteger> = {42, 42.5}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.DOUBLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1416 : ArrayList<BigInteger> = {42, BigInteger.ONE}
  var bigIntegerArrayList1417 : ArrayList<BigInteger> = {42, BigDecimal.TEN}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.NUMBER & JAVA.LANG.COMPARABLE<JAVA.LANG.NUMBER & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1418 : ArrayList<BigInteger> = {42, d1}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1419 : ArrayList<BigInteger> = {42, o}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1420 : ArrayList<BigInteger> = {42, aaa}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1421 : ArrayList<BigInteger> = {42, "mystring"}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1422 : ArrayList<BigInteger> = {42, arrayList}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1423 : ArrayList<BigInteger> = {42, hashMap}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'

  var bigIntegerArrayList1511 : ArrayList<BigInteger> = {42.5f, 'c'}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.FLOAT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1510 : ArrayList<BigInteger> = {42.5f, 1b}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.FLOAT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1512 : ArrayList<BigInteger> = {42.5f, 1s}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.FLOAT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1513 : ArrayList<BigInteger> = {42.5f, 42}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.FLOAT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1514 : ArrayList<BigInteger> = {42.5f, 42.5f}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.FLOAT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1515 : ArrayList<BigInteger> = {42.5f, 42.5}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.DOUBLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1516 : ArrayList<BigInteger> = {42.5f, BigInteger.ONE}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.NUMBER & JAVA.LANG.COMPARABLE<JAVA.LANG.NUMBER & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1517 : ArrayList<BigInteger> = {42.5f, BigDecimal.TEN}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.NUMBER & JAVA.LANG.COMPARABLE<JAVA.LANG.NUMBER & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1518 : ArrayList<BigInteger> = {42.5f, d1}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1519 : ArrayList<BigInteger> = {42.5f, o}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1520 : ArrayList<BigInteger> = {42.5f, aaa}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1521 : ArrayList<BigInteger> = {42.5f, "mystring"}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1522 : ArrayList<BigInteger> = {42.5f, arrayList}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1523 : ArrayList<BigInteger> = {42.5f, hashMap}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'

  var bigIntegerArrayList1611 : ArrayList<BigInteger> = {42.5, 'c'}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.DOUBLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1610 : ArrayList<BigInteger> = {42.5, 1b}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.DOUBLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1612 : ArrayList<BigInteger> = {42.5, 1s}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.DOUBLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1613 : ArrayList<BigInteger> = {42.5, 42}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.DOUBLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1614 : ArrayList<BigInteger> = {42.5, 42.5f}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.DOUBLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1615 : ArrayList<BigInteger> = {42.5, 42.5}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.DOUBLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1616 : ArrayList<BigInteger> = {42.5, BigInteger.ONE}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.NUMBER & JAVA.LANG.COMPARABLE<JAVA.LANG.NUMBER & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1617 : ArrayList<BigInteger> = {42.5, BigDecimal.TEN}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.NUMBER & JAVA.LANG.COMPARABLE<JAVA.LANG.NUMBER & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1618 : ArrayList<BigInteger> = {42.5, d1}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1619 : ArrayList<BigInteger> = {42.5, o}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1620 : ArrayList<BigInteger> = {42.5, aaa}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1621 : ArrayList<BigInteger> = {42.5, "mystring"}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1622 : ArrayList<BigInteger> = {42.5, arrayList}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1623 : ArrayList<BigInteger> = {42.5, hashMap}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'

  var bigIntegerArrayList1711 : ArrayList<BigInteger> = {BigInteger.ONE, 'c'}
  var bigIntegerArrayList1710 : ArrayList<BigInteger> = {BigInteger.ONE, 1b}
  var bigIntegerArrayList1712 : ArrayList<BigInteger> = {BigInteger.ONE, 1s}
  var bigIntegerArrayList1713 : ArrayList<BigInteger> = {BigInteger.ONE, 42}
  var bigIntegerArrayList1714 : ArrayList<BigInteger> = {BigInteger.ONE, 42.5f}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.NUMBER & JAVA.LANG.COMPARABLE<JAVA.LANG.NUMBER & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1715 : ArrayList<BigInteger> = {BigInteger.ONE, 42.5}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.NUMBER & JAVA.LANG.COMPARABLE<JAVA.LANG.NUMBER & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1716 : ArrayList<BigInteger> = {BigInteger.ONE, BigInteger.ONE}
  var bigIntegerArrayList1717 : ArrayList<BigInteger> = {BigInteger.ONE, BigDecimal.TEN}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.NUMBER & JAVA.LANG.COMPARABLE<JAVA.LANG.NUMBER & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1718 : ArrayList<BigInteger> = {BigInteger.ONE, d1}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1719 : ArrayList<BigInteger> = {BigInteger.ONE, o}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1720 : ArrayList<BigInteger> = {BigInteger.ONE, aaa}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1721 : ArrayList<BigInteger> = {BigInteger.ONE, "mystring"}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1722 : ArrayList<BigInteger> = {BigInteger.ONE, arrayList}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1723 : ArrayList<BigInteger> = {BigInteger.ONE, hashMap}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'

  var bigIntegerArrayList1811 : ArrayList<BigInteger> = {BigDecimal.TEN, 'c'}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1810 : ArrayList<BigInteger> = {BigDecimal.TEN, 1b}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.NUMBER & JAVA.LANG.COMPARABLE<JAVA.LANG.NUMBER & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1812 : ArrayList<BigInteger> = {BigDecimal.TEN, 1s}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.NUMBER & JAVA.LANG.COMPARABLE<JAVA.LANG.NUMBER & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1813 : ArrayList<BigInteger> = {BigDecimal.TEN, 42}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.NUMBER & JAVA.LANG.COMPARABLE<JAVA.LANG.NUMBER & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1814 : ArrayList<BigInteger> = {BigDecimal.TEN, 42.5f}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.NUMBER & JAVA.LANG.COMPARABLE<JAVA.LANG.NUMBER & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1815 : ArrayList<BigInteger> = {BigDecimal.TEN, 42.5}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.NUMBER & JAVA.LANG.COMPARABLE<JAVA.LANG.NUMBER & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1816 : ArrayList<BigInteger> = {BigDecimal.TEN, BigInteger.ONE}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.NUMBER & JAVA.LANG.COMPARABLE<JAVA.LANG.NUMBER & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1817 : ArrayList<BigInteger> = {BigDecimal.TEN, BigDecimal.TEN}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGDECIMAL>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1818 : ArrayList<BigInteger> = {BigDecimal.TEN, d1}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1819 : ArrayList<BigInteger> = {BigDecimal.TEN, o}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1820 : ArrayList<BigInteger> = {BigDecimal.TEN, aaa}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1821 : ArrayList<BigInteger> = {BigDecimal.TEN, "mystring"}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1822 : ArrayList<BigInteger> = {BigDecimal.TEN, arrayList}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1823 : ArrayList<BigInteger> = {BigDecimal.TEN, hashMap}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'

  var bigIntegerArrayList1911 : ArrayList<BigInteger> = {d1, 'c'}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1910 : ArrayList<BigInteger> = {d1, 1b}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1912 : ArrayList<BigInteger> = {d1, 1s}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1913 : ArrayList<BigInteger> = {d1, 42}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1914 : ArrayList<BigInteger> = {d1, 42.5f}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1915 : ArrayList<BigInteger> = {d1, 42.5}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1916 : ArrayList<BigInteger> = {d1, BigInteger.ONE}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1917 : ArrayList<BigInteger> = {d1, BigDecimal.TEN}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1918 : ArrayList<BigInteger> = {d1, d1}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.UTIL.DATE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1919 : ArrayList<BigInteger> = {d1, o}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1920 : ArrayList<BigInteger> = {d1, aaa}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1921 : ArrayList<BigInteger> = {d1, "mystring"}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1922 : ArrayList<BigInteger> = {d1, arrayList}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.CLONEABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList1923 : ArrayList<BigInteger> = {d1, hashMap}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.CLONEABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'

  var bigIntegerArrayList2011 : ArrayList<BigInteger> = {o, 'c'}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2010 : ArrayList<BigInteger> = {o, 1b}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2012 : ArrayList<BigInteger> = {o, 1s}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2013 : ArrayList<BigInteger> = {o, 42}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2014 : ArrayList<BigInteger> = {o, 42.5f}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2015 : ArrayList<BigInteger> = {o, 42.5}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2016 : ArrayList<BigInteger> = {o, BigInteger.ONE}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2017 : ArrayList<BigInteger> = {o, BigDecimal.TEN}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2018 : ArrayList<BigInteger> = {o, d1}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2019 : ArrayList<BigInteger> = {o, o}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2020 : ArrayList<BigInteger> = {o, aaa}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2021 : ArrayList<BigInteger> = {o, "mystring"}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2022 : ArrayList<BigInteger> = {o, arrayList}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2023 : ArrayList<BigInteger> = {o, hashMap}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'

  var bigIntegerArrayList2111 : ArrayList<BigInteger> = {aaa, 'c'}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2110 : ArrayList<BigInteger> = {aaa, 1b}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2112 : ArrayList<BigInteger> = {aaa, 1s}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2113 : ArrayList<BigInteger> = {aaa, 42}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2114 : ArrayList<BigInteger> = {aaa, 42.5f}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2115 : ArrayList<BigInteger> = {aaa, 42.5}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2116 : ArrayList<BigInteger> = {aaa, BigInteger.ONE}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2117 : ArrayList<BigInteger> = {aaa, BigDecimal.TEN}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2118 : ArrayList<BigInteger> = {aaa, d1}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2119 : ArrayList<BigInteger> = {aaa, o}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2120 : ArrayList<BigInteger> = {aaa, aaa}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.INITIALIZERS.ARRAYLISTINITIALIZER.ERRANT_BIGINTEGERARRAYLISTINITIALIZER1.A>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2121 : ArrayList<BigInteger> = {aaa, "mystring"}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2122 : ArrayList<BigInteger> = {aaa, arrayList}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2123 : ArrayList<BigInteger> = {aaa, hashMap}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'

  var bigIntegerArrayList2211 : ArrayList<BigInteger> = {"mystring", 'c'}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2210 : ArrayList<BigInteger> = {"mystring", 1b}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2212 : ArrayList<BigInteger> = {"mystring", 1s}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2213 : ArrayList<BigInteger> = {"mystring", 42}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2214 : ArrayList<BigInteger> = {"mystring", 42.5f}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2215 : ArrayList<BigInteger> = {"mystring", 42.5}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2216 : ArrayList<BigInteger> = {"mystring", BigInteger.ONE}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2217 : ArrayList<BigInteger> = {"mystring", BigDecimal.TEN}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2218 : ArrayList<BigInteger> = {"mystring", d1}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<JAVA.IO.SERIALIZABLE & JAVA.LANG.COMPARABLE<? EXTENDS JAVA.LANG.COMPARABLE<?>>>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2219 : ArrayList<BigInteger> = {"mystring", o}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2220 : ArrayList<BigInteger> = {"mystring", aaa}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2221 : ArrayList<BigInteger> = {"mystring", "mystring"}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.STRING>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2222 : ArrayList<BigInteger> = {"mystring", arrayList}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2223 : ArrayList<BigInteger> = {"mystring", hashMap}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'


  var bigIntegerArrayList2311 : ArrayList<BigInteger> = {arrayList, 'c'}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2310 : ArrayList<BigInteger> = {arrayList, 1b}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2312 : ArrayList<BigInteger> = {arrayList, 1s}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2313 : ArrayList<BigInteger> = {arrayList, 42}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2314 : ArrayList<BigInteger> = {arrayList, 42.5f}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2315 : ArrayList<BigInteger> = {arrayList, 42.5}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2316 : ArrayList<BigInteger> = {arrayList, BigInteger.ONE}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2317 : ArrayList<BigInteger> = {arrayList, BigDecimal.TEN}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2318 : ArrayList<BigInteger> = {arrayList, d1}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.CLONEABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2319 : ArrayList<BigInteger> = {arrayList, o}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2320 : ArrayList<BigInteger> = {arrayList, aaa}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2321 : ArrayList<BigInteger> = {arrayList, "mystring"}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2322 : ArrayList<BigInteger> = {arrayList, arrayList}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2323 : ArrayList<BigInteger> = {arrayList, hashMap}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.CLONEABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'

  var bigIntegerArrayList2411 : ArrayList<BigInteger> = {hashMap, 'c'}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2410 : ArrayList<BigInteger> = {hashMap, 1b}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2412 : ArrayList<BigInteger> = {hashMap, 1s}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2413 : ArrayList<BigInteger> = {hashMap, 42}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2414 : ArrayList<BigInteger> = {hashMap, 42.5f}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2415 : ArrayList<BigInteger> = {hashMap, 42.5}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2416 : ArrayList<BigInteger> = {hashMap, BigInteger.ONE}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2417 : ArrayList<BigInteger> = {hashMap, BigDecimal.TEN}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2418 : ArrayList<BigInteger> = {hashMap, d1}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.CLONEABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2419 : ArrayList<BigInteger> = {hashMap, o}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2420 : ArrayList<BigInteger> = {hashMap, aaa}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.LANG.OBJECT>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2421 : ArrayList<BigInteger> = {hashMap, "mystring"}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2422 : ArrayList<BigInteger> = {hashMap, arrayList}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.IO.SERIALIZABLE & JAVA.LANG.CLONEABLE>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'
  var bigIntegerArrayList2423 : ArrayList<BigInteger> = {hashMap, hashMap}      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'JAVA.UTIL.ARRAYLIST<JAVA.UTIL.HASHMAP<JAVA.LANG.OBJECT,JAVA.LANG.OBJECT>>', REQUIRED: 'JAVA.UTIL.ARRAYLIST<JAVA.MATH.BIGINTEGER>'

}