package gw.internal.schema.gw.xsd.w3c.soap12_envelope.types.complex;

/***************************************************************************/
/* THIS IS AUTOGENERATED CODE - DO NOT MODIFY OR YOUR CHANGES WILL BE LOST */
/* THIS CODE CAN BE REGENERATED USING 'xsd-codegen'                        */
/***************************************************************************/
public class Envelope extends gw.internal.schema.gw.xsd.w3c.xmlschema.types.complex.AnyType implements gw.internal.xml.IXmlGeneratedClass {

  public static final javax.xml.namespace.QName $ELEMENT_QNAME_Body = new javax.xml.namespace.QName( "http://www.w3.org/2003/05/soap-envelope", "Body", "soap12" );
  public static final javax.xml.namespace.QName $ELEMENT_QNAME_Header = new javax.xml.namespace.QName( "http://www.w3.org/2003/05/soap-envelope", "Header", "soap12" );
  public static final javax.xml.namespace.QName $QNAME = new javax.xml.namespace.QName( "http://www.w3.org/2003/05/soap-envelope", "Envelope", "soap12" );
  public static final gw.util.concurrent.LockingLazyVar<gw.lang.reflect.IType> TYPE = new gw.util.concurrent.LockingLazyVar<gw.lang.reflect.IType>( gw.lang.reflect.TypeSystem.getGlobalLock() ) {
          @Override
          protected gw.lang.reflect.IType init() {
            return gw.lang.reflect.TypeSystem.getByFullName( "gw.xsd.w3c.soap12_envelope.types.complex.Envelope" );
          }
        };
  private static final gw.util.concurrent.LockingLazyVar<java.lang.Object> SCHEMAINFO = new gw.util.concurrent.LockingLazyVar<java.lang.Object>( gw.lang.reflect.TypeSystem.getGlobalLock() ) {
          @Override
          protected java.lang.Object init() {
            gw.lang.reflect.IType type = TYPE.get();
            return getSchemaInfoByType( type );
          }
        };

  public Envelope() {
    super( TYPE.get(), SCHEMAINFO.get() );
  }

  protected Envelope( gw.lang.reflect.IType type, java.lang.Object schemaInfo ) {
    super( type, schemaInfo );
  }


  public gw.internal.schema.gw.xsd.w3c.soap12_envelope.Body Body() {
    return (gw.internal.schema.gw.xsd.w3c.soap12_envelope.Body) TYPE.get().getTypeInfo().getProperty( "Body" ).getAccessor().getValue( this );
  }

  public void setBody$( gw.internal.schema.gw.xsd.w3c.soap12_envelope.Body param ) {
    TYPE.get().getTypeInfo().getProperty( "Body" ).getAccessor().setValue( this, param );
  }


  public gw.internal.schema.gw.xsd.w3c.soap12_envelope.Header Header() {
    return (gw.internal.schema.gw.xsd.w3c.soap12_envelope.Header) TYPE.get().getTypeInfo().getProperty( "Header" ).getAccessor().getValue( this );
  }

  public void setHeader$( gw.internal.schema.gw.xsd.w3c.soap12_envelope.Header param ) {
    TYPE.get().getTypeInfo().getProperty( "Header" ).getAccessor().setValue( this, param );
  }

  @SuppressWarnings( {"UnusedDeclaration"} )
  private static final long FINGERPRINT = -6014282781002754770L;

}
