package gw.specContrib.classes.method_Scoring.arrays_And_Lists

uses java.util.ArrayList

class Errant_ArrayListString {

  class AAA {
  }

  class BBB {
  }

  var strArray: String[] = {"g", "o", "s", "u"}
  var strList: List<String> = {"g", "o", "s", "u"}
  var strArrayList: ArrayList<String> = {"g", "o", "s", "u"}


  class ObjectArrayObjectList {
    function funOASL(o: Object[]): AAA {
      return null
    }

    function funOASL(o: List): BBB {
      return null
    }

    function caller() {
      var aa1: AAA = funOASL({"g", "o", "s", "u"})
      var aa2: AAA = funOASL(strArray)
      var aa3: AAA = funOASL(strList)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.BBB', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.AAA'
      var aa4: AAA = funOASL(strArrayList)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.BBB', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.AAA'

      var bb1: BBB = funOASL({"g", "o", "s", "u"})      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.AAA', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.BBB'
      var bb2: BBB = funOASL(strArray)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.AAA', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.BBB'
      var bb3: BBB = funOASL(strList)
      var bb4: BBB = funOASL(strArrayList)

      var cc1 = funOASL({"g", "o", "s", "u"})
      var cc2 = funOASL(strArray)
      var cc3 = funOASL(strList)
      var cc4 = funOASL(strArrayList)
    }
  }

  class ObjectArrayObjectArrayList {
    function funOASL(o: Object[]): AAA {
      return null
    }

    function funOASL(o: ArrayList): BBB {
      return null
    }

    function caller() {
      var aa1: AAA = funOASL({"g", "o", "s", "u"})      //## issuekeys: AMBIGUOUS METHOD CALL: BOTH 'OBJECTARRAYOBJECTARRAYLIST.FUNOASL(OBJECT[])' AND 'OBJECTARRAYOBJECTARRAYLIST.FUNOASL(ARRAYLIST)' MATCH
      var aa2: AAA = funOASL(strArray)
      var aa3: AAA = funOASL(strList)      //## issuekeys: CANNOT RESOLVE METHOD 'FUNOASL(JAVA.UTIL.LIST<JAVA.LANG.STRING>)'
      var aa4: AAA = funOASL(strArrayList)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.BBB', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.AAA'

      var bb1: BBB = funOASL({"g", "o", "s", "u"})      //## issuekeys: AMBIGUOUS METHOD CALL: BOTH 'OBJECTARRAYOBJECTARRAYLIST.FUNOASL(OBJECT[])' AND 'OBJECTARRAYOBJECTARRAYLIST.FUNOASL(ARRAYLIST)' MATCH
      var bb2: BBB = funOASL(strArray)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.AAA', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.BBB'
      var bb3: BBB = funOASL(strList)      //## issuekeys: CANNOT RESOLVE METHOD 'FUNOASL(JAVA.UTIL.LIST<JAVA.LANG.STRING>)'
      var bb4: BBB = funOASL(strArrayList)

      var cc1 = funOASL({"g", "o", "s", "u"})      //## issuekeys: AMBIGUOUS METHOD CALL: BOTH 'OBJECTARRAYOBJECTARRAYLIST.FUNOASL(OBJECT[])' AND 'OBJECTARRAYOBJECTARRAYLIST.FUNOASL(ARRAYLIST)' MATCH
      var cc2 = funOASL(strArray)
      var cc3 = funOASL(strList)      //## issuekeys: CANNOT RESOLVE METHOD 'FUNOASL(JAVA.UTIL.LIST<JAVA.LANG.STRING>)'
      var cc4 = funOASL(strArrayList)
    }
  }

  class ObjectArrayStringList {
    function funOASL(o: Object[]): AAA {
      return null
    }

    function funOASL(o: List<String>): BBB {
      return null
    }

    function caller() {
      var aa1: AAA = funOASL({"g", "o", "s", "u"})
      var aa2: AAA = funOASL(strArray)
      var aa3: AAA = funOASL(strList)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.BBB', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.AAA'
      var aa4: AAA = funOASL(strArrayList)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.BBB', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.AAA'

      var bb1: BBB = funOASL({"g", "o", "s", "u"})      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.AAA', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.BBB'
      var bb2: BBB = funOASL(strArray)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.AAA', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.BBB'
      var bb3: BBB = funOASL(strList)
      var bb4: BBB = funOASL(strArrayList)

      var cc1 = funOASL({"g", "o", "s", "u"})
      var cc2 = funOASL(strArray)
      var cc3 = funOASL(strList)
      var cc4 = funOASL(strArrayList)
    }
  }

  class ObjectArrayStringArrayList {
    function funOASL(o: Object[]): AAA {
      return null
    }

    function funOASL(o: ArrayList<String>): BBB {
      return null
    }

    function caller() {
      var aa1: AAA = funOASL({"g", "o", "s", "u"})      //## issuekeys: AMBIGUOUS METHOD CALL: BOTH 'OBJECTARRAYSTRINGARRAYLIST.FUNOASL(OBJECT[])' AND 'OBJECTARRAYSTRINGARRAYLIST.FUNOASL(ARRAYLIST<STRING>)' MATCH
      var aa2: AAA = funOASL(strArray)
      var aa3: AAA = funOASL(strList)      //## issuekeys: CANNOT RESOLVE METHOD 'FUNOASL(JAVA.UTIL.LIST<JAVA.LANG.STRING>)'
      var aa4: AAA = funOASL(strArrayList)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.BBB', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.AAA'

      var bb1: BBB = funOASL({"g", "o", "s", "u"})      //## issuekeys: AMBIGUOUS METHOD CALL: BOTH 'OBJECTARRAYSTRINGARRAYLIST.FUNOASL(OBJECT[])' AND 'OBJECTARRAYSTRINGARRAYLIST.FUNOASL(ARRAYLIST<STRING>)' MATCH
      var bb2: BBB = funOASL(strArray)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.AAA', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.BBB'
      var bb3: BBB = funOASL(strList)      //## issuekeys: CANNOT RESOLVE METHOD 'FUNOASL(JAVA.UTIL.LIST<JAVA.LANG.STRING>)'
      var bb4: BBB = funOASL(strArrayList)

      var cc1 = funOASL({"g", "o", "s", "u"})      //## issuekeys: AMBIGUOUS METHOD CALL: BOTH 'OBJECTARRAYSTRINGARRAYLIST.FUNOASL(OBJECT[])' AND 'OBJECTARRAYSTRINGARRAYLIST.FUNOASL(ARRAYLIST<STRING>)' MATCH
      var cc2 = funOASL(strArray)
      var cc3 = funOASL(strList)      //## issuekeys: CANNOT RESOLVE METHOD 'FUNOASL(JAVA.UTIL.LIST<JAVA.LANG.STRING>)'
      var cc4 = funOASL(strArrayList)
    }
  }
  class StringArrayStringList {
    function funOASL(o: String[]): AAA {
      return null
    }

    function funOASL(o: List<String>): BBB {
      return null
    }

    function caller() {
      var aa1: AAA = funOASL({"g", "o", "s", "u"})
      var aa2: AAA = funOASL(strArray)
      var aa3: AAA = funOASL(strList)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.BBB', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.AAA'
      var aa4: AAA = funOASL(strArrayList)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.BBB', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.AAA'

      var bb1: BBB = funOASL({"g", "o", "s", "u"})      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.AAA', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.BBB'
      var bb2: BBB = funOASL(strArray)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.AAA', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.BBB'
      var bb3: BBB = funOASL(strList)
      var bb4: BBB = funOASL(strArrayList)

      var cc1 = funOASL({"g", "o", "s", "u"})
      var cc2 = funOASL(strArray)
      var cc3 = funOASL(strList)
      var cc4 = funOASL(strArrayList)
    }
  }

  class StringArrayStringArrayList {
    function funOASL(o: String[]): AAA {
      return null
    }

    function funOASL(o: ArrayList<String>): BBB {
      return null
    }

    function caller() {
      var aa1: AAA = funOASL({"g", "o", "s", "u"})      //## issuekeys: AMBIGUOUS METHOD CALL: BOTH 'STRINGARRAYSTRINGARRAYLIST.FUNOASL(STRING[])' AND 'STRINGARRAYSTRINGARRAYLIST.FUNOASL(ARRAYLIST<STRING>)' MATCH
      var aa2: AAA = funOASL(strArray)
      var aa3: AAA = funOASL(strList)      //## issuekeys: CANNOT RESOLVE METHOD 'FUNOASL(JAVA.UTIL.LIST<JAVA.LANG.STRING>)'
      var aa4: AAA = funOASL(strArrayList)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.BBB', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.AAA'

      var bb1: BBB = funOASL({"g", "o", "s", "u"})      //## issuekeys: AMBIGUOUS METHOD CALL: BOTH 'STRINGARRAYSTRINGARRAYLIST.FUNOASL(STRING[])' AND 'STRINGARRAYSTRINGARRAYLIST.FUNOASL(ARRAYLIST<STRING>)' MATCH
      var bb2: BBB = funOASL(strArray)      //## issuekeys: INCOMPATIBLE TYPES. FOUND: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.AAA', REQUIRED: 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.METHODSCORINGOVERLOADING.ARRAYS.TOBEPUSHED.ERRANT_ARRAYLISTSTRING.BBB'
      var bb3: BBB = funOASL(strList)      //## issuekeys: CANNOT RESOLVE METHOD 'FUNOASL(JAVA.UTIL.LIST<JAVA.LANG.STRING>)'
      var bb4: BBB = funOASL(strArrayList)

      var cc1 = funOASL({"g", "o", "s", "u"})      //## issuekeys: AMBIGUOUS METHOD CALL: BOTH 'STRINGARRAYSTRINGARRAYLIST.FUNOASL(STRING[])' AND 'STRINGARRAYSTRINGARRAYLIST.FUNOASL(ARRAYLIST<STRING>)' MATCH
      var cc2 = funOASL(strArray)
      var cc3 = funOASL(strList)      //## issuekeys: CANNOT RESOLVE METHOD 'FUNOASL(JAVA.UTIL.LIST<JAVA.LANG.STRING>)'
      var cc4 = funOASL(strArrayList)
    }
  }
}