package gw.internal.schema.gw.xsd.w3c.soap12_envelope.types.simple;

/***************************************************************************/
/* THIS IS AUTOGENERATED CODE - DO NOT MODIFY OR YOUR CHANGES WILL BE LOST */
/* THIS CODE CAN BE REGENERATED USING 'xsd-codegen'                        */
/***************************************************************************/
public class FaultcodeEnum extends gw.internal.schema.gw.xsd.w3c.xmlschema.types.simple.QName implements gw.internal.xml.IXmlGeneratedClass {

  public static final javax.xml.namespace.QName $QNAME = new javax.xml.namespace.QName( "http://www.w3.org/2003/05/soap-envelope", "faultcodeEnum", "soap12" );
  public static final gw.util.concurrent.LockingLazyVar<gw.lang.reflect.IType> TYPE = new gw.util.concurrent.LockingLazyVar<gw.lang.reflect.IType>( gw.lang.reflect.TypeSystem.getGlobalLock() ) {
          @Override
          protected gw.lang.reflect.IType init() {
            return gw.lang.reflect.TypeSystem.getByFullName( "gw.xsd.w3c.soap12_envelope.types.simple.FaultcodeEnum" );
          }
        };
  private static final gw.util.concurrent.LockingLazyVar<java.lang.Object> SCHEMAINFO = new gw.util.concurrent.LockingLazyVar<java.lang.Object>( gw.lang.reflect.TypeSystem.getGlobalLock() ) {
          @Override
          protected java.lang.Object init() {
            gw.lang.reflect.IType type = TYPE.get();
            return getSchemaInfoByType( type );
          }
        };

  public FaultcodeEnum() {
    super( TYPE.get(), SCHEMAINFO.get() );
  }

  protected FaultcodeEnum( gw.lang.reflect.IType type, java.lang.Object schemaInfo ) {
    super( type, schemaInfo );
  }

  public FaultcodeEnum( gw.internal.schema.gw.xsd.w3c.soap12_envelope.enums.FaultcodeEnum value ) {
    this();
    TYPE.get().getTypeInfo().getProperty( "$Value" ).getAccessor().setValue( this, value );
  }


  @Deprecated
  public javax.xml.namespace.QName getValue$$gw_xsd_w3c_xmlschema_types_simple_QName() {
    return super.getValue$$gw_xsd_w3c_xmlschema_types_simple_QName();
  }

  @Deprecated
  public void setValue$$gw_xsd_w3c_xmlschema_types_simple_QName( javax.xml.namespace.QName param ) {
    super.setValue$$gw_xsd_w3c_xmlschema_types_simple_QName( param );
  }

  public gw.internal.schema.gw.xsd.w3c.soap12_envelope.enums.FaultcodeEnum getValue$$gw_xsd_w3c_soap12_envelope_types_simple_FaultcodeEnum() {
    return (gw.internal.schema.gw.xsd.w3c.soap12_envelope.enums.FaultcodeEnum) TYPE.get().getTypeInfo().getProperty( "$Value" ).getAccessor().getValue( this );
  }

  public void setValue$$gw_xsd_w3c_soap12_envelope_types_simple_FaultcodeEnum( gw.internal.schema.gw.xsd.w3c.soap12_envelope.enums.FaultcodeEnum param ) {
    TYPE.get().getTypeInfo().getProperty( "$Value" ).getAccessor().setValue( this, param );
  }

  @SuppressWarnings( {"UnusedDeclaration"} )
  private static final long FINGERPRINT = -6014282781002754770L;

}
